OMiSCID(aka O3MiSCID): Omiscid::ConnectorListener Class Reference
Omiscid::ConnectorListener Class Reference
#include <ConnectorListener.h>
Public Member Functions
virtual void MessageReceived (Service &TheService, const SimpleString LocalConnectorName, const Message &Msg)
virtual void Connected (Service &TheService, const SimpleString LocalConnectorName, unsigned int PeerId)
virtual void Disconnected (Service &TheService, const SimpleString LocalConnectorName, unsigned int PeerId)
Detailed Description
Defines the listener interface for Omiscid messages. This interface must be implemented in order to receive notifications on Omiscid messages receptions.
Author:
Dominique Vaufreydaz
Definition at line 28 of file ConnectorListener.h.
Member Function Documentation
void ConnectorListener::MessageReceived (Service & TheService, const SimpleString LocalConnectorName, const Message & Msg) [virtual]
Processes a received Omiscid message. As a given message could be processed by several others listeners, the message must not be modified by its processing.
Parameters:
TheService the service which received the message
LocalConnectorName the name of the connector that has received the message
Msg the message to process
Processes a received Omiscid message. As a given message could be processed by several others listeners, the message must not be modified by its processing.
Parameters:
service the service receiving the message
localConnectorName the name of the connector that has received the message
Msg the message to process
Reimplemented in Omiscid::Accumulator.
Definition at line 69 of file ConnectorListener.cpp.
{
}
void ConnectorListener::Connected (Service & TheService, const SimpleString LocalConnectorName, unsigned int PeerId) [virtual]
Called when the connexion between the local service and the remote service is open.
Parameters:
TheService A reference to the service which have a new connected Peer
LocalConnectorName The name of the connector handling the new link
PeerId the connected remote service PeerId
Definition at line 44 of file ConnectorListener.cpp.
References Omiscid::Service::GetName(), and Omiscid::SimpleString::GetStr().
{
    OmiscidTrace( "A new peer %8.8x connects to %s:%s.\n", PeerId, TheService.GetName().GetStr(), LocalConnectorName.GetStr() );
}
void ConnectorListener::Disconnected (Service & TheService, const SimpleString LocalConnectorName, unsigned int PeerId) [virtual]
Called when the connexion between the local service and the remote service is broken.
Parameters:
TheService A reference to the service which losts a connection
LocalConnectorName the name of the connector handling the broken link
PeerId the disconnected remote service PeerId
Definition at line 56 of file ConnectorListener.cpp.
References Omiscid::Service::GetName(), and Omiscid::SimpleString::GetStr().
{
    OmiscidTrace( "The peer %8.8x disconnects from %s:%s.\n", PeerId, TheService.GetName().GetStr(), LocalConnectorName.GetStr() );
}
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/ConnectorListener.h
ServiceControl/ConnectorListener.cpp