OMiSCID(aka O3MiSCID): Omiscid::XMLMessage Class Reference
Omiscid::XMLMessage Class Reference
This class group the data about a parsed message.
#include <ServiceControl/XMLTreeParser.h>
Public Member Functions
XMLMessage ()
Constructor.
XMLMessage (const XMLMessage &msg)
Copy Constructor.
XMLMessage (const Message &MesgFromPeer)
Constructor from a message.
~XMLMessage ()
Destructor.
void Display (FILE *fout=stdout)
Display the message.
xmlNodePtr GetRootNode ()
Access to the root node in the XML message.
Static Public Member Functions
static xmlAttrPtr FindAttribute (const SimpleString name, xmlNodePtr node)
Find a particular attribute.
static xmlNodePtr FindFirstChild (const SimpleString name, xmlNodePtr node)
Find a particular child node.
static void DisplayNode (xmlNodePtr node, FILE *fout)
Display a node.
Public Attributes
xmlDocPtr doc
MessageOrigine origine
unsigned int pid
unsigned int mid
Detailed Description
This class group the data about a parsed message.
Similar to Message (in part Com) but it is used with XML Message, and stored the message as a XML tree. The XML tree is based on the structure given by the library XML 2.
Author:
Sebastien Pesnel
Definition at line 35 of file XMLTreeParser.h.
Constructor & Destructor Documentation
XMLMessage::XMLMessage (const XMLMessage & msg)
Copy Constructor.
The message as XML tree is not copied. Only the pointer on the structure is copied. Before deleting these object, set one of the two doc attribute to NULL, in order to not free two times the same data.
Parameters:
msg [in] the message to copy
Definition at line 36 of file XMLTreeParser.cpp.
References doc, mid, origine, and pid.
{
    if ( msg.doc )
    {
        doc = xmlCopyDoc(msg.doc, 1 ); // 1 stands for recursive copy
    }
    else
    {
        doc = NULL;
    }
    origine = msg.origine;
    pid = msg.pid;
    mid = msg.mid;
}
XMLMessage::XMLMessage (const Message & MesgFromPeer)
Constructor from a message.
Definition at line 19 of file XMLTreeParser.cpp.
References doc, Omiscid::Message::GetBuffer(), Omiscid::Message::GetLength(), Omiscid::Message::GetMsgId(), Omiscid::Message::GetOrigine(), Omiscid::Message::GetPeerId(), mid, origine, Omiscid::XMLTreeParser::ParseMessage(), and pid.
{
    doc         = XMLTreeParser::ParseMessage(MesgFromPeer.GetLength(), (unsigned char*)MesgFromPeer.GetBuffer());;
    origine = MesgFromPeer.GetOrigine();
    pid         = MesgFromPeer.GetPeerId();
    mid         = MesgFromPeer.GetMsgId();
}
XMLMessage::~XMLMessage ()
Destructor.
free the XML tree, if the doc attribute is not NULL.
Definition at line 27 of file XMLTreeParser.cpp.
References doc.
{
    if ( doc != NULL )
    {
        xmlFreeDoc(doc);
        doc = NULL;
    }
}
Member Function Documentation
void XMLMessage::Display (FILE * fout = stdout)
Display the message.
Message can be displayed on screen, or write in file.
Parameters:
fout destination for display
Definition at line 57 of file XMLTreeParser.cpp.
References DisplayNode(), and GetRootNode().
Referenced by Omiscid::XMLTreeParser::ProcessAMessage().
{
    DisplayNode(GetRootNode(), fout);
}
xmlNodePtr XMLMessage::GetRootNode ()
Access to the root node in the XML message.
Returns:
the pointer on the first node in the tree structure
Definition at line 51 of file XMLTreeParser.cpp.
References doc.
Referenced by Omiscid::AnswersManager::CheckMessage(), Omiscid::ControlClient::CtrlEventProcess(), Display(), Omiscid::ControlServer::ProcessAMessage(), Omiscid::ControlClient::ProcessAMessage(), Omiscid::ControlClient::QueryInOutputDescription(), Omiscid::ControlClient::QueryInputDescription(), Omiscid::ControlClient::QueryOutputDescription(), Omiscid::ControlClient::QueryVariableDescription(), Omiscid::ControlClient::QueryVariableModif(), and Omiscid::ControlClient::Subscribe().
{
    if(doc) return xmlDocGetRootElement(doc);
    else return NULL;
}
xmlAttrPtr XMLMessage::FindAttribute (const SimpleString name, xmlNodePtr node) [static]
Find a particular attribute.
Search among the attributes of 'node' for an attribute wit a particular name
Parameters:
name [in] the name for the wanted attribute
node [in] the node where look for this attribute.
Returns:
the found attribute, NULL if not found
Definition at line 62 of file XMLTreeParser.cpp.
Referenced by Omiscid::AnswersManager::CheckMessage(), Omiscid::ControlClient::CtrlEventProcess(), Omiscid::VariableAttribute::ExtractDataFromXml(), Omiscid::InOutputAttribute::ExtractDataFromXml(), and Omiscid::ControlServer::ProcessAMessage().
{
    if(node)
    {
        xmlAttrPtr current = node->properties;
        while(current)
        {
            if( name == (const char*)current->name )
            {
                return current;
            }
            current = current->next;
        }
    }
    return NULL;
}
xmlNodePtr XMLMessage::FindFirstChild (const SimpleString name, xmlNodePtr node) [static]
Find a particular child node.
Search in the children of 'node', the first node with a given name.
Parameters:
name [in] name for the wanted node
node [in] look for the node in the children of this node
Returns:
the first child with the tag 'name', NULL if not child node with that name
Definition at line 79 of file XMLTreeParser.cpp.
Referenced by Omiscid::ControlClient::CtrlEventProcess().
{
    if(node)
    {
        xmlNodePtr current = node->children;
        while(current)
        {
            if( (current->type == XML_ELEMENT_NODE) && (name == (const char*)current->name) )
            {
                return current;
            }
            current = current->next;
        }
    }
    return NULL;
}
void XMLMessage::DisplayNode (xmlNodePtr node, FILE * fout) [static]
Display a node.
Display a node to a file descriptor. Recursive methods called on the node child.
Parameters:
node [in] node to display
fout destination for display
Definition at line 96 of file XMLTreeParser.cpp.
Referenced by Display().
{
    if(node)
    {
        xmlNodePtr current = node->children;
        if(current)
        {
            fprintf(fout, "<%s>\n", node->name);
            while(current)
            {
                if((current->type == XML_ELEMENT_NODE))
                    DisplayNode(current, fout);
                current = current->next;
            }
            fprintf(fout, "</%s>\n", node->name);
        }
        else fprintf(fout, "<%s/>\n", node->name);
    }
}
Member Data Documentation
xmlDocPtr Omiscid::XMLMessage::doc
pointer on the XML tree created with the XML message received
Definition at line 62 of file XMLTreeParser.h.
Referenced by GetRootNode(), Omiscid::ControlServer::ProcessAMessage(), Omiscid::ControlClient::ProcessAMessage(), Omiscid::XMLTreeParser::Receive(), XMLMessage(), and ~XMLMessage().
MessageOrigine Omiscid::XMLMessage::origine
pointer on the source of the message (MsgSocket or UdpConnection object)
Definition at line 63 of file XMLTreeParser.h.
Referenced by XMLMessage().
unsigned int Omiscid::XMLMessage::pid
peer identifier
Definition at line 64 of file XMLTreeParser.h.
Referenced by Omiscid::ControlServer::ProcessAMessage(), and XMLMessage().
unsigned int Omiscid::XMLMessage::mid
message identifier
Definition at line 65 of file XMLTreeParser.h.
Referenced by XMLMessage().
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/XMLTreeParser.h
ServiceControl/XMLTreeParser.cpp