OMiSCID(aka O3MiSCID): Omiscid::ServiceRepository Class Reference
Omiscid::ServiceRepository Class Reference
[User friendly high-level API for Omiscid, Layer 2 : Omiscid multiplateform Service Control layer.]
High level user friendly class to browse Omiscid services.
#include <ServiceControl/ServiceRepository.h>
Public Member Functions
bool AddListener (ServiceRepositoryListener *Listener, bool NotifyOnlyNewEvents=false)
bool AddListener (ServiceRepositoryListener *Listener, ServiceFilter *Filter, bool NotifyOnlyNewEvents=false)
bool RemoveListener (ServiceRepositoryListener *Listener, bool NotifyAsIfExistingServicesDisappear=false)
Detailed Description
High level user friendly class to browse Omiscid services.
Author:
Dominique Vaufreydaz
Definition at line 27 of file ServiceRepository.h.
Member Function Documentation
bool ServiceRepository::AddListener (ServiceRepositoryListener * Listener, bool NotifyOnlyNewEvents = false)
Adds a listener to be notified of service apparitions and disapparitions. Apparition notifications will only happen for all services. Disapparition notifications will only happen for all services.
From this addition, the listener will be notified of each service event (see ServiceRepositoryListener). When a listener is added to the repository, this latter can already contain some services. The boolean parameter tells whether the listener should be notified of these services as if they were appearing.
Parameters:
Listener the listener that will be notified of service events
NotifyOnlyNewEvents a boolean used to ignore services running at the time of listener addition. Setting it to false (default value) will cause the listener to be immediately notified of services already present in the repository
Definition at line 45 of file ServiceRepository.cpp.
{
    return AddListener( Listener, (ServiceFilter*)NULL, NotifyOnlyNewEvents );
}
bool ServiceRepository::AddListener (ServiceRepositoryListener * Listener, ServiceFilter * Filter, bool NotifyOnlyNewEvents = false)
Adds a listener to be notified of service apparitions and disapparitions. Apparition notifications will only happen for services matching given filter. Disapparition notifications will only happen for services that have been notified of apparition.
From this addition, the listener will be notified of each service event (see ServiceRepositoryListener). When a listener is added to the repository, this latter can already contain some services. The boolean parameter tells whether the listener should be notified of these services as if they were appearing.
Parameters:
Listener the listener that will be notified of service events
Filter the filter to apply to service apparition/removal
NotifyOnlyNewEvents a boolean used to ignore services running at the time of listener addition. Setting it to false (default value) will cause the listener to be immediately notified of services already present in the repository
Definition at line 21 of file ServiceRepository.cpp.
References Omiscid::ServiceRepositoryListener::SetFilter(), and Omiscid::SmartLocker::Unlock().
{
    if ( Listener != (ServiceRepositoryListener*)NULL )
    {
        SmartLocker SL_RepoListeners(RepoListeners);
        // Add listener and start its browse
        RepoListeners.AddTail(Listener);
        if ( Filter != (ServiceFilter *)NULL )
        {
            Listener->SetFilter( Filter );
        }
        SL_RepoListeners.Unlock();
        Listener->StartBrowse( NotifyOnlyNewEvents );
        return true;
    }
    return false;
}
bool ServiceRepository::RemoveListener (ServiceRepositoryListener * Listener, bool NotifyAsIfExistingServicesDisappear = false)
Removes a listener from the notification process. Disapparition notifications will only happen if NotifyAsIfExistingServicesDisappear is set to true.
From this removal, the listener will no longer be notified of each service event (see ServiceRepositoryListener). It can be reused later maybe with another filter. The boolean parameter tells whether the listener should be notified of current running services as if they were disappearing.
Parameters:
Listener the listener that will be notified of service events
NotifyAsIfExistingServicesDisappear a boolean used to asked to be notified as if services were disappearing (default value = false)
Definition at line 50 of file ServiceRepository.cpp.
References Omiscid::SmartLocker::Unlock(), and Omiscid::ServiceRepositoryListener::UnsetFilter().
{
    bool Found;
    if ( Listener == (ServiceRepositoryListener*)NULL )
    {
        return false;
    }
    SmartLocker SL_RepoListeners(RepoListeners);
    Found = false;
    for( RepoListeners.First(); RepoListeners.NotAtEnd(); RepoListeners.Next() )
    {
        if ( RepoListeners.GetCurrent() == Listener )
        {
            Found = true;
            RepoListeners.RemoveCurrent();
            break;
        }
    }
    SL_RepoListeners.Unlock();
    if ( Found == true )
    {
        // Stop browse
        Listener->StopBrowse( NotifyAsIfExistingServicesDisappear );
        // Remove its listener
        Listener->UnsetFilter();
        return true;
    }
    return false;
}
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/ServiceRepository.h
ServiceControl/ServiceRepository.cpp