OMiSCID(aka O3MiSCID): Omiscid::SimpleString Class Reference
Omiscid::SimpleString Class Reference
[Layer 0 : Omiscid multiplateform System layer., User friendly high-level API for Omiscid]
Storage and manipulation of character strings.
#include <System/SimpleString.h>
Public Member Functions
SimpleString ()
SimpleString (const char *str)
SimpleString (const char *str1, const char *str2)
SimpleString (const SimpleString &to_copy)
SimpleString (const SimpleString &to_copy1, const SimpleString &to_copy2)
SimpleString (int i)
SimpleString (unsigned int ui)
SimpleString (long int li)
SimpleString (float f)
SimpleString (double d)
virtual ~SimpleString ()
void Empty ()
To empty a string.
bool IsEmpty () const
SimpleString SubString (int begin, int end) const
Extract a string of this string.
Data Access
const char * GetStr () const
unsigned int GetLength () const
char operator[] (int i) const
char & operator[] (int i)
Affectation
const SimpleString & operator= (const char *str)
const SimpleString & operator= (const SimpleString &str)
const SimpleString & operator= (int i)
const SimpleString & operator= (unsigned int ui)
const SimpleString & operator= (long int li)
const SimpleString & operator= (float f)
const SimpleString & operator= (double d)
Data Manipulation : Append String
void Append (const char *str)
void Append (const SimpleString &str)
SimpleString & operator+= (const char *str)
SimpleString & operator+= (const SimpleString &str)
SimpleString & operator+= (unsigned int ui)
SimpleString & operator+= (int i)
SimpleString & operator+= (long l)
SimpleString & operator+= (float f)
SimpleString & operator+= (double d)
Data Comparaison
bool operator== (const SimpleString &str) const
bool operator== (const char *str) const
bool operator!= (const SimpleString &str) const
bool operator!= (const char *str) const
bool EqualsCaseInsensitive (const SimpleString &str) const
bool EqualsCaseInsensitive (const char *str) const
Comparaison
bool Lock () const
bool Unlock () const
Static Public Attributes
static const SimpleString EmptyString
Protected Member Functions
SimpleString (StringData *)
Detailed Description
Storage and manipulation of character strings.
The character strings are duplicate only when they are modified. The copy are done only if necessary. (Use of a counter of reference on the character string)
By default, strings are equals to "".
Author:
Sebastien Pesnel
Dominique Vaufreydaz
Definition at line 35 of file SimpleString.h.
Constructor & Destructor Documentation
SimpleString::SimpleString ()
build an empty string
Definition at line 219 of file SimpleString.cpp.
References Lock(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = new OMISCID_TLM StringData();
    Unlock();
}
SimpleString::SimpleString (const char * str)
build a string with the value 'str'
Definition at line 229 of file SimpleString.cpp.
References Lock(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = new OMISCID_TLM StringData(str);
    Unlock();
}
SimpleString::SimpleString (const char * str1, const char * str2)
Build a String with the value 'str1' followed by 'str2'
Definition at line 239 of file SimpleString.cpp.
References Lock(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = new OMISCID_TLM StringData(str1, str2);
    Unlock();
}
SimpleString::SimpleString (const SimpleString & to_copy)
Copy constructor of the string
Definition at line 249 of file SimpleString.cpp.
References Lock(), stringData, and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    to_copy.Lock();
    // Set data as usual
    // stringData = to_copy.stringData;
    // incr reference count
    // to_copy.stringData->AddReference();
    // Set data as usual
    stringData = new OMISCID_TLM StringData(to_copy.stringData);
    to_copy.Unlock();
    Unlock();
}
SimpleString::SimpleString (const SimpleString & to_copy1, const SimpleString & to_copy2)
Copy constructor for 2 strings
Definition at line 268 of file SimpleString.cpp.
References Lock(), stringData, and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    to_copy1.Lock();
    to_copy2.Lock();
    stringData = new OMISCID_TLM StringData((StringData*)to_copy1.stringData,(StringData*)to_copy2.stringData);
    to_copy2.Unlock();
    to_copy1.Unlock();
    Unlock();
}
SimpleString::SimpleString (int i)
Creating a string representing an interger
Definition at line 298 of file SimpleString.cpp.
References Lock(), operator+=(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = (StringData*)NULL;
    operator+=(i);
    Unlock();
}
SimpleString::SimpleString (unsigned int ui)
Creating a string representing an unsigned interger
Definition at line 309 of file SimpleString.cpp.
References Lock(), operator+=(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = (StringData*)NULL;
    operator+=(ui);
    Unlock();
}
SimpleString::SimpleString (long int li)
Creating a string representing a long interger
Definition at line 320 of file SimpleString.cpp.
References Lock(), operator+=(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = (StringData*)NULL;
    operator+=(li);
    Unlock();
}
SimpleString::SimpleString (float f)
Creating a string representing a float
Definition at line 331 of file SimpleString.cpp.
References Lock(), operator+=(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = (StringData*)NULL;
    operator+=(f);
    Unlock();
}
SimpleString::SimpleString (double d)
Creating a string representing a double
Definition at line 342 of file SimpleString.cpp.
References Lock(), operator+=(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    stringData = (StringData*)NULL;
    operator+=(d);
    Unlock();
}
SimpleString::SimpleString (StringData * sd) [protected]
used by SubString
Definition at line 282 of file SimpleString.cpp.
References Lock(), and Unlock().
    : stringData((StringData*)NULL), Protect()
{
    Lock();
    // Set data as usual
    // stringData = sd;
    // incr reference count
    // sd->AddReference();
    // Set data as usual
    stringData = new OMISCID_TLM StringData(sd);
    Unlock();
}
SimpleString::~SimpleString () [virtual]
Destructor (free if necessary, the underlying buffer)
Definition at line 353 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    // Lock is not done in DestroyStringData
    Lock();
    DestroyStringData();
    Unlock();
}
Member Function Documentation
const char * SimpleString::GetStr () const
Returns:
the character string
Definition at line 897 of file SimpleString.cpp.
Referenced by Omiscid::Service::AddConnector(), Omiscid::Service::AddConnectorListener(), Omiscid::ValueListener::AddListener(), Omiscid::Service::AddVariable(), Omiscid::Service::CloseAllConnections(), Omiscid::Service::CloseConnection(), Omiscid::ControlServer::Connect(), Omiscid::ConnectorListener::Connected(), Omiscid::Service::ConnectTo(), Omiscid::ConnectorListener::Disconnected(), Omiscid::SimpleException::Display(), Omiscid::VariableAttribute::Display(), Omiscid::ControlServer::DisplayServiceGlobalShortDescription(), Omiscid::VariableAttribute::ExtractDataFromXml(), Omiscid::InOutputAttribute::ExtractDataFromXml(), Omiscid::ControlServer::FindInOutput(), Omiscid::ControlServer::FindVariable(), Omiscid::Attribute::GenerateHeaderDescription(), Omiscid::Service::GetVariableAccessTypeType(), Omiscid::Service::GetVariableDescription(), Omiscid::Service::GetVariableValue(), Omiscid::Accumulator::MessageReceived(), Omiscid::XMLTreeParser::ParseFile(), Omiscid::ComTools::PeerIdFromString(), Omiscid::ControlServer::ProcessAMessage(), Omiscid::XMLTreeParser::ProcessMessages(), Omiscid::MsgManager::ProcessMessages(), Omiscid::ControlClient::QueryInOutputDescription(), Omiscid::ControlClient::QueryInputDescription(), Omiscid::ControlClient::QueryOutputDescription(), Omiscid::ControlClient::QueryVariableDescription(), Omiscid::ControlClient::QueryVariableModif(), Omiscid::Service::RemoveAllConnectorListeners(), Omiscid::Service::RemoveConnectorListener(), Omiscid::XMLTreeParser::Run(), Omiscid::MsgSocket::Send(), Omiscid::MsgSocket::SendCuttedMsg(), Omiscid::MsgSocket::SendPreparedBuffer(), Omiscid::Service::SendReplyToMessage(), Omiscid::UdpExchange::SendTo(), Omiscid::MsgSocket::SendTo(), Omiscid::UdpExchange::SendToAll(), Omiscid::Connector::SendToAll(), Omiscid::Service::SendToAllClients(), Omiscid::TcpServer::SendToAllClients(), Omiscid::TcpServer::SendToClient(), Omiscid::Service::SendToOneClient(), Omiscid::Connector::SendToPeer(), Omiscid::Service::SetVariableDescription(), Omiscid::Service::SetVariableValue(), Omiscid::SimpleException::SimpleException(), Omiscid::ControlServer::StartServer(), Omiscid::Message::ToString(), and Omiscid::ControlServer::VariableChange().
{
    return (const char*)stringData->data;
}
unsigned int SimpleString::GetLength () const
Returns:
the length of the string
Definition at line 902 of file SimpleString.cpp.
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::Attribute::GenerateHeaderDescription(), Omiscid::Accumulator::MessageReceived(), Omiscid::Service::SendReplyToMessage(), Omiscid::Service::SendToAllClients(), Omiscid::Service::SendToOneClient(), Omiscid::ServiceProperty::SetProperty(), SubString(), and Omiscid::ServiceProperty::UpdateProperty().
{
    return stringData->length;
}
char SimpleString::operator[] (int i) const
read access on the characters
Parameters:
i [in] the index of the character between 0 and GetLength()-1
Definition at line 547 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    char tmp;
    if ( i < 0 || i >= (int)stringData->length )
    {
        Unlock();
        throw  SimpleException("SimpleString::out of bound");
    }
    tmp = *(stringData->data+i);
    Unlock();
    // retreive character at position
    return tmp;
}
char & SimpleString::operator[] (int i)
read-write access on the characters
Parameters:
i [in] the index of the character between 0 and GetLength()-1
Definition at line 567 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    if ( i < 0 || i >= (int)stringData->length )
    {
        Unlock();
        throw  SimpleException("SimpleString::out of bound");
    }
    char& tmp = *(stringData->data+i);
    Unlock();
    return tmp;
}
bool SimpleString::IsEmpty () const
Returns:
true if the string is empty, false otherwise
Definition at line 907 of file SimpleString.cpp.
Referenced by Omiscid::ControlServer::AddInOutput(), Omiscid::ControlServer::AddVariable(), Omiscid::Factory::Create(), Omiscid::MsgSocket::GetName(), Omiscid::ComTools::PeerIdFromString(), and Omiscid::SimpleException::SimpleException().
{
    return (stringData == NULL || stringData->length == 0 );
}
const SimpleString & SimpleString::operator= (const char * str)
assign 'str' as content for this string
Definition at line 421 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    DestroyStringData();
    stringData = new OMISCID_TLM StringData(str);
    Unlock();
    return *this;
}
const SimpleString & SimpleString::operator= (const SimpleString & str)
assign 'str' as content for this string
Definition at line 405 of file SimpleString.cpp.
References Lock(), stringData, and Unlock().
{
    Lock();
    str.Lock();
    DestroyStringData();
    // stringData = str.stringData;
    // stringData->AddReference();
    stringData = new OMISCID_TLM StringData(str.stringData);
    str.Unlock();
    Unlock();
    return *this;
}
const SimpleString & SimpleString::operator= (int i)
assign a string representation of an interger as content for this string
Definition at line 433 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    DestroyStringData();
    TemporaryMemoryBuffer tmp(25);
    snprintf((char*)tmp, 20, "%d", i);
    stringData = new OMISCID_TLM StringData((char*)tmp);
    Unlock();
    return *this;
}
const SimpleString & SimpleString::operator= (unsigned int ui)
assign a string representation of an unsigned interger as content for this string
Definition at line 447 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    DestroyStringData();
    TemporaryMemoryBuffer tmp(25);
    snprintf((char*)tmp, 20, "%u", ui);
    stringData = new OMISCID_TLM StringData((char*)tmp);
    Unlock();
    return *this;
}
const SimpleString & SimpleString::operator= (long int li)
assign a string representation of a long interger as content for this string
Definition at line 463 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    DestroyStringData();
    TemporaryMemoryBuffer tmp(55);
    snprintf((char*)tmp, 50, "%li", li);
    stringData = new OMISCID_TLM StringData((char*)tmp);
    Unlock();
    return *this;
}
const SimpleString & SimpleString::operator= (float f)
assign a string representation of a float as content for this string
Definition at line 478 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    DestroyStringData();
    TemporaryMemoryBuffer tmp(55);
    snprintf((char*)tmp, 50, "%f", f);
    stringData = new OMISCID_TLM StringData((char*)tmp);
    Unlock();
    return *this;
}
const SimpleString & SimpleString::operator= (double d)
assign a string representation of double as content for this string
Definition at line 493 of file SimpleString.cpp.
References Lock(), and Unlock().
{
    Lock();
    DestroyStringData();
    TemporaryMemoryBuffer tmp(55);
    // warning: ISO C++ does not support the '%lf' printf format
    snprintf((char*)tmp, 50, "%f", d);
    stringData = new OMISCID_TLM StringData((char*)tmp);
    Unlock();
    return *this;
}
void SimpleString::Append (const char * str)
add 'str' to the end of this string
Definition at line 509 of file SimpleString.cpp.
References Lock(), and Unlock().
Referenced by operator+=().
{
    if ( str != NULL )
    {
        Lock();
        StringData* tmp;
        if ( stringData != (StringData*)NULL )
        {
            tmp = new OMISCID_TLM StringData(stringData, str);
            DestroyStringData();
            stringData = tmp;
        }
        else
        {
            stringData = new OMISCID_TLM StringData(str);
        }
        Unlock();
    }
}
void SimpleString::Append (const SimpleString & str)
add 'str' to the end of this string
Definition at line 531 of file SimpleString.cpp.
References Lock(), stringData, and Unlock().
{
    if ( str.stringData->length != 0 )
    {
        Lock();
        str.Lock();
        StringData* tmp = new OMISCID_TLM StringData(stringData, str.stringData);
        DestroyStringData();
        stringData = tmp;
        str.Unlock();
        Unlock();
    }
}
SimpleString & SimpleString::operator+= (const char * str)
add 'str' to the end of this string
Definition at line 584 of file SimpleString.cpp.
References Append().
Referenced by SimpleString().
{
    Append(str);
    return *this;
}
SimpleString & SimpleString::operator+= (const SimpleString & str)
add 'str' to the end of this string
Definition at line 590 of file SimpleString.cpp.
References Append().
{
    Append(str);
    return *this;
}
SimpleString & SimpleString::operator+= (unsigned int ui)
add the integer 'i' changed in string to the end of this string
Definition at line 604 of file SimpleString.cpp.
References Append().
{
    TemporaryMemoryBuffer tmp(20);
    snprintf((char*)tmp, 20, "%u", ui);
    Append((char*)tmp);
    return *this;
}
SimpleString & SimpleString::operator+= (int i)
add the integer 'i' changed in string to the end of this string
Definition at line 596 of file SimpleString.cpp.
References Append().
{
    TemporaryMemoryBuffer tmp(20);
    snprintf((char*)tmp, 20, "%d", i);
    Append((char*)tmp);
    return *this;
}
SimpleString & SimpleString::operator+= (long l)
add the long integer 'l' changed in string to the end of this string
Definition at line 612 of file SimpleString.cpp.
References Append().
{
    TemporaryMemoryBuffer tmp(50);
    snprintf((char*)tmp, 50, "%li", l);
    Append((char*)tmp);
    return *this;
}
SimpleString & SimpleString::operator+= (float f)
add the long integer 'l' changed in string to the end of this string
Definition at line 620 of file SimpleString.cpp.
References Append().
{
    TemporaryMemoryBuffer tmp(50);
    snprintf((char*)tmp, 50, "%f", f);
    Append((char*)tmp);
    return *this;
}
SimpleString & SimpleString::operator+= (double d)
add the integer 'd' changed in string (using no specific formating) to the end of this string
Definition at line 628 of file SimpleString.cpp.
References Append().
{
    TemporaryMemoryBuffer tmp(50);
    // warning: ISO C++ does not support the '%lf' printf format
    snprintf((char*)tmp, 50, "%f", d);
    Append((char*)tmp);
    return *this;
}
bool SimpleString::operator== (const SimpleString & str) const
Compare (case sensitive) 2 strings to check if they are equals
Definition at line 912 of file SimpleString.cpp.
References stringData.
{
    return stringData->Equals(*(str.stringData));
}
bool SimpleString::operator== (const char * str) const
Compare (case sensitive) 2 strings to check if they are equals
Definition at line 917 of file SimpleString.cpp.
{
    return stringData->Equals(str);
}
bool SimpleString::operator!= (const SimpleString & str) const
Compare (case sensitive) 2 strings to check if they are *not* equals
Definition at line 922 of file SimpleString.cpp.
References stringData.
{
    return stringData->NotEquals(*(str.stringData));
}
bool SimpleString::operator!= (const char * str) const
Compare (case sensitive) 2 strings to check if they are *not* equals
Definition at line 927 of file SimpleString.cpp.
{
    return stringData->NotEquals(str);
}
bool SimpleString::EqualsCaseInsensitive (const SimpleString & str) const
Compare (case insensitive) 2 strings to check if they are equals
Definition at line 933 of file SimpleString.cpp.
References stringData.
{
    return stringData->EqualsCaseInsensitive(*(str.stringData));
}
bool SimpleString::EqualsCaseInsensitive (const char * str) const
Compare (case insensitive) 2 strings to check if they are equals
Definition at line 939 of file SimpleString.cpp.
{
    return stringData->EqualsCaseInsensitive(str);
}
bool SimpleString::Lock () const
Lock my internal data
Definition at line 208 of file SimpleString.cpp.
Referenced by Append(), Empty(), operator=(), operator[](), SimpleString(), SubString(), and ~SimpleString().
{
    return ((Omiscid::ReentrantMutex&)Protect).Lock();
}
bool SimpleString::Unlock () const
Unlock my internal data
Definition at line 214 of file SimpleString.cpp.
Referenced by Append(), Empty(), operator=(), operator[](), SimpleString(), SubString(), and ~SimpleString().
{
    return ((Omiscid::ReentrantMutex&)Protect).Unlock();
}
SimpleString SimpleString::SubString (int begin, int end) const
Extract a string of this string.
Parameters:
[in] begin index of the first character included in the result string
[in] end index of the first excluded character return A new string conaining the sub-string
Definition at line 637 of file SimpleString.cpp.
References EmptyString, GetLength(), Lock(), SetStringData(), and Unlock().
{
    int lend = end;
    if ( lend < 0 )
    {
        if ( lend == -1 )
        {
            lend = GetLength();
        }
        else
        {
            return SimpleString::EmptyString;
        }
    }
    if ( begin >= lend )        // The Could not do the job, or job is empty return an empty string
    {
        return SimpleString::EmptyString;
    }
    // Lock myself
    Lock();
    StringData * sd = new OMISCID_TLM StringData((StringData*)stringData, begin, lend);
    // Unlock
    Unlock();
    if ( sd == NULL )
    {
        return EmptyString;
    }
    else
    {
        SimpleString TmpS;
        TmpS.SetStringData(sd);
        return TmpS;
    }
}
Member Data Documentation
const SimpleString SimpleString::EmptyString [static]
All empty string refer to this unique instance, can be used by user
Definition at line 249 of file SimpleString.h.
Referenced by Omiscid::ServiceProxy::FindConnector(), Omiscid::ServiceProxy::GetPeerIdAsString(), Omiscid::ControlServer::GetRegisteredServiceName(), Omiscid::Service::GetVariableAccessTypeType(), Omiscid::Service::GetVariableDescription(), Omiscid::Service::GetVariableType(), Omiscid::Service::GetVariableValue(), Omiscid::MsgSocket::InitForTcpServer(), Omiscid::MsgSocket::InitForUdpExchange(), Omiscid::InOutputAttribute::KindToStr(), and SubString().
The documentation for this class was generated from the following files:
System/System/SimpleString.h
System/SimpleString.cpp