OMiSCID(aka O3MiSCID): Omiscid::InOutputAttribute Class Reference
Omiscid::InOutputAttribute Class Reference
Class to manage the input or output of a service.
#include <ServiceControl/InOutputAttribute.h>
Public Member Functions
const SimpleString & KindToStr () const
String associated to the kind of the object.
void ExtractDataFromXml (xmlNodePtr node)
Extract data from XML.
Constructors
InOutputAttribute ()
Default Constructor.
InOutputAttribute (const SimpleString a_name, ComTools *com_tool, ConnectorKind kind_of_input)
Constructor.
InOutputAttribute (const SimpleString a_name, ConnectorKind kind_of_input)
Constructor.
Read Accessors
bool IsAnInput () const
bool IsAnOutput () const
bool IsAnInOutput () const
ConnectorKind GetType () const
int GetTcpPort ()
int GetUdpPort ()
unsigned int GetPeerId ()
const SimpleList< unsigned int > & GetListPeerId ()
Write Accessors
void SetKindOfInput (ConnectorKind kind_of_input)
void SetComTool (ComTools *com_tool)
ComTools * GetComTool ()
Write Accessor for data storage when request to controlServer
Methods use by the ControlClient class.
void SetTcpPort (unsigned short port)
void SetUdpPort (unsigned short port)
void AddPeer (unsigned int peer_id)
XML Generation
void GenerateShortDescription (SimpleString &str)
Add to str a short xml description of the attribut.
void GenerateLongDescription (SimpleString &str)
Add to str a long xml description of the attribut.
void GenerateConnectAnswer (SimpleString &str)
void GenerateRecordData (SimpleString &str)
Static Public Attributes
static const SimpleString input_str = "input"
static const SimpleString output_str = "output"
static const SimpleString inoutput_str = "inoutput"
static const SimpleString unknown_str = "unknown type"
Protected Attributes
ConnectorKind kindOfInput
ComTools * comTool
unsigned int peerId
unsigned short tcpPort
unsigned short udpPort
SimpleList< unsigned int > listPeerId
Detailed Description
Class to manage the input or output of a service.
Contains the description of the input, the port TCP, UDP ....
Author:
Sebastien Pesnel
Definition at line 27 of file InOutputAttribute.h.
Constructor & Destructor Documentation
InOutputAttribute::InOutputAttribute (const SimpleString a_name, ComTools * com_tool, ConnectorKind kind_of_input)
Constructor.
Parameters:
a_name name for the input/output
com_tool Communication tool assciated to the input/output
kind_of_input define if the object is AnInput, AnOutput or AnInOutput
Definition at line 21 of file InOutputAttribute.cpp.
References comTool, kindOfInput, peerId, tcpPort, and udpPort.
        : Attribute(a_name)
{
  comTool = com_tool;
  kindOfInput = kind_of_input;
  peerId = 0;
  tcpPort = 0; udpPort = 0;
}
InOutputAttribute::InOutputAttribute (const SimpleString a_name, ConnectorKind kind_of_input)
Constructor.
Parameters:
a_name name for the input/output
kind_of_input define if the object is AnInput, AnOutput or AnInOutput
Definition at line 30 of file InOutputAttribute.cpp.
References comTool, kindOfInput, peerId, tcpPort, and udpPort.
  : Attribute(a_name)
{
  kindOfInput = kind_of_input;
  comTool = NULL;
  peerId = 0;
  tcpPort = 0; udpPort = 0;
}
Member Function Documentation
bool InOutputAttribute::IsAnInput () const
test if the object kind is AnInput
Definition at line 238 of file InOutputAttribute.cpp.
References kindOfInput.
Referenced by Omiscid::Service::SendToAllClients(), and Omiscid::Service::SendToOneClient().
{
    return kindOfInput == AnInput;
}
bool InOutputAttribute::IsAnOutput () const
test if the object kind is AnOutput
Definition at line 243 of file InOutputAttribute.cpp.
References kindOfInput.
Referenced by Omiscid::Service::AddConnectorListener().
{
    return kindOfInput == AnOutput;
}
bool InOutputAttribute::IsAnInOutput () const
test if the object kind is AnInOutput
Definition at line 248 of file InOutputAttribute.cpp.
References kindOfInput.
{
    return kindOfInput == AnInOutput;
}
ConnectorKind InOutputAttribute::GetType () const
retrieve the object kind
Definition at line 253 of file InOutputAttribute.cpp.
References kindOfInput.
Referenced by Omiscid::Service::ConnectTo(), and Omiscid::ServiceProxy::HasConnector().
{
    return kindOfInput;
}
int InOutputAttribute::GetTcpPort ()
Access to port number for TCP
Definition at line 273 of file InOutputAttribute.cpp.
References comTool, Omiscid::ComTools::GetTcpPort(), and tcpPort.
Referenced by GenerateLongDescription().
{
    return comTool == NULL ? tcpPort : comTool->GetTcpPort();
}
int InOutputAttribute::GetUdpPort ()
Access to port number for UDP
Definition at line 278 of file InOutputAttribute.cpp.
References comTool, Omiscid::ComTools::GetUdpPort(), and udpPort.
Referenced by GenerateLongDescription().
{
    return comTool == NULL ? udpPort : comTool->GetUdpPort();
}
unsigned int InOutputAttribute::GetPeerId ()
Will return either the comtool peerid either the local one for distant usage
Definition at line 43 of file InOutputAttribute.cpp.
References comTool, Omiscid::ComTools::GetServiceId(), and peerId.
{
    if ( comTool )
    {
        return comTool->GetServiceId();
    }
    return peerId;
}
const SimpleList< unsigned int > & InOutputAttribute::GetListPeerId ()
Access to the list of connected peer
Definition at line 151 of file InOutputAttribute.cpp.
References comTool, Omiscid::SimpleList< TYPE >::Empty(), Omiscid::ComTools::GetListPeerId(), and listPeerId.
Referenced by Omiscid::Service::GetConnectorClientCount().
{
  if(comTool)
    {
      listPeerId.Empty();
      comTool->GetListPeerId(listPeerId);
    }
  return listPeerId;
}
void InOutputAttribute::SetKindOfInput (ConnectorKind kind_of_input)
Change the kind of the object
Definition at line 258 of file InOutputAttribute.cpp.
References kindOfInput.
{
    kindOfInput = kind_of_input;
}
void InOutputAttribute::SetComTool (ComTools * com_tool)
define the comunication tool associated to the input/output
Definition at line 263 of file InOutputAttribute.cpp.
References comTool.
{
    comTool = com_tool;
}
ComTools * InOutputAttribute::GetComTool ()
retrieve the comunication tool associated to the input/output
Definition at line 268 of file InOutputAttribute.cpp.
References comTool.
Referenced by Omiscid::Service::AddConnectorListener(), Omiscid::Service::CloseAllConnections(), Omiscid::Service::CloseConnection(), Omiscid::Service::ConnectTo(), Omiscid::Service::RemoveAllConnectorListeners(), Omiscid::Service::RemoveConnectorListener(), Omiscid::Service::SendToAllClients(), and Omiscid::Service::SendToOneClient().
{
    return comTool;
}
void InOutputAttribute::GenerateShortDescription (SimpleString & str) [virtual]
Add to str a short xml description of the attribut.
This description is composed by the kind of the attribute and the name. It can be generated with the method GenerateHeaderDescription. (to implement in the child)
Parameters:
str [in, out] the SimpleString where add the description
Implements Omiscid::Attribute.
Definition at line 52 of file InOutputAttribute.cpp.
References Omiscid::Attribute::GenerateHeaderDescription(), and KindToStr().
{
  GenerateHeaderDescription(KindToStr(), GetName(), str);
}
void InOutputAttribute::GenerateLongDescription (SimpleString & str) [virtual]
Add to str a long xml description of the attribut.
This description contained the descriptions and other data defined in child class. The description information can be added to a string with the method AddTagDescriptionToStr (to implement in the child)
Parameters:
str [in, out] the SimpleString where add the description
Implements Omiscid::Attribute.
Definition at line 57 of file InOutputAttribute.cpp.
References Omiscid::Attribute::AddTagDescriptionToStr(), comTool, Omiscid::SimpleList< TYPE >::Empty(), Omiscid::SimpleList< TYPE >::First(), Omiscid::Attribute::GenerateHeaderDescription(), Omiscid::SimpleList< TYPE >::GetCurrent(), Omiscid::ComTools::GetListPeerId(), Omiscid::SimpleList< TYPE >::GetNumberOfElements(), Omiscid::ComTools::GetServiceId(), GetTcpPort(), GetUdpPort(), KindToStr(), Omiscid::SimpleList< TYPE >::Next(), and Omiscid::SimpleList< TYPE >::NotAtEnd().
Referenced by GenerateConnectAnswer().
{
    // Estimate max size
    // "<tcp>" + tmp + "</tcp>" + "<udp>" + tmp + "</udp>" + "<peerId>" + tmp+ "</peerId>" +
    // "<peers>" + {"<peer>"+ tmp +"</peer>" ...} + "</peers>" + "</" + KindToStr() +">"
    int MaxLenForBuffer = 100; // almost "<tcp>" + tmp + "</tcp>" + "<udp>" + tmp + "</udp>" + "<peerId>" + tmp+ "</peerId>"
    // Retrieve number of connected peer
    SimpleList<unsigned int> listPeer;
    comTool->GetListPeerId(listPeer);
    // Ok, if need, so
    // "<peers>" + listPeer.GetNumberOfElements() * "<peer>"+ tmp +"</peer>" + "</peers>" + "</" + KindToStr() +">"
    if ( listPeer.GetNumberOfElements() >= 2 )
    {
        MaxLenForBuffer = 7 + listPeer.GetNumberOfElements() * 25 + 8 + 50;
    }
    TemporaryMemoryBuffer tmp(MaxLenForBuffer);
    char * WhereToWrite = (char*)tmp;
    int SizeAvailable   = MaxLenForBuffer;
    GenerateHeaderDescription(KindToStr(), GetName(), str, false);
    if ( GetTcpPort() != 0 )
    {
        WhereToWrite += snprintf(WhereToWrite, SizeAvailable, "<tcp>%d</tcp>", GetTcpPort());
        SizeAvailable -= 22;
    }
    if ( GetUdpPort() != 0 )
    {
        WhereToWrite += snprintf(WhereToWrite, SizeAvailable, "<udp>%d</udp>", GetUdpPort());
        SizeAvailable -= 22;
    }
    snprintf( WhereToWrite, SizeAvailable, "<peerId>%8.8x</peerId>", comTool->GetServiceId() );
    str += (char*)tmp;
    AddTagDescriptionToStr(str);
    WhereToWrite = (char*)tmp;
    SizeAvailable   = MaxLenForBuffer;
    WhereToWrite += snprintf(WhereToWrite, SizeAvailable, "<peers>" );
    SizeAvailable -= 7;
    for( listPeer.First(); listPeer.NotAtEnd();  listPeer.Next())
    {
        WhereToWrite += snprintf(WhereToWrite, SizeAvailable, "<peer>%08x</peer>",  listPeer.GetCurrent());
        SizeAvailable -= 21;
    }
    snprintf(WhereToWrite, SizeAvailable, "</peers></%s>",  KindToStr().GetStr() );
    str += (char*)tmp;
    listPeer.Empty();
}
void InOutputAttribute::GenerateConnectAnswer (SimpleString & str)
generates XML answer to connect request
Definition at line 283 of file InOutputAttribute.cpp.
References GenerateLongDescription().
{
    GenerateLongDescription(str);
}
void InOutputAttribute::GenerateRecordData (SimpleString & str)
add to SimpleString the SimpleString 'portTcp/portUdp'
Definition at line 116 of file InOutputAttribute.cpp.
References comTool, Omiscid::ComTools::GetTcpPort(), Omiscid::ComTools::GetUdpPort(), tcpPort, and udpPort.
{
  // OmiscidTrace( "in InOutputAttribute::GenerateRecordData\n");
  // OmiscidTrace( "str before : |%s| \n", str.GetStr());
  // OmiscidTrace( "Tcp port (%p) : %d %d \n", comTool, GetTcpPort() ,comTool->GetTcpPort());
  TemporaryMemoryBuffer tmp(30);
  int tcp, udp;
  if(comTool == NULL)
    {
      tcp = tcpPort;
      udp = udpPort;
    }
  else
    {
      tcp = comTool->GetTcpPort();
      udp = comTool->GetUdpPort();
    }
  if(tcp != 0)
    {
      snprintf(tmp, 30, "%d", tcp);
      str = tmp;
    }
  if(udp != 0)
    {
      snprintf(tmp, 30, "%d", udp);
      str = str + "/" + tmp;
    }
  // OmiscidTrace( "str after : %s \n", str.GetStr());
  // OmiscidTrace( "out InOutputAttribute::GenerateRecordData\n");
}
void InOutputAttribute::ExtractDataFromXml (xmlNodePtr node)
Extract data from XML.
Extract the name, the child node (but not the kind).
Parameters:
node XML node with tag name input, output or inoutput
Definition at line 181 of file InOutputAttribute.cpp.
References Omiscid::XMLMessage::FindAttribute(), Omiscid::SimpleString::GetStr(), and peerId.
{
  //parcours attributs
  xmlAttrPtr attr_name = XMLMessage::FindAttribute("name", node);
  if(attr_name)
    {
      SetName(SimpleString((const char*)attr_name->children->content));
    }
  //parcours child tag
  xmlNodePtr cur_node = node->children;
  for(; cur_node; cur_node = cur_node->next)
  {
      if (cur_node->type == XML_ELEMENT_NODE)
      {
          SimpleString cur_name = (const char*)cur_node->name;
          if( cur_name == "description" )
          {
              SetDescription( XMLMessage::ExtractTextContent(cur_node->children) );
          }
          else if( cur_name == "formatDescription" )
          {
              SetDescription( XMLMessage::ExtractTextContent(cur_node->children) );
          }
          else if ( cur_name == "tcp" )
          {
              SetTcpPort( (unsigned short)atoi(XMLMessage::ExtractTextContent(cur_node->children).GetStr()) );
          }
          else if ( cur_name == "udp" )
          {
              SetUdpPort( (unsigned short)atoi(XMLMessage::ExtractTextContent(cur_node->children).GetStr()) );
          }
          else if ( cur_name == "peerId" )
          {
              sscanf( XMLMessage::ExtractTextContent(cur_node->children).GetStr(), "%x", &peerId );
          }
          else if ( cur_name == "peers" )
          {
              xmlNodePtr node_peer = cur_node->children;
              for(; node_peer; node_peer = node_peer->next)
              {
                  if((node_peer->type == XML_ELEMENT_NODE) && strcmp((const char*)node_peer->name, "peer") == 0)
                  {
                      unsigned int ConnectedPeerId;
                      sscanf( XMLMessage::ExtractTextContent(node_peer->children).GetStr(), "%x", &ConnectedPeerId );
                      AddPeer(ConnectedPeerId);
                  }
              }
          }
          else
          {
              OmiscidError( "Unwaited Tag : %s\n", cur_name.GetStr() );
          }
      }
  }
}
Member Data Documentation
const SimpleString InOutputAttribute::input_str = "input" [static]
String associated to the kind AnInput
Definition at line 32 of file InOutputAttribute.h.
Referenced by KindToStr(), Omiscid::ControlServer::ProcessAMessage(), and Omiscid::ControlClient::QueryInputDescription().
const SimpleString InOutputAttribute::output_str = "output" [static]
String associated to the kind AnOutput
Definition at line 33 of file InOutputAttribute.h.
Referenced by KindToStr(), Omiscid::ControlServer::ProcessAMessage(), and Omiscid::ControlClient::QueryOutputDescription().
const SimpleString InOutputAttribute::inoutput_str = "inoutput" [static]
String associated to the kind AnInOutput
Definition at line 34 of file InOutputAttribute.h.
Referenced by KindToStr(), Omiscid::ControlServer::ProcessAMessage(), and Omiscid::ControlClient::QueryInOutputDescription().
const SimpleString InOutputAttribute::unknown_str = "unknown type" [static]
String associated to the kind UnknownConnectorKind
Definition at line 35 of file InOutputAttribute.h.
Referenced by KindToStr().
ConnectorKind Omiscid::InOutputAttribute::kindOfInput [protected]
0 if input, 1 of output, 2 if input/output
Definition at line 113 of file InOutputAttribute.h.
Referenced by GetType(), InOutputAttribute(), IsAnInOutput(), IsAnInput(), IsAnOutput(), KindToStr(), and SetKindOfInput().
ComTools* Omiscid::InOutputAttribute::comTool [protected]
the pointer on the tool of communication associated to this input or output object
Definition at line 115 of file InOutputAttribute.h.
Referenced by GenerateLongDescription(), GenerateRecordData(), GetComTool(), GetListPeerId(), GetPeerId(), GetTcpPort(), GetUdpPort(), InOutputAttribute(), and SetComTool().
unsigned int Omiscid::InOutputAttribute::peerId [protected]
needed in case of distant usage, because we do not have a comtool
Definition at line 116 of file InOutputAttribute.h.
Referenced by ExtractDataFromXml(), GetPeerId(), and InOutputAttribute().
unsigned short Omiscid::InOutputAttribute::tcpPort [protected]
port number for TCP
Definition at line 118 of file InOutputAttribute.h.
Referenced by GenerateRecordData(), GetTcpPort(), and InOutputAttribute().
unsigned short Omiscid::InOutputAttribute::udpPort [protected]
port number for UDP
Definition at line 119 of file InOutputAttribute.h.
Referenced by GenerateRecordData(), GetUdpPort(), and InOutputAttribute().
SimpleList<unsigned int> Omiscid::InOutputAttribute::listPeerId [protected]
list of connected peer
Definition at line 121 of file InOutputAttribute.h.
Referenced by GetListPeerId().
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/InOutputAttribute.h
ServiceControl/InOutputAttribute.cpp