OMiSCID(aka O3MiSCID): Omiscid::MsgSocket Class Reference
Omiscid::MsgSocket Class Reference
Socket with an implementation of Basic Interconnection Protocol to exchange message.
#include <Com/MsgSocket.h>
Public Types
enum MsgSocketKind { , TCP_CLIENT_KIND = 0, TCP_SERVER_KIND, UDP_EXCHANGE_KIND }
Kind of use of a MsgSocket object.
typedef void(FUNCTION_CALL_TYPE * Callback_SyncLink)(MsgSocketCallBackData *, MsgSocket *)
Callback for the message reception.
Public Member Functions
MsgSocket (Socket *s)
Constructor.
MsgSocket (Socket::SocketKind type)
Constructor.
virtual ~MsgSocket ()
Destructor.
void InitForTcpClient (const SimpleString addr, int port)
Initialization for TCP Client.
void InitForTcpServer (int port)
Initialization for TCP Server.
void InitForUdpExchange (int port)
Initialization for UDP Exchange.
bool AddCallbackObject (MsgSocketCallbackObject *CallbackObject)
define callback function called in receive
bool RemoveCallbackObject (MsgSocketCallbackObject *CallbackObject)
Remove the callback for message reception.
void RemoveAllCallbackObjects ()
Remove all the callback object for notification.
void SetCallbackSyncLink (Callback_SyncLink cr, void *user_data1=NULL, void *user_data2=NULL)
define callback function called in receive
void FUNCTION_CALL_TYPE Run ()
method call when the Thread is started
int Send (int len, const char *buf)
Send a message (on TCP) by using the BIP protocol.
int SendPreparedBuffer (int len, char *buf)
Send a preformated BIP message (on TCP) by using the BIP protocol.
int SendCuttedMsg (int *tab_len, const char **tab_buf, int nb_buf)
Send a message in several part (on TCP) by using the BIP protocol.
int SendTo (int len, const char *buf, UdpConnection *udp_dest)
Socket * GetSocket () const
Access to the socket object.
unsigned short GetPortNb () const
Access to Port number.
bool IsConnected () const
Test if the MsgSocket is in usage.
void Stop ()
Stop the MsgSocket.
void SetServiceId (unsigned int pid)
Set the service Id.
unsigned int GetServiceId () const
Access to the service Id.
unsigned int GetPeerPid () const
bool ReceivedSyncLinkMsg ()
test if the Socket has received the link message
bool WaitSyncLinkMsg (unsigned int TimeToWait=250)
wait for a synclink message
bool SyncLinkMsgSent () const
test if the Socket has sent the link message
int GetMaxMessageSizeForTCP () const
size max for message on TCP
void SetMaxMessageSizeForTCP (int max)
size max for message on TCP Define the size max accepted for exchange on TCP (by default the value is 1<<16)
bool operator== (unsigned int peer_id) const
Compare the peer id.
bool SetTcpNoDelay (bool Set=true)
Set the undelying socket in non buffering mode if possible.
Naming connecting points
void SetName (const SimpleString NewName)
const SimpleString GetName ()
Protected Member Functions
virtual bool AcceptConnection (MsgSocket *s)
Accept new TCP connection.
virtual UdpConnection * AcceptConnection (const UdpConnection &udp_connect, bool msg_empty)
Accept new UDP connection.
Protected Attributes
MutexedSimpleList
< MsgSocketCallbackObject * > CallbackObjects
MsgSocketCallBackData callbackData
Mutex mutex
Callback_SyncLink callbackSyncLinkFct
Detailed Description
Socket with an implementation of Basic Interconnection Protocol to exchange message.
The 'size' bytes of the message are between : BIP\1.0 pid(8 bytes) mid(8 bytes) size(8 bytes)\r\n and \r\n When a new message arrives, the callback function 'callbackReceive' is called with the object 'callbackData' which contains the data.
Author:
Sebastien Pesnel
Dominique Vaufreydaz
Definition at line 122 of file MsgSocket.h.
Member Enumeration Documentation
enum Omiscid::MsgSocket::MsgSocketKind
Kind of use of a MsgSocket object.
Enumerator:
TCP_CLIENT_KIND for TCP connection : client side
TCP_SERVER_KIND for TCP connection : server side
UDP_EXCHANGE_KIND for UDP connection
Definition at line 144 of file MsgSocket.h.
    {
      NONE_KIND = -1,
      TCP_CLIENT_KIND = 0,
      TCP_SERVER_KIND,
      UDP_EXCHANGE_KIND
    };
Constructor & Destructor Documentation
MsgSocket::MsgSocket (Socket * s)
Constructor.
Create an object MsgSocket built on the Socket s. Used in TcpConnection to manage a new connection.
Parameters:
s Socket creates for the new tcp connection. (example : Socket returned by Accept method)
Definition at line 84 of file MsgSocket.cpp.
References SetMaxMessageSizeForTCP().
                              :
#ifdef DEBUG_THREAD
    Thread( "MsgSocket" ),
#else
    Thread(),
#endif
callbackSyncLinkFct(NULL),
socket(s),
bufferSize(TCP_BUFFER_SIZE),
buffer(NULL),
occupiedSize(0),
connected(true),
start_tag(NULL),
buffer_udp_send(NULL),
kind(TCP_CLIENT_KIND),
SendBuffer(NULL),
service_id(0),
message_id(0),
peer_pid(0),
receivedSyncLinkMsg(false),
sendSyncLinkMsg(false)
{
    buffer = new OMISCID_TLM unsigned char[bufferSize+1];                       // +1 for '\0'
    SendBuffer = new OMISCID_TLM unsigned char[TCP_BUFFER_SIZE];        // +1 for '\0'
    start_tag = new OMISCID_TLM char[tag_size+1];
    SetMaxMessageSizeForTCP(TCP_BUFFER_SIZE-1);
}
MsgSocket::MsgSocket (Socket::SocketKind type)
Constructor.
Create an MsgSocket for TCP or UDP communication.
Parameters:
type gives the kind of socket :
Socket::TCP for TCP connection,
Socket::UDP for UDP connection.
Definition at line 113 of file MsgSocket.cpp.
References SetMaxMessageSizeForTCP().
                                          :
#ifdef DEBUG_THREAD
    Thread( "MsgSocket" ),
#else
    Thread(),
#endif
callbackSyncLinkFct(NULL),
socket(NULL),
bufferSize(0),
buffer(NULL),
occupiedSize(0),
connected(false),
start_tag(NULL),
buffer_udp_send(NULL),
kind(NONE_KIND),
SendBuffer(NULL),
service_id(0),
message_id(0),
peer_pid(0),
receivedSyncLinkMsg(false),
sendSyncLinkMsg(false)
{
    socket = new OMISCID_TLM Socket(type);
    SetMaxMessageSizeForTCP(TCP_BUFFER_SIZE-1);
}
Member Function Documentation
void MsgSocket::InitForTcpClient (const SimpleString addr, int port)
Initialization for TCP Client.
Connection to a TCP server
Parameters:
addr [in] host where find the server
port [in] port where listen the server
Definition at line 364 of file MsgSocket.cpp.
References Omiscid::Socket::Connect(), and TCP_CLIENT_KIND.
Referenced by Omiscid::TcpClient::ConnectToServer().
{
    socket->Connect(addr, port);
    bufferSize = TCP_BUFFER_SIZE;
    buffer = new OMISCID_TLM unsigned char[bufferSize+1];       // + 1 for ending '\0'
    if ( buffer == NULL )
    {
        throw MsgSocketException( "Not enougth memory" );
    }
    SendBuffer = new OMISCID_TLM unsigned char[TCP_BUFFER_SIZE+1];      // + 1 for ending '\0'
    if ( SendBuffer == NULL )
    {
        throw MsgSocketException( "Not enougth memory" );
    }
    start_tag = new OMISCID_TLM char[tag_size+1];
    if ( start_tag == NULL )
    {
        throw MsgSocketException( "Not enougth memory" );
    }
    kind = TCP_CLIENT_KIND;
    connected = true;
    occupiedSize = 0;
}
void MsgSocket::InitForTcpServer (int port)
Initialization for TCP Server.
Parameters:
port [in] port number where the server must listen (if null a free port is chosen)
Definition at line 388 of file MsgSocket.cpp.
References Omiscid::Socket::Bind(), Omiscid::SimpleString::EmptyString, Omiscid::Socket::Listen(), and TCP_SERVER_KIND.
Referenced by Omiscid::TcpServer::Create().
{
    socket->Bind(SimpleString::EmptyString, port);
    socket->Listen();
    kind = TCP_SERVER_KIND;
    connected = true;
    //   unsigned short port_nb = socket->GetPortNb();
    //   char hostname[256];
    //   socket->GetHostName(hostname, 256);
    //   printf("Server Connected on : %s:%d", hostname, (int)port_nb);
}
void MsgSocket::InitForUdpExchange (int port)
Initialization for UDP Exchange.
Parameters:
port [in] port where wait for connections
Definition at line 403 of file MsgSocket.cpp.
References Omiscid::Socket::Bind(), Omiscid::SimpleString::EmptyString, and UDP_EXCHANGE_KIND.
Referenced by Omiscid::UdpExchange::Create().
{
    socket->Bind(SimpleString::EmptyString, port);
    bufferSize = TCP_BUFFER_SIZE;
    buffer = new OMISCID_TLM unsigned char[bufferSize+1];               // +1 for '\0'
    buffer_udp_send = new OMISCID_TLM char[UDP_MAX_MSG_SIZE+1]; // +1 for '\0'
    kind = UDP_EXCHANGE_KIND;
    connected = true;
    occupiedSize = 0;
}
bool MsgSocket::AddCallbackObject (MsgSocketCallbackObject * CallbackObject)
define callback function called in receive
Parameters:
[in] a callback object to notify
Reimplemented in Omiscid::Connector, and Omiscid::TcpServer.
Definition at line 415 of file MsgSocket.cpp.
References CallbackObjects.
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::TcpServer::AddCallbackObject(), Omiscid::Connector::AddCallbackObject(), Omiscid::Connector::ConnectTo(), and Omiscid::ControlClient::ControlClient().
{
    // lock the list
    SmartLocker SL_CallbackObjects(CallbackObjects);
    // Is the Callback object already in the list ?
    for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
    {
        if ( CallbackObjects.GetCurrent() == CallbackObject )
        {
            // Could not add trice the same listener
            return false;
        }
    }
    // Add the listener
    CallbackObjects.Add( CallbackObject );
    return true;
}
bool MsgSocket::RemoveCallbackObject (MsgSocketCallbackObject * CallbackObject)
Remove the callback for message reception.
Parameters:
[in] a callback object to remove from notification list
Reimplemented in Omiscid::Connector, and Omiscid::TcpServer.
Definition at line 440 of file MsgSocket.cpp.
References CallbackObjects.
Referenced by Omiscid::TcpServer::RemoveCallbackObject(), and Omiscid::Connector::RemoveCallbackObject().
{
    // lock the list
    SmartLocker SL_CallbackObjects(CallbackObjects);
    // Is the Callback object already in the list ?
    for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
    {
        if ( CallbackObjects.GetCurrent() == CallbackObject )
        {
            // Found ! Remove it
            CallbackObjects.RemoveCurrent();
            // ok, we remove it
            return true;
        }
    }
    // We did not find it
    return false;
}
void MsgSocket::SetName (const SimpleString NewName)
Used to set names on MsgSocket
Reimplemented in Omiscid::Connector.
Definition at line 175 of file MsgSocket.cpp.
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::Connector::ConnectTo(), and Omiscid::Connector::SetName().
{
    Name = NewName;
}
const SimpleString MsgSocket::GetName ()
Used to set names on MsgSocket
Reimplemented in Omiscid::Connector, Omiscid::Service, and Omiscid::ServiceProxy.
Definition at line 180 of file MsgSocket.cpp.
References Omiscid::SimpleString::IsEmpty().
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::Connector::ConnectTo(), Omiscid::ControlClient::FindInOutput(), Omiscid::ControlClient::FindInput(), Omiscid::ControlClient::FindOutput(), Omiscid::ControlClient::FindVariable(), and Omiscid::Connector::GetName().
{
    if ( Name.IsEmpty() )
    {
        return DefaultMsgSocketName;
    }
    return Name;
}
void MsgSocket::SetCallbackSyncLink (Callback_SyncLink cr, void * user_data1 = NULL, void * user_data2 = NULL)
define callback function called in receive
Parameters:
cr the callback call on receive message
user_data1 pointer on data (will be found in the callback parameter)
user_data2 pointer on data (will be found in the callback parameter)
Definition at line 471 of file MsgSocket.cpp.
References Omiscid::Message::buffer, callbackSyncLinkFct, Omiscid::Message::len, Omiscid::Mutex::Lock(), Omiscid::MsgSocketCallBackData::Msg, mutex, Omiscid::Mutex::Unlock(), Omiscid::MsgSocketCallBackData::userData1, and Omiscid::MsgSocketCallBackData::userData2.
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::Connector::ConnectTo(), and Omiscid::Connector::Create().
{
    mutex.Lock();       // Add SL_ as comment in order to prevent false alarm in code checker on locks
    callbackSyncLinkFct = cr;
    callbackSyncLinkData.Msg.len = 0;
    callbackSyncLinkData.Msg.buffer = NULL;
    callbackSyncLinkData.userData1 = user_data1;
    callbackSyncLinkData.userData2 = user_data2;
    mutex.Unlock();     // Add SL_ as comment in order to prevent false alarm in code checker on locks
}
void FUNCTION_CALL_TYPE MsgSocket::Run () [virtual]
method call when the Thread is started
According to the kind of MsgSocket :
receive the message on UDP, on TCP,
accept the connection for TCP_SERVER
Implements Omiscid::Thread.
Definition at line 568 of file MsgSocket.cpp.
References AcceptConnection(), Omiscid::Thread::StopPending(), TCP_CLIENT_KIND, TCP_SERVER_KIND, and UDP_EXCHANGE_KIND.
{
    switch (kind)
    {
    case TCP_SERVER_KIND:
        while(connected && !StopPending())
        {
            //printf("MsgSocket::run : tcp_server loop\n");
            AcceptConnection();
        }
        break;
    case TCP_CLIENT_KIND:
        while(connected && !StopPending())
        {
            //printf("MsgSocket::run : tcp_client loop\n");
            Receive();
        }
        break;
    case UDP_EXCHANGE_KIND:
        while(connected && !StopPending())
        {
            ReceiveUdpExchange();
        }
        break;
    default:
        OmiscidError( "run : unknown type of connection\n");
        break;
    }
}
int MsgSocket::Send (int len, const char * buf)
Send a message (on TCP) by using the BIP protocol.
add tag around data in buf before sending them
   * BIP/1.0 pid mid size\r\n
   * ... data ...
   * /r/n
   *
Parameters:
len [in] number of byte to send
buf [in] buffer to send
Returns:
the number of byte send (byte of data + tag) (-1 if error occured)
Definition at line 911 of file MsgSocket.cpp.
References CallbackObjects, Omiscid::SimpleException::err, GetPeerPid(), Omiscid::SimpleString::GetStr(), Omiscid::SimpleException::msg, Omiscid::Socket::Send(), and Omiscid::SmartLocker::Unlock().
Referenced by Omiscid::ControlServer::ProcessAMessage(), Omiscid::TcpServer::SendToAllClients(), Omiscid::TcpServer::SendToClient(), and Omiscid::TcpClient::SendToServer().
{
    int TotalLen = 0;
    SmartLocker SL_protectSend(protectSend);
    try
    {
        if ( Sendlen > maxBIPMessageSize )
        {
            int HeaderSend      = 0;
            // int BodySend     = 0;
            int TailerSend      = 0;
            // int ResSend              = 0;
            // OmiscidTrace( "Message too big for one TCP frame (size=%d, sizemax=%d) sends many.\n", Sendlen, maxMessageSizeForTCP);
            TotalLen = PrepareBufferForBip( (char*)SendBuffer, NULL, Sendlen, true );
            if ( TotalLen == -1 )
            {
                SL_protectSend.Unlock();
                return -1;
            }
            // We complete the header
            WriteHeaderForBip( (char*)SendBuffer, service_id, message_id );
            // Increase the number for the next message
            message_id++;
            // Send header
            HeaderSend = socket->Send(TotalLen, (char*)SendBuffer);
            if ( HeaderSend != TotalLen )
            {
                return -1;
            }
            // Let's send data...
            TotalLen = socket->Send( Sendlen, (char*)(buf) );
            if ( TotalLen != Sendlen )
            {
                return -1;
            }
            TailerSend = socket->Send( tag_end_size, tag_end );
            if ( TailerSend != tag_end_size )
            {
                return -1;
            }
            return HeaderSend + TotalLen + TailerSend;
        }
        TotalLen = PrepareBufferForBip( (char*)SendBuffer, buf, Sendlen );
        if ( TotalLen == -1 )
        {
            return -1;
        }
        // We complete the header
        WriteHeaderForBip( (char*)SendBuffer, service_id, message_id );
        // Increase the number for the next message
        message_id++;
        // if ( (TotalLen = socket->Send(TotalLen, (char*)SendBuffer)) == -1)
        // {
        //      TotalLen = -1;
        //}
        TotalLen = socket->Send(TotalLen, (char*)SendBuffer);
#ifdef DEBUG
        if ( Debug & DBG_SEND )
        {
            SendBuffer[TotalLen] = '\0';
            fprintf( stderr, "MsgSocket::Send: %s (%d)\n", SendBuffer, TotalLen );
        }
#endif
        SL_protectSend.Unlock();
        return (TotalLen-tag_end_size-tag_size);
    }
    catch(SocketException& e)
    {
        OmiscidTrace( "SocketException: %s %d\n", e.msg.GetStr(), e.err);
        if ( connected )
        {
            // Send disconnected message
            SmartLocker SL_CallbackObjects(CallbackObjects);
            // Send info to all listener
            for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
            {
                try
                {
                    CallbackObjects.GetCurrent()->Disconnected(*this,GetPeerPid());
                }
                catch(SocketException&) {}      // Discard it...
            }
            connected = false;
        }
        return -1;
    }
}
int MsgSocket::SendPreparedBuffer (int len, char * buf)
Send a preformated BIP message (on TCP) by using the BIP protocol.
add tag at the bigning of buf and send it
   * BIP/1.0 pid mid size\r\n
   * ... data ...
   * /r/n
   *
Parameters:
len [in] number of byte to send
buf [in,out] buffer to modify and send
Returns:
the number of byte send (byte of data + tag) (-1 if error occured)
Definition at line 1129 of file MsgSocket.cpp.
References CallbackObjects, Omiscid::SimpleException::err, GetPeerPid(), Omiscid::SimpleString::GetStr(), Omiscid::SimpleException::msg, and Omiscid::Socket::Send().
Referenced by Omiscid::TcpServer::SendToAllClients().
{
    if(l_buffer == NULL)
    {
        OmiscidError( "SendPreparedBuffer : NULL mesg\n" );
        throw MsgSocketException("Message NULL for TCP");
    }
    if(len > maxMessageSizeForTCP)
    {
        OmiscidError( "Message too big for TCP (size=%d, sizemax=%d) so not sended.\n", len, maxMessageSizeForTCP);
        throw MsgSocketException("Message too big for TCP");
    }
    SmartLocker SL_protectSend(protectSend);
    try
    {
        // Here we've got a full buffer and we can (must) write our header at the in at the beginning !
        WriteHeaderForBip(l_buffer, service_id, message_id );
#ifdef DEBUG
        if ( Debug & DBG_SEND )
        {
            OmiscidTrace( "MsgSocket::SendPreparedBuffer %s\n", l_buffer );
        }
#endif
        message_id++;
        //socket->Send(strlen(start_tag), start_tag);
        int res;
        if((res = socket->Send(len, l_buffer)) != -1)
        {
            return res;
        }
        OmiscidTrace( "Erreur Send (-1)\n" );
        return -1;
    }
    catch(SocketException& e)
    {
        OmiscidTrace( "SocketException: %s %d\n", e.msg.GetStr(), e.err);
        if ( connected )
        {
            // Send disconnected message
            SmartLocker SL_CallbackObjects(CallbackObjects);
            // Send info to all listener
            for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
            {
                try
                {
                    CallbackObjects.GetCurrent()->Disconnected(*this, GetPeerPid());
                }
                catch(SocketException&) {} // Discard it
            }
            connected = false;
        }
        return -1;
    }
}
int MsgSocket::SendCuttedMsg (int * tab_len, const char ** tab_buf, int nb_buf)
Send a message in several part (on TCP) by using the BIP protocol.
The parts of the message are sent the one per one, the all message is put between BIP tag.
Parameters:
tab_len [in] array of buffer size : the size of each buffer
tab_buf [in] array of buffer : the buffers to send
nb_buf [in] the number of buffer to send : the number of buffer in the array
Returns:
the number of byte send (byte of data + tag) (-1 if error occured)
Definition at line 1013 of file MsgSocket.cpp.
References CallbackObjects, Omiscid::SimpleException::err, GetPeerPid(), Omiscid::SimpleString::GetStr(), Omiscid::SimpleException::msg, Omiscid::Socket::Send(), SOCKET_ERROR, and Omiscid::SmartLocker::Unlock().
Referenced by Omiscid::TcpServer::SendToAllClients(), and Omiscid::TcpServer::SendToClient().
{
    int i;
    int SendLen;
    int TotalLen;
    // Compute the len of all buffers
    for( SendLen = 0, i = 0; i < nb_buf; i ++ )
    {
        SendLen += tab_length[i];
    }
    SmartLocker SL_protectSend(protectSend);
    try
    {
        if ( SendLen > maxBIPMessageSize )
        {
            int HeaderSend      = 0;
            int BodySend        = 0;
            int TailerSend      = 0;
            // int ResSend              = 0;
            // OmiscidTrace( "Message too big for one TCP frame (size=%d, sizemax=%d) sends many.\n", SendLen, maxMessageSizeForTCP);
            // prepare buffer
            TotalLen = PrepareBufferForBip( (char*)SendBuffer, NULL, SendLen, true );
            if ( TotalLen == -1 )
            {
                return -1;
            }
            // We complete the header
            WriteHeaderForBip( (char*)SendBuffer, service_id, message_id );
            // Increase the number for the next message
            message_id++;
            // Send header
            HeaderSend = socket->Send(TotalLen, (char*)SendBuffer);
            if ( HeaderSend != TotalLen )
            {
                return -1;
            }
            // Send all parts of the message
            for( i = 0; i < nb_buf; i ++ )
            {
                TotalLen = socket->Send( tab_length[i], tab_buf[i] );
                if ( TotalLen == SOCKET_ERROR )
                {
                    return -1;
                }
                BodySend += TotalLen;
            }
            // Send end of the message
            TailerSend = socket->Send( tag_end_size, tag_end );
            if ( TailerSend == -1 )
            {
                return -1;
            }
            return HeaderSend + BodySend + TailerSend;
        }
        TotalLen = PrepareBufferForBipFromCuttedMsg( (char*)SendBuffer, tab_length, tab_buf, nb_buf);
        if ( TotalLen == -1 )
        {
            return -1;
        }
        // We complete the header
        WriteHeaderForBip( (char*)SendBuffer, service_id, message_id );
#ifdef DEBUG
        if ( Debug & DBG_SEND )
        {
            OmiscidTrace( "MsgSocket::SendPreparedBuffer %s\n", SendBuffer );
        }
#endif
        // Increase the number for the next message
        ++message_id;
        if ( (TotalLen = socket->Send(TotalLen, (char*)SendBuffer)) == -1)
        {
            TotalLen = -1;
        }
        return TotalLen;
    }
    catch(SocketException& e)
    {
        OmiscidTrace( "SocketException: %s %d\n", e.msg.GetStr(), e.err);
        if ( connected )
        {
            // Send disconnected message
            SmartLocker SL_CallbackObjects(CallbackObjects);
            // Send info to all listener
            for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
            {
                try
                {
                    CallbackObjects.GetCurrent()->Disconnected(*this, GetPeerPid());
                }
                catch(SocketException&) {} // Discard it
            }
            connected = false;
        }
        SL_protectSend.Unlock();
        return -1;
    }
}
int MsgSocket::SendTo (int len, const char * buf, UdpConnection * udp_dest)
Send a message (on UDP) by using BIP protocol
Parameters:
len [in] number of byte to send
buf [in] buffer to send
udp_dest [in] the destination for the message
Returns:
the number of byte send (-1 if error occured)
Reimplemented in Omiscid::UdpExchange.
Definition at line 1189 of file MsgSocket.cpp.
References Omiscid::UdpConnection::addr, CallbackObjects, Omiscid::SimpleException::err, GetPeerPid(), Omiscid::SimpleString::GetStr(), Omiscid::SimpleException::msg, and Omiscid::Socket::SendTo().
Referenced by Omiscid::UdpExchange::SendTo().
{
    //   OmiscidTrace( "in MsgSocket::SendTo\n");
    //   OmiscidTrace( "send to pid : %u\n", dest->pid);
    if(len > UDP_MAX_MSG_SIZE){
        OmiscidError( "Message too big for UDP size=%d,  sizemax=%d\n", len, UDP_MAX_MSG_SIZE);
        throw MsgSocketException("Message too big for UDP");
    }
    SmartLocker SL_protectSend(protectSend);
    if ( buffer_udp_send == NULL )
    {
        buffer_udp_send = new OMISCID_TLM char[UDP_MAX_MSG_SIZE+1];     // +1 for '\0'
        if ( buffer_udp_send == NULL )
        {
            return 0;
        }
    }
    try
    {
        struct sockaddr_in* destptr = &(dest->addr);
        unsigned int total = tag_size+len+tag_end_size;
        sprintf(buffer_udp_send, tag_str, service_id, message_id, len);
        ++message_id;
        sprintf((buffer_udp_send+total-tag_end_size), tag_end);
        memcpy(buffer_udp_send+tag_size, buf, len);
        int TotalLen = socket->SendTo(total, buffer_udp_send, destptr);
        return TotalLen;
        //        socket->SendTo(strlen(start_tag), start_tag, destptr);
        //        socket->SendTo(len, buf, destptr);
        //        socket->SendTo(tag_end_size, tag_end, destptr);
    }
    catch(SocketException& e)
    {
        OmiscidTrace( "SocketException: %s %d \n", e.msg.GetStr(), e.err);
        if ( connected )
        {
            // Send disconnected message
            SmartLocker SL_CallbackObjects(CallbackObjects);
            // Send info to all listener
            for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
            {
                try
                {
                    CallbackObjects.GetCurrent()->Disconnected(*this,GetPeerPid());
                }
                catch(SocketException&) {} // Discard it
            }
            connected = false;
        }
        return -1;
    }
}
Socket * MsgSocket::GetSocket () const
Access to the socket object.
Returns:
the Socket object used by this MsgSocket object
Definition at line 1459 of file MsgSocket.cpp.
Referenced by Omiscid::UdpExchange::Close(), Omiscid::TcpServer::Close(), and Omiscid::ControlServer::StartServer().
{
    return socket;
}
unsigned short MsgSocket::GetPortNb () const
Access to Port number.
Returns:
the port number where the socket listen
Definition at line 1444 of file MsgSocket.cpp.
References Omiscid::Socket::GetPortNb().
Referenced by Omiscid::TcpServer::GetTcpPort(), and Omiscid::UdpExchange::GetUdpPort().
{
    return socket->GetPortNb();
}
bool MsgSocket::IsConnected () const
Test if the MsgSocket is in usage.
Returns:
false if this object is no more useful (no more connected)
Definition at line 1464 of file MsgSocket.cpp.
Referenced by Omiscid::Connector::AcceptConnection(), Omiscid::TcpServer::AddCallbackObject(), Omiscid::ServiceProxy::AddRemoteVariableChangeListener(), Omiscid::Connector::ConnectTo(), Omiscid::TcpServer::DisconnectPeerId(), Omiscid::TcpServer::FindClientFromId(), Omiscid::TcpServer::GetListPeerId(), Omiscid::TcpServer::GetNbConnections(), Omiscid::ServiceProxy::GetVariableDescription(), Omiscid::ServiceProxy::GetVariableType(), Omiscid::ServiceProxy::GetVariableValue(), Omiscid::TcpServer::RemoveAllCallbackObjects(), Omiscid::TcpServer::RemoveCallbackObject(), Omiscid::ServiceProxy::RemoveRemoteVariableChangeListener(), Omiscid::TcpServer::SendToAllClients(), Omiscid::ServiceProxy::SetVariableValue(), and Omiscid::ServiceProxy::UpdateDescription().
{
    return connected;
}
void MsgSocket::Stop ()
Stop the MsgSocket.
stop the thread used for reception, or to accept connection and set the MsgSocket as disconnected
Definition at line 601 of file MsgSocket.cpp.
References CallbackObjects, GetPeerPid(), and Omiscid::Thread::StopThread().
Referenced by Omiscid::UdpExchange::Close(), Omiscid::Connector::~Connector(), Omiscid::ControlClient::~ControlClient(), and ~MsgSocket().
{
    if ( connected )
    {
        // Send disconnected message
        SmartLocker SL_CallbackObjects(CallbackObjects);
        // Send info to all listener
        for( CallbackObjects.First(); CallbackObjects.NotAtEnd(); CallbackObjects.Next() )
        {
            try
            {
                CallbackObjects.GetCurrent()->Disconnected(*this, GetPeerPid());
            }
            catch(SocketException&) {} // Discard it
        }
        connected = false;
    }
    Thread::StopThread(0);
}
void MsgSocket::SetServiceId (unsigned int pid)
Set the service Id.
Define the id used by the BIP protocol to identifies peer in message exchange
Reimplemented in Omiscid::Connector, Omiscid::TcpClient, Omiscid::TcpServer, and Omiscid::UdpExchange.
Definition at line 1469 of file MsgSocket.cpp.
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::UdpExchange::SetServiceId(), Omiscid::TcpServer::SetServiceId(), and Omiscid::TcpClient::SetServiceId().
{
    service_id = pid;
}
unsigned int MsgSocket::GetServiceId () const
Access to the service Id.
Returns:
the service id
Reimplemented in Omiscid::Connector, Omiscid::TcpClient, Omiscid::TcpServer, Omiscid::UdpExchange, and Omiscid::ControlServer.
Definition at line 1474 of file MsgSocket.cpp.
Referenced by Omiscid::UdpExchange::GetServiceId(), Omiscid::TcpServer::GetServiceId(), and Omiscid::TcpClient::GetServiceId().
{
    return service_id;
}
unsigned int MsgSocket::GetPeerPid () const
Returns:
the peer id : the service id of the other extremity of the socket
Definition at line 1479 of file MsgSocket.cpp.
Referenced by Omiscid::Connector::AcceptConnection(), Omiscid::Connector::ConnectTo(), Omiscid::TcpServer::DisconnectPeerId(), Omiscid::TcpServer::FindClientFromId(), Omiscid::TcpServer::GetListPeerId(), Omiscid::TcpClient::GetListPeerId(), Omiscid::Connector::GetListPeerId(), Omiscid::TcpClient::GetPeerId(), Omiscid::ClientConnection::GetPeerPid(), Send(), SendCuttedMsg(), SendPreparedBuffer(), SendTo(), Omiscid::Connector::SendToAll(), and Stop().
{
    return peer_pid;
}
bool MsgSocket::ReceivedSyncLinkMsg ()
test if the Socket has received the link message
An link message is exchanged when the socket are connected. The extremity can then exchange their id
Returns:
true if the Socket has received an empty message
Definition at line 1484 of file MsgSocket.cpp.
Referenced by WaitSyncLinkMsg().
{
    bool tmpb;
    SmartLocker SL_protectSend(protectSend);
    tmpb = receivedSyncLinkMsg;
    return tmpb;
}
bool MsgSocket::WaitSyncLinkMsg (unsigned int TimeToWait = 250)
wait for a synclink message
Parameters:
[in] TimeToWait the max time to wait in ms (default 250 ms)
Returns:
true if the Socket has received a SyncLink message before timeout
Definition at line 1499 of file MsgSocket.cpp.
References ReceivedSyncLinkMsg(), and Omiscid::Thread::Sleep().
Referenced by Omiscid::Connector::ConnectTo().
{
    ElapsedTime CountWaitedTime;
    while( connected == true )
    {
        if ( ReceivedSyncLinkMsg() )
        {
            return true;
        }
        if ( CountWaitedTime.Get() >= TimeToWait )
        {
            return false;
        }
        Thread::Sleep(10);
    }
    return false;
}
bool MsgSocket::SyncLinkMsgSent () const
test if the Socket has sent the link message
An link message is exchanged when the socket are connected. The extremity can then exchange their id
Returns:
true if the Socket has received an empty message
Definition at line 1517 of file MsgSocket.cpp.
{
    return sendSyncLinkMsg;
}
int MsgSocket::GetMaxMessageSizeForTCP () const
size max for message on TCP
Returns:
the size max accepted for exchange on TCP
Reimplemented in Omiscid::TcpClient.
Definition at line 1522 of file MsgSocket.cpp.
Referenced by Omiscid::TcpServer::AcceptConnection(), and Omiscid::TcpClient::GetMaxMessageSizeForTCP().
{
    return maxMessageSizeForTCP;
}
bool MsgSocket::operator== (unsigned int peer_id) const
Compare the peer id.
Parameters:
peer_id [in] peer id to compare
Returns:
true if the peer id for this socket has the value 'peer_id'
Definition at line 1543 of file MsgSocket.cpp.
{
    return peer_pid == peer_id;
}
bool MsgSocket::SetTcpNoDelay (bool Set = true)
Set the undelying socket in non buffering mode if possible.
Reimplemented in Omiscid::TcpServer.
Definition at line 1548 of file MsgSocket.cpp.
References Omiscid::Socket::SetTcpNoDelay().
Referenced by Omiscid::TcpServer::AcceptConnection(), and Omiscid::ControlClient::ControlClient().
{
    return socket->SetTcpNoDelay(Set);
}
bool MsgSocket::AcceptConnection (MsgSocket * s) [protected, virtual]
Accept new TCP connection.
method called by TCP or Connector server when it accepts new connection. (method called by AcceptConnection()) Default Implementation : Close the connection.
Parameters:
s object created with the new accepted TCP connection
Returns:
true if the connection is accepted
Reimplemented in Omiscid::TcpServer.
Definition at line 904 of file MsgSocket.cpp.
Referenced by Run().
{
    //std::cerr << "in MsgSocket::acceptConnection(MsgSocket*)\n";
    delete ms;
    return false;
}
UdpConnection * MsgSocket::AcceptConnection (const UdpConnection & udp_connect, bool msg_empty) [protected, virtual]
Accept new UDP connection.
Used for the kind UDP_EXCHANGE Enable to store new source that declare itself with an empty message, and return NULL if the message is not empty and the source not already known.
(to implement in child class) current implementation : display a message on error output, and return NULL.
Parameters:
udp_connect [in] information about the source of a message coming from UDP.
msg_empty [in] true if udp_connect is the source of an empty message
Returns:
NULL if refuse the message, else return an object linked to the same source
Reimplemented in Omiscid::Connector, and Omiscid::UdpExchange.
Definition at line 1290 of file MsgSocket.cpp.
{
    OmiscidTrace( "AcceptConnection UDP (2)\n");
    if(msg_empty)
    {
        OmiscidTrace( "[Empty Msg]\n");
    }
    OmiscidTrace( "\n");
    return NULL;
}
Member Data Documentation
MutexedSimpleList<MsgSocketCallbackObject*> Omiscid::MsgSocket::CallbackObjects [protected]
callback call when messages arrive
Definition at line 392 of file MsgSocket.h.
Referenced by Omiscid::TcpServer::AcceptConnection(), AddCallbackObject(), Omiscid::Connector::ConnectTo(), RemoveAllCallbackObjects(), RemoveCallbackObject(), Send(), SendCuttedMsg(), SendPreparedBuffer(), SendTo(), and Stop().
MsgSocketCallBackData Omiscid::MsgSocket::callbackData [protected]
structure given to the callback methods
Definition at line 393 of file MsgSocket.h.
Mutex Omiscid::MsgSocket::mutex [protected]
mutex to protect the callback access
Definition at line 395 of file MsgSocket.h.
Referenced by Omiscid::TcpServer::AcceptConnection(), and SetCallbackSyncLink().
Callback_SyncLink Omiscid::MsgSocket::callbackSyncLinkFct [protected]
callback call when SyncLink messages arrive
Definition at line 396 of file MsgSocket.h.
Referenced by Omiscid::TcpServer::AcceptConnection(), and SetCallbackSyncLink().
The documentation for this class was generated from the following files:
Com/Com/MsgSocket.h
Com/MsgSocket.cpp