OMiSCID(aka O3MiSCID): Omiscid::ControlServer Class Reference
Omiscid::ControlServer Class Reference
Declaration and Control of service.
#include <ServiceControl/ControlServer.h>
Public Member Functions
ControlServer (const SimpleString service_name="Control")
Constructor.
virtual ~ControlServer ()
Destructor.
bool SetServiceName (const SimpleString service_name)
Set the name of the service.
const SimpleString & GetServiceName ()
get the name of the service.
const SimpleString & GetRegisteredServiceName ()
Access to the name of the registered service.
bool StartServer ()
Launch a server for the control and Register the service.
void StartThreadProcessMsg ()
Message processing in a thread.
int ProcessMessages ()
Call XMLTreeParser::ProcessMessages();.
bool WaitForMessage (unsigned long timer=0)
Call XMLTreeParser::WaitForMessage();.
unsigned int GetServiceId () const
Access to the service id.
void DisplayServiceId () const
display on standard output the service id followed by a newline
void DisplayServiceGlobalShortDescription ()
display on standard output the service description
InOutputAttribute * AddInOutput (const SimpleString name, ComTools *com_tool, ConnectorKind kind_of_input)
Add an input or an output to export in description.
VariableAttribute * AddVariable (const SimpleString name)
Create a new variable to export.
InOutputAttribute * FindInOutput (const SimpleString name)
Retrieve an InOutputAttribute object with a particular name.
VariableAttribute * FindVariable (const SimpleString name)
Retrieve a VariableAttribute object with a particular name.
ControlServerStatus GetStatus () const
Access to the service status.
void SetStatus (ControlServerStatus state)
Change the value of status.
void SetClass (const SimpleString Class)
Set service class. The class can be used for search.
const SimpleString GetClass ()
Retrieve the service class.
Protected Member Functions
virtual void Connect (const SimpleString host, int port, bool tcp, InOutputAttribute *ioa)
Called when a request of connection is done.
void VariableChange (VariableAttribute *va, SimpleString NewValue, ControlServerStatus status)
Called when a request of variable modification is done.
void VariableChanged (VariableAttribute *ChangedVariable)
Called when a request of variable modification is done.
void ProcessAMessage (XMLMessage *msg)
Function called on each message.
bool LockOk (unsigned int peer)
Protected Attributes
int port
ControlServerStatus Status
IntVariableAttribute * lockIntVariable
StringVariableAttribute * NameVariable
StringVariableAttribute * OwnerVariable
StringVariableAttribute * ClassVariable
StringVariableAttribute * PeerIdVariable
SimpleList< InOutputAttribute * > listInOutput
SimpleList< VariableAttribute * > listVariable
RegisterOmiscidService * registerDnsSd
MutexedSimpleList
< ValueListener * > listValueListener
Detailed Description
Declaration and Control of service.
Use:
Create a ControlServer, with the name for the service registration
add Variable, input, output ...
register the service (StartServer)
Process the control message by using ProcessMessages or in a new thread by calling one time StartThreadProcessMsg
Author:
Sebastien Pesnel
Definition at line 86 of file ControlServer.h.
Constructor & Destructor Documentation
ControlServer::ControlServer (const SimpleString service_name = "Control")
Constructor.
Define a service ID for this service.
Parameters:
service_name the name for the service. It will be registered with this name.
Definition at line 82 of file ControlServer.cpp.
                                                           :
  port(0),
  serviceId(0),
  localConnectorId(0),
  serviceName(service_name),
  Status(STATUS_INIT),
  lockIntVariable((IntVariableAttribute*)NULL),
  NameVariable((StringVariableAttribute*)NULL),
  OwnerVariable((StringVariableAttribute*)NULL),
  ClassVariable((StringVariableAttribute*)NULL),
  PeerIdVariable((StringVariableAttribute*)NULL),
  listInOutput(),
  listVariable(),
  registerDnsSd((RegisterOmiscidService*)NULL),
  listValueListener(),
  ControlQueryValidator()
  // If we are in debug mode, check also outgoing answer
#ifdef DEBUG
  , ControlAnswerValidator()
#endif
{
    InitInstance();
}
Member Function Documentation
bool ControlServer::SetServiceName (const SimpleString service_name)
Set the name of the service.
If the service is already registered, it will not change the published data.
Parameters:
service_name [in] the name for the service registration
Definition at line 1004 of file ControlServer.cpp.
References Omiscid::RegisterService::IsRegistered(), and registerDnsSd.
{
    if ( registerDnsSd && registerDnsSd->IsRegistered() )
    {
        return false;
    }
    serviceName = service_name;
    return true;
}
const SimpleString & ControlServer::GetServiceName ()
get the name of the service.
Returns:
the service name
Definition at line 1042 of file ControlServer.cpp.
{
    return serviceName;
}
const SimpleString & ControlServer::GetRegisteredServiceName ()
Access to the name of the registered service.
Available after server starts.
Returns:
the service name registered
Definition at line 1047 of file ControlServer.cpp.
References Omiscid::SimpleString::EmptyString, registerDnsSd, and Omiscid::DnsSdService::RegisteredName.
{
    if ( registerDnsSd )
    {
        return registerDnsSd->RegisteredName;
    }
    else
    {
        return SimpleString::EmptyString;
    }
}
bool ControlServer::StartServer ()
Launch a server for the control and Register the service.
Launch a Tcp Server on a free port. Register the service (DNS-SD)
Returns:
true if the tcp server is correctly launched and the service registered
Definition at line 173 of file ControlServer.cpp.
References Omiscid::TcpServer::Create(), Omiscid::SimpleException::Display(), Omiscid::ComTools::GeneratePeerId(), Omiscid::Socket::GetPortNb(), GetServiceId(), Omiscid::MsgSocket::GetSocket(), GetStatus(), Omiscid::SimpleString::GetStr(), Omiscid::StringVariableAttribute::GetValue(), Omiscid::RegisterService::IsRegistered(), listInOutput, listVariable, NameVariable, OwnerVariable, PeerIdVariable, port, Omiscid::DnsSdService::Properties, Omiscid::RegisterService::Register(), registerDnsSd, Omiscid::DnsSdService::RegisteredName, Omiscid::TcpServer::SetServiceId(), SetStatus(), Omiscid::StringVariableAttribute::SetValue(), and StartThreadProcessMsg().
Referenced by Omiscid::Service::Start().
{
    if ( GetStatus() != STATUS_INIT )
    {
        // server already launch
        return false;
    }
    try
    {
        Create(0);
        port = GetSocket()->GetPortNb();
        // GetSocket()->GetHostName((char*)hostname, HOST_NAME_MAX_SIZE);
        for(unsigned int NbMaxRegisterTries = 10; NbMaxRegisterTries > 0; NbMaxRegisterTries--)
        {
            // Add peerID value
            TemporaryMemoryBuffer tmp_peerid(30);       // To prevent buffer overflow
            snprintf( tmp_peerid, 30, "%8.8x", GetServiceId());
            PeerIdVariable->SetValue( (char*)tmp_peerid );
            // Create an object to register the service
            registerDnsSd = new OMISCID_TLM RegisterOmiscidService( PeerIdVariable->GetValue(), "local.", (unsigned short)port, false);
            // Add Constant variable
            // The desctiption if full by default
            bool TxtRecordIsFull = false;
            registerDnsSd->Properties["desc"] = "full"; // Will be set to part if not full
            // Add owner value
            OwnerVariable->SetValue( GetLoggedUser() );
            NameVariable->SetValue( serviceName );
            // To prevent adding variable , inputs from another thread...
            SetStatus(STATUS_RUNNING);
            SimpleString tmp;
            // Add Constant variable
            for( listVariable.First(); TxtRecordIsFull != true && listVariable.NotAtEnd(); listVariable.Next() )
            {
                if ( listVariable.GetCurrent()->GetAccess() == ConstantAccess )
                {
                    // Compute len of the key
                    unsigned int TotalLenOfRecord;
                    TotalLenOfRecord  = listVariable.GetCurrent()->GetName().GetLength();       // Len of name
                    TotalLenOfRecord += 1;      // '='
                    TotalLenOfRecord += listVariable.GetCurrent()->GetValue().GetLength();      // len of value
                    if ( TotalLenOfRecord > 252 )
                    {
                        // We could not set the full data in the variable
                        // We just say it is a variable
                        tmp = "c";
                    }
                    else
                    {
                        tmp = "c/";
                        tmp += listVariable.GetCurrent()->GetValue();
                    }
                    registerDnsSd->Properties[listVariable.GetCurrent()->GetName()] = tmp;
                    TxtRecordIsFull = registerDnsSd->Properties.TxtRecordIsFull();
                    if ( TxtRecordIsFull )
                    {
                        // undefine the last add
                        registerDnsSd->Properties.Undefine( listVariable.GetCurrent()->GetName() );
                        // Say the definition is partial
                        registerDnsSd->Properties["desc"] = "part";
                    }
                }
            }
            // Add inputs/outputs/inoutputs
            if ( TxtRecordIsFull != true )
            {
                // Add Constant variable
                for( listInOutput.First(); TxtRecordIsFull != true && listInOutput.NotAtEnd(); listInOutput.Next() )
                {
                    ConnectorKind KindOfInOutput = listInOutput.GetCurrent()->GetType();
                    switch( KindOfInOutput )
                    {
                        case AnInput:
                            tmp = "i/";
                            break;
                        case AnOutput:
                            tmp = "o/";
                            break;
                        case AnInOutput:
                            tmp = "d/";
                            break;
                            // to make gcc happy
                            // If by error, we do not have the type, we do not publish it...
                        case UnkownConnectorKind:
                            continue;
                    }
                    tmp += listInOutput.GetCurrent()->GetTcpPort();
                    registerDnsSd->Properties[listInOutput.GetCurrent()->GetName()] = tmp;
                    TxtRecordIsFull = registerDnsSd->Properties.TxtRecordIsFull();
                    if ( TxtRecordIsFull )
                    {
                        // undefine the last add
                        registerDnsSd->Properties.Undefine( listInOutput.GetCurrent()->GetName() );
                        // Say the definition is partial
                        registerDnsSd->Properties["desc"] = "part";
                    }
                }
            }
            // Add non constant variable
            if ( TxtRecordIsFull != true )
            {
                // Add Constant variable
                for( listVariable.First(); TxtRecordIsFull != true && listVariable.NotAtEnd(); listVariable.Next() )
                {
                    VariableAccessType VarAccess = listVariable.GetCurrent()->GetAccess();
                    switch( VarAccess )
                    {
                        case ReadAccess:
                            tmp = "r";
                            break;
                        case ReadWriteAccess:
                            tmp = "w";
                            break;
                        case ConstantAccess:
                            // already done
                            continue;
                    }
                    registerDnsSd->Properties[listVariable.GetCurrent()->GetName()] = tmp;
                    TxtRecordIsFull = registerDnsSd->Properties.TxtRecordIsFull();
                    if ( TxtRecordIsFull )
                    {
                        // undefine the last add
                        registerDnsSd->Properties.Undefine( listVariable.GetCurrent()->GetName() );
                        // Say the definition is partial
                        registerDnsSd->Properties["desc"] = "part";
                    }
                }
            }
            // Remove Name variable from TxtRecord list, when using DNS-SD, we've got the "id" as service name
            registerDnsSd->Properties.Undefine( CommonServiceValues::NameForPeerIdString );
            // Actually register
            registerDnsSd->Register(false);
            // Check if everything goes fine
            if( registerDnsSd->IsRegistered() )
            {
                OmiscidTrace( "registered '%s' as '%s' ok\n", serviceName.GetStr(), registerDnsSd->RegisteredName.GetStr() );
                // serviceName = registerDnsSd->RegisteredName;
                // NameVariable->SetValue( serviceName );
                StartThreadProcessMsg();
                return true;
            }
            // Ok, destroy the register Object
            delete registerDnsSd;
            registerDnsSd = NULL;
            OmiscidError( "Changing PeerId from %8.8x ", serviceId );
            // Generate a new PeerId and set it !
            serviceId = ComTools::GeneratePeerId();
            TcpServer::SetServiceId( serviceId );
            OmiscidError( "to %8.8x because of name conflict.\n", serviceId );
        }
        // Something was wrong...
        OmiscidError( "Registration of '%s' failed\n", serviceName.GetStr() );
    }
    catch(SocketException e)
    {
        e.Display();
    }
    if ( registerDnsSd )
    {
        // Delete DNS-SD object
        delete registerDnsSd;
        registerDnsSd = NULL;
    }
    // An error occurred, back to init mode
    SetStatus( STATUS_INIT );
    return false;
}
void ControlServer::StartThreadProcessMsg ()
Message processing in a thread.
run a thread where queries to the server are processed. In this case, the user don't need to use the methods ProcessMessages() and WaitForMessage(). call ProcessMessages when messages wait.
See also:
ProcessMessages, WaitForMessage
Definition at line 370 of file ControlServer.cpp.
References Omiscid::Thread::StartThread().
Referenced by StartServer().
{
    XMLTreeParser::StartThread();
}
int ControlServer::ProcessMessages ()
Call XMLTreeParser::ProcessMessages();.
See also:
XMLTreeParser::ProcessMessages();
Reimplemented from Omiscid::XMLTreeParser.
Definition at line 1015 of file ControlServer.cpp.
References Omiscid::XMLTreeParser::ProcessMessages().
{
    return XMLTreeParser::ProcessMessages();
}
bool ControlServer::WaitForMessage (unsigned long timer = 0)
Call XMLTreeParser::WaitForMessage();.
See also:
XMLTreeParser::WaitForMessage();
Reimplemented from Omiscid::XMLTreeParser.
Definition at line 1020 of file ControlServer.cpp.
References Omiscid::XMLTreeParser::WaitForMessage().
{
    return XMLTreeParser::WaitForMessage(timer);
}
unsigned int ControlServer::GetServiceId () const [virtual]
Access to the service id.
Returns:
the service id.
Reimplemented from Omiscid::TcpServer.
Definition at line 994 of file ControlServer.cpp.
Referenced by AddInOutput(), Omiscid::Service::FindService(), Omiscid::Service::FindServices(), and StartServer().
{
    return serviceId;
}
InOutputAttribute * ControlServer::AddInOutput (const SimpleString name, ComTools * com_tool, ConnectorKind kind_of_input)
Add an input or an output to export in description.
Create a new Input or Output and give the pointer on this object to change or add some data.
Parameters:
name [in] name of input or output to add.
com_tool object used for the communication (TcpServer, TcpClient, Connector)
kind_of_input [in] define if it is input or output or inoutput
Returns:
a new InOutputAttribute object (will be deleted by the controlServer)
Definition at line 818 of file ControlServer.cpp.
References FindInOutput(), FindVariable(), GetServiceId(), GetStatus(), Omiscid::SimpleString::IsEmpty(), listInOutput, and Omiscid::ComTools::SetServiceId().
Referenced by Omiscid::Service::AddConnector().
{
    if ( GetStatus() == STATUS_RUNNING || InOutputName.IsEmpty() )
    {
        return NULL;
    }
    // Look for a Varible of an Input with the same name
    if ( FindInOutput( InOutputName ) != NULL )
    {
        // Already exists
        OmiscidError( "A connector with the same name already exists.\n" );
        return NULL;
    }
    // Look for a Varible of an Input with the same name
    if ( FindVariable( InOutputName ) != NULL )
    {
        // Already exists
        OmiscidError( "A variable with the same name already exists. Could not add connector.\n" );
        return NULL;
    }
    // Add the connector
    unsigned int ConnectorId;
    InOutputAttribute* ioa = new OMISCID_TLM InOutputAttribute(InOutputName, com_tool, kind_of_input);
    if ( com_tool )
    {
        // Incr number for the Connector
        localConnectorId++;
        if ( (localConnectorId & ComTools::SERVICE_PEERID) != 0 )
        {
            fprintf( stderr, "Too many connector (>127). Unexpected features may appear\n." );
        }
        ConnectorId = localConnectorId & ComTools::CONNECTOR_ID;
        com_tool->SetServiceId( GetServiceId() | ConnectorId );
    }
    listInOutput.Add(ioa);
    return ioa;
}
VariableAttribute * ControlServer::AddVariable (const SimpleString name)
Create a new variable to export.
Parameters:
name [in] the name of the variable
Returns:
a new VariableAttribute object. It will be deleted by the controlServer. use this pointer to complete the data about this variable.
Definition at line 786 of file ControlServer.cpp.
References Omiscid::VariableAttribute::AddListener(), FindInOutput(), FindVariable(), GetStatus(), Omiscid::SimpleString::IsEmpty(), and listVariable.
Referenced by Omiscid::Service::AddVariable().
{
    if ( GetStatus() == STATUS_RUNNING || VarName.IsEmpty() )
    {
        return NULL;
    }
    // Look for a Varible of an Input with the same name
    if ( FindVariable( VarName ) != NULL )
    {
        // Already exists
        OmiscidError( "A variable with the same name already exists.\n" );
        return NULL;
    }
    // Look for a Varible of an Input with the same name
    if ( FindInOutput( VarName ) != NULL )
    {
        // Already exists
        OmiscidError( "A connector with the same name already exists. Could not add variable.\n" );
        return NULL;
    }
    VariableAttribute* va = new OMISCID_TLM VariableAttribute(VarName);
    listVariable.Add(va);
    // I am the first listener
    va->AddListener( this );
    return va;
}
InOutputAttribute * ControlServer::FindInOutput (const SimpleString name)
Retrieve an InOutputAttribute object with a particular name.
Find an InOutputAttribute object declared with AddInOutput, and that has the name 'name'.
Parameters:
name [in] name of the input or output
Returns:
the InOutputAttribute object or NULL if not found
Definition at line 388 of file ControlServer.cpp.
References Omiscid::SimpleString::GetStr(), and listInOutput.
Referenced by Omiscid::Service::AddConnector(), Omiscid::Service::AddConnectorListener(), AddInOutput(), AddVariable(), Omiscid::Service::CloseAllConnections(), Omiscid::Service::CloseConnection(), Omiscid::Service::ConnectTo(), Omiscid::Service::GetConnectorClientCount(), Omiscid::Service::RemoveAllConnectorListeners(), Omiscid::Service::RemoveConnectorListener(), Omiscid::Service::SendToAllClients(), and Omiscid::Service::SendToOneClient().
{
    for(listInOutput.First(); listInOutput.NotAtEnd(); listInOutput.Next())
    {
        if ( strcasecmp(InOutputName.GetStr(), listInOutput.GetCurrent()->GetName().GetStr() ) == 0 )
            return listInOutput.GetCurrent();
    }
    return NULL;
}
VariableAttribute * ControlServer::FindVariable (const SimpleString name)
Retrieve a VariableAttribute object with a particular name.
retrieve a VariableAttribute object declared with AddVariable, and that has the name 'name'.
Parameters:
name [in] name of the variable
Returns:
the VariableAttribute object or NULL if not found
Definition at line 398 of file ControlServer.cpp.
References Omiscid::SimpleString::GetStr(), and listVariable.
Referenced by AddInOutput(), Omiscid::Service::AddLocalVariableListener(), Omiscid::Service::AddVariable(), AddVariable(), Omiscid::Service::GetVariableAccessTypeType(), Omiscid::Service::GetVariableDescription(), Omiscid::Service::GetVariableValue(), Omiscid::Service::RemoveLocalVariableListener(), Omiscid::Service::SetVariableDescription(), and Omiscid::Service::SetVariableValue().
{
    for(listVariable.First(); listVariable.NotAtEnd(); listVariable.Next())
    {
        if( strcasecmp( VarName.GetStr(), listVariable.GetCurrent()->GetName().GetStr() ) == 0 )
            return listVariable.GetCurrent();
    }
    return NULL;
}
ControlServerStatus ControlServer::GetStatus () const
Access to the service status.
Returns:
the value of status
Definition at line 1032 of file ControlServer.cpp.
References Status.
Referenced by Omiscid::Service::AddConnector(), AddInOutput(), AddVariable(), and StartServer().
{
    return (ControlServerStatus)Status;
}
void ControlServer::SetStatus (ControlServerStatus state)
Change the value of status.
Parameters:
state [in] the new value.
Definition at line 1037 of file ControlServer.cpp.
References Status.
Referenced by StartServer().
{
    Status = s;
}
void ControlServer::SetClass (const SimpleString Class)
Set service class. The class can be used for search.
Parameters:
[in] Class of the service
Definition at line 1063 of file ControlServer.cpp.
References ClassVariable, and Omiscid::StringVariableAttribute::SetValue().
{
    ClassVariable->SetValue( Class );
}
const SimpleString ControlServer::GetClass ()
Retrieve the service class.
Returns:
Class of the service
Definition at line 1072 of file ControlServer.cpp.
References ClassVariable, and Omiscid::StringVariableAttribute::GetValue().
{
    return ClassVariable->GetValue();
}
void ControlServer::Connect (const SimpleString host, int port, bool tcp, InOutputAttribute * ioa) [protected, virtual]
Called when a request of connection is done.
A VOIR, A REVOIR, ... Must be be reimplemented by the user. The Input or Output is requested to connect to a port on a given host.
Parameters:
host [in] host where do connection.
port [in] port to connect.
Definition at line 753 of file ControlServer.cpp.
References Omiscid::Attribute::GetName(), and Omiscid::SimpleString::GetStr().
{
#ifdef DEBUG
    fprintf(stderr, "in ControlServer::Connect (%s:%d", host.GetStr(), port);
    if(tcp) fprintf(stderr, " [TCP] "); else fprintf(stderr, " [UDP] ");
    fprintf(stderr, "%s\n", ioa->GetName().GetStr());
#endif
}
void ControlServer::VariableChange (VariableAttribute * va, SimpleString NewValue, ControlServerStatus status) [protected]
Called when a request of variable modification is done.
Must be be reimplemented by the user. The Input or Output is requested to connect to a port on a given host.
Parameters:
length [in] number of byte in the buffer
buffer [in] contain the new value on 'length' byte.
status [in] current status of the service. Useful for the variable that can be modified only during initialization.
va [in] contains the data about the variable.
Definition at line 762 of file ControlServer.cpp.
References Omiscid::Attribute::GetName(), Omiscid::SimpleString::GetStr(), and Omiscid::VariableAttribute::SetValue().
{
    OmiscidTrace( "ControlServer::VariableChange '%s' New Value='%s'\n", va->GetName().GetStr(), NewValue.GetStr());
    // Do what we must do...
    // va will call back me to know if I agree to change it's value
    // va will also notify me that the value has changed (if change have been validated)
    va->SetValue( NewValue );
}
void ControlServer::VariableChanged (VariableAttribute * ChangedVariable) [protected]
Called when a request of variable modification is done.
can be be reimplemented by the user. The Input or Output is requested to connect to a port on a given host.
Parameters:
length [in] number of byte in the buffer
buffer [in] contain the new value on 'length' byte.
status [in] current status of the service. Useful for the variable that can be modified only during initialization.
va [in] contains the data about the variable.
Definition at line 778 of file ControlServer.cpp.
References Status.
{
    if ( Status == STATUS_RUNNING )
    {
        NotifyValueChanged( ChangedVariable );
    }
}
void ControlServer::ProcessAMessage (XMLMessage * msg) [protected, virtual]
Function called on each message.
(reimplemented from XMLTreeParser)
Parameters:
msg [in] the message to process
Reimplemented from Omiscid::XMLTreeParser.
Definition at line 408 of file ControlServer.cpp.
References Omiscid::XMLMessage::doc, Omiscid::SimpleException::err, Omiscid::XMLMessage::FindAttribute(), Omiscid::TcpServer::FindClientFromId(), Omiscid::XMLMessage::GetRootNode(), Omiscid::SimpleString::GetStr(), Omiscid::InOutputAttribute::inoutput_str, Omiscid::InOutputAttribute::input_str, Omiscid::TcpServer::listConnections, Omiscid::SimpleException::msg, Omiscid::InOutputAttribute::output_str, Omiscid::XMLMessage::pid, Omiscid::MsgSocket::Send(), and Omiscid::VariableAttribute::VariableStr.
{
    // OmiscidTrace( "in ControlServer::ProcessAMessage\n");
    // OmiscidTrace( "from pid = %u \n",msg->pid);
    if ( msg == NULL )
    {
        // Nothing to do
        return;
    }
    xmlNodePtr node = msg->GetRootNode();
    // if( strcmp((const char*)node->name, "controlQuery") == 0 )
    if ( ControlQueryValidator.ValidateDoc(msg->doc) )
    {
        SimpleString id;
        xmlAttrPtr attr = XMLMessage::FindAttribute("id", node);
        if(attr)
        { id = SimpleString((const char*)attr->children->content);}
        bool ReplyAnAnswer = true;      // default
        SimpleString str;
        if(node->children == NULL)
        {
            //global description
            GenerateGlobalShortDescription(str);
        }
        else
        {
            // more precise request
            xmlNodePtr cur_node = node->children;
            for(; cur_node; cur_node = cur_node->next)
            {
                SimpleString name = (const char*)(cur_node->name);
                //std::cerr << "tag name="<<(*it)->name <<"\n";
                if( name == InOutputAttribute::input_str.GetStr() ||
                    name == InOutputAttribute::output_str.GetStr() ||
                    name == InOutputAttribute::inoutput_str.GetStr() )
                {
                    // OmiscidTrace( " process io : %s \n", (*it)->name.GetStr());
                    ProcessInOutputQuery(cur_node, str);
                }
                else if( name == VariableAttribute::VariableStr )
                {
                    ProcessVariableQuery(cur_node, msg->pid,  str);
                }
                else if( name == "connect" )
                {
                    ProcessConnectQuery(cur_node, str);
                }
                else if( name == "subscribe" )
                {
                    ProcessSubscribeQuery(cur_node, msg->pid, true, str);
                }
                else if( name == "unsubscribe" )
                {
                    ReplyAnAnswer = false;
                    ProcessSubscribeQuery(cur_node, msg->pid, false, str);
                }
                else if( name == "lock" )
                {
                    ProcessLockQuery(cur_node, msg->pid, true, str);
                }
                else if( name == "unlock" )
                {
                    ProcessLockQuery(cur_node, msg->pid, false, str);
                }
                else if( name == "fullDescription" )
                {
                    ProcessFullDescriptionQuery(cur_node, str);
                }
                else
                {
                    // Should not appear
                    OmiscidError( "unknown tag : %s\n", name.GetStr() );
                }
            }
            // OmiscidError( "Send : %s \n", str.GetStr());
        }
        if ( ReplyAnAnswer == true )
        {
            str = "<controlAnswer id=\""+id+"\">"
                + str
                + "</controlAnswer>";
    #ifdef DEBUG
            if ( ControlAnswerValidator.ValidateDoc( str ) == false )
            {
                OmiscidError( "ControlServer::ProcessAMessage: bad ControlAnswer sent.\n" );
            }
    #endif
            SmartLocker SL_TcpServer_listConnections(TcpServer::listConnections);
            MsgSocket* ms = FindClientFromId( msg->pid );
            if( ms != (MsgSocket*)NULL )
            {
                try
                {
                    ms->Send((int)str.GetLength(), str.GetStr());
                }
                catch( SocketException& e )
                {
                    OmiscidError( "Error when responding to a client request : %s (%d)\n", e.msg.GetStr(), e.err );
                }
            }
        }
    }
    else
    {
        OmiscidError( "waited : controlQuery, received='%s'\n", node->name);
    }
}
bool ControlServer::LockOk (unsigned int peer) [protected]
Return if a peer can change the variables according to the lock value
Definition at line 739 of file ControlServer.cpp.
References Omiscid::IntVariableAttribute::GetValue(), and lockIntVariable.
{
    RefreshLock();
    return (lockIntVariable->GetValue() == 0) || (((unsigned int)lockIntVariable->GetValue()) == peer);
}
Member Data Documentation
int Omiscid::ControlServer::port [protected]
number of the control port
Definition at line 333 of file ControlServer.h.
Referenced by StartServer().
ControlServerStatus Omiscid::ControlServer::Status [protected]
default variable structure for the variable status combined with the status value
Definition at line 344 of file ControlServer.h.
Referenced by GetStatus(), SetStatus(), and VariableChanged().
IntVariableAttribute* Omiscid::ControlServer::lockIntVariable [protected]
variable structure for integer to manage the lock state
Definition at line 346 of file ControlServer.h.
Referenced by LockOk(), and ~ControlServer().
StringVariableAttribute* Omiscid::ControlServer::NameVariable [protected]
variable structure for exporting the name of this service
Definition at line 347 of file ControlServer.h.
Referenced by StartServer(), and ~ControlServer().
StringVariableAttribute* Omiscid::ControlServer::OwnerVariable [protected]
variable structure for exporting the name of this service
Definition at line 348 of file ControlServer.h.
Referenced by StartServer(), and ~ControlServer().
StringVariableAttribute* Omiscid::ControlServer::ClassVariable [protected]
variable structure for exporting the name of this service
Definition at line 349 of file ControlServer.h.
Referenced by GetClass(), SetClass(), and ~ControlServer().
StringVariableAttribute* Omiscid::ControlServer::PeerIdVariable [protected]
variable structure for integer to export the peerid
Definition at line 350 of file ControlServer.h.
Referenced by Omiscid::Service::GetPeerId(), Omiscid::Service::GetPeerIdAsString(), StartServer(), and ~ControlServer().
SimpleList<InOutputAttribute*> Omiscid::ControlServer::listInOutput [protected]
list of inputs and outputs
Definition at line 352 of file ControlServer.h.
Referenced by AddInOutput(), Omiscid::Service::CloseAllConnections(), FindInOutput(), Omiscid::Service::RemoveAllConnectorListeners(), StartServer(), ~ControlServer(), and Omiscid::Service::~Service().
SimpleList<VariableAttribute*> Omiscid::ControlServer::listVariable [protected]
list of variables
Definition at line 354 of file ControlServer.h.
Referenced by AddVariable(), FindVariable(), StartServer(), and ~ControlServer().
RegisterOmiscidService* Omiscid::ControlServer::registerDnsSd [protected]
Object for registering the service to DNS-SD
Definition at line 356 of file ControlServer.h.
Referenced by GetRegisteredServiceName(), SetServiceName(), StartServer(), and ~ControlServer().
MutexedSimpleList<ValueListener*> Omiscid::ControlServer::listValueListener [protected]
list of group variable - peer id intereted in variable modification
Definition at line 358 of file ControlServer.h.
Referenced by ~ControlServer().
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/ControlServer.h
ServiceControl/ControlServer.cpp