OMiSCID(aka O3MiSCID): Omiscid::TcpClient Class Reference
Omiscid::TcpClient Class Reference
Client using TCP communication.
#include <Com/TcpClient.h>
Public Member Functions
TcpClient ()
Constructor.
TcpClient (const SimpleString addr, int port)
Constructor.
void ConnectToServer (const SimpleString addr, int port)
Connect to Server.
int SendToServer (int len, const char *buffer)
Send a message to the server.
void SetServiceId (unsigned int pid)
Define the service Id.
unsigned int GetServiceId () const
Acces to the service id.
unsigned int GetPeerId () const
Access to the server id.
int GetListPeerId (SimpleList< unsigned int > &listId)
List of peer id.
int GetMaxMessageSizeForTCP () const
size max for message on TCP
void SetMaxMessageSizeForTCP (int max)
size max for message on TCP Define the size max accepted for exchange on TCP (by default the value is 1<<16)
virtual ComTools * Cast ()
Cast in ComTools.
Detailed Description
Client using TCP communication.
Author:
Sebastien Pesnel
Domnique Vaufreydaz
Definition at line 24 of file TcpClient.h.
Constructor & Destructor Documentation
TcpClient::TcpClient ()
Constructor.
Build a TCP Socket
Definition at line 5 of file TcpClient.cpp.
: MsgSocket(Socket::TCP)
{
}
TcpClient::TcpClient (const SimpleString addr, int port)
Constructor.
Build a TCP Socket. Call ConnectToServer with parameters addr, port.
Parameters:
addr [in] host address or name.
port [in] port where the server listen.
See also:
ConnectToServer
Definition at line 10 of file TcpClient.cpp.
References ConnectToServer().
 : MsgSocket(Socket::TCP)
{
  ConnectToServer(addr, port);
}
Member Function Documentation
void TcpClient::ConnectToServer (const SimpleString addr, int port)
Connect to Server.
Parameters:
addr [in] host address or name.
port [in] port where the server listen.
Exceptions:
SocketException if connection error.
Definition at line 21 of file TcpClient.cpp.
References Omiscid::MsgSocket::InitForTcpClient(), and Omiscid::Thread::StartThread().
Referenced by Omiscid::Connector::ConnectTo(), Omiscid::ControlClient::ConnectToCtrlServer(), and TcpClient().
{
  MsgSocket::InitForTcpClient(addr, port);
  MsgSocket::StartThread();
  MsgSocket::SendSyncLinkMsg();
}
int TcpClient::SendToServer (int len, const char * buffer)
Send a message to the server.
Send 'len' bytes in the buffer 'buffer' to the server.
Parameters:
len [in] number of bytes to send.
buffer [in] buffer with the len bytes to send. (reimplemented from Client)
Returns:
number of byte sent, (-1 if error)
Definition at line 29 of file TcpClient.cpp.
References Omiscid::MsgSocket::Send().
Referenced by Omiscid::Connector::SendToPeer().
{
  return MsgSocket::Send(len, buffer);
}
void TcpClient::SetServiceId (unsigned int pid) [virtual]
Define the service Id.
Define the service Id used in the header of each sent messages.
Parameters:
pid [in] the service id value.
Implements Omiscid::ComTools.
Definition at line 34 of file TcpClient.cpp.
References Omiscid::MsgSocket::SetServiceId().
Referenced by Omiscid::Connector::ConnectTo(), and Omiscid::ControlClient::ControlClient().
{
    // Check validity of a service Id
    if ( (pid & ComTools::CONNECTOR_ID) == 0 )
    {
        // pid = pid | 0xffffff01;
#ifdef DEBUG
//              fprintf(stderr, "Warning: ConnectorId could not be 0 for TcpClient. Value changes to 1 (PeerId = %8.8x)\n", pid);
#endif
    }
    MsgSocket::SetServiceId(pid);
}
unsigned int TcpClient::GetServiceId () const [virtual]
Acces to the service id.
Returns:
the service id
Implements Omiscid::ComTools.
Definition at line 52 of file TcpClient.cpp.
References Omiscid::MsgSocket::GetServiceId().
{
    return MsgSocket::GetServiceId();
}
unsigned int TcpClient::GetPeerId () const
Access to the server id.
Returns:
the id of the server.
Definition at line 57 of file TcpClient.cpp.
References Omiscid::MsgSocket::GetPeerPid().
{
    return MsgSocket::GetPeerPid();
}
int TcpClient::GetListPeerId (SimpleList< unsigned int > & listId) [virtual]
List of peer id.
if connected add to the list the server id
Parameters:
listId [in, out] listId where add the peer id
Returns:
0 or 1 if connected
Implements Omiscid::ComTools.
Definition at line 62 of file TcpClient.cpp.
References Omiscid::SimpleList< TYPE >::Add(), and Omiscid::MsgSocket::GetPeerPid().
{
  unsigned int pid = MsgSocket::GetPeerPid();
  if(pid != 0)
    {
      listId.Add(pid);
      return 1;
    }
  return 0;
}
int TcpClient::GetMaxMessageSizeForTCP () const
size max for message on TCP
Returns:
the size max accepted for exchange on TCP
Reimplemented from Omiscid::MsgSocket.
Definition at line 73 of file TcpClient.cpp.
References Omiscid::MsgSocket::GetMaxMessageSizeForTCP().
{
    return MsgSocket::GetMaxMessageSizeForTCP();
}
ComTools * TcpClient::Cast () [virtual]
Cast in ComTools.
Returns:
the Comtool pointer on an object that derived Comtool
Implements Omiscid::ComTools.
Definition at line 47 of file TcpClient.cpp.
{
    return dynamic_cast<ComTools*>(this);
}
The documentation for this class was generated from the following files:
Com/Com/TcpClient.h
Com/TcpClient.cpp