OMiSCID(aka O3MiSCID): Omiscid::ServiceProxy Class Reference
Omiscid::ServiceProxy Class Reference
#include <ServiceProxy.h>
Public Member Functions
SimpleList< SimpleString > & GetVariables ()
SimpleList< SimpleString > & GetInputConnectors ()
SimpleList< SimpleString > & GetOutputConnectors ()
SimpleList< SimpleString > & GetInputOutputConnectors ()
void UpdateDescription ()
SimpleString GetHostName ()
unsigned int GetPeerId ()
SimpleString GetPeerIdAsString ()
SimpleString GetName ()
bool HasVariable (const SimpleString VarName)
bool SetVariableValue (const SimpleString VarName, const SimpleString value)
SimpleString GetVariableValue (const SimpleString VarName)
SimpleString GetVariableType (const SimpleString VarName)
SimpleString GetVariableDescription (const SimpleString VarName)
VariableAccessType GetVariableAccessTypeType (const SimpleString VarName)
bool AddRemoteVariableChangeListener (const SimpleString VarName, RemoteVariableChangeListener *Listener)
bool RemoveRemoteVariableChangeListener (const SimpleString VarName, RemoteVariableChangeListener *Listener)
bool HasConnector (const SimpleString ConnectorName, ConnectorKind ItsKind=UnkownConnectorKind)
SimpleString FindConnector (unsigned int PeerId)
SimpleString GetConnectorDescription (const SimpleString ConnectorName)
Detailed Description
Author:
Definition at line 31 of file ServiceProxy.h.
Member Function Documentation
SimpleList< SimpleString > & ServiceProxy::GetVariables ()
Returns the list of variables
Returns:
the list of variables
Definition at line 238 of file ServiceProxy.cpp.
References Omiscid::ControlClient::GetVariableNameList().
{
    return GetVariableNameList();
}
SimpleList< SimpleString > & ServiceProxy::GetInputConnectors ()
Returns the list of connectors (input type)
Returns:
the list of connectors
Definition at line 247 of file ServiceProxy.cpp.
References Omiscid::ControlClient::GetInputNameList(), and UpdateDescription().
{
    // We got everything
    if ( FullDescription == true )
    {
        return GetInputNameList();
    }
    // In other case, update the description
    UpdateDescription();
    return GetInputNameList();
}
SimpleList< SimpleString > & ServiceProxy::GetOutputConnectors ()
Returns the list of connectors (output type)
Returns:
the list of connectors
Definition at line 265 of file ServiceProxy.cpp.
References Omiscid::ControlClient::GetOutputNameList(), and UpdateDescription().
{
    // We got everything
    if ( FullDescription == true )
    {
        return GetOutputNameList();
    }
    // In other case, update the description
    UpdateDescription();
    return GetOutputNameList();
}
SimpleList< SimpleString > & ServiceProxy::GetInputOutputConnectors ()
Returns the list of connectors (input-output type)
Returns:
the list of connectors
Definition at line 283 of file ServiceProxy.cpp.
References Omiscid::ControlClient::GetInOutputNameList(), and UpdateDescription().
{
    // We got everything
    if ( FullDescription == true )
    {
        return GetInOutputNameList();
    }
    // In other case, update the description
    UpdateDescription();
    return GetInOutputNameList();
}
void ServiceProxy::UpdateDescription ()
Updates the local view of a remote Omiscid service :
the list of variables (and value)
the list of connectors (and port)
Updates the local view of a remote bip service :
the list of variables
the list of connectors
Definition at line 304 of file ServiceProxy.cpp.
References Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::MsgSocket::IsConnected(), and Omiscid::ControlClient::QueryDetailedDescription().
Referenced by FindConnector(), GetInputConnectors(), GetInputOutputConnectors(), GetOutputConnectors(), and SetVariableValue().
{
    if ( FullDescription == true )
    {
        return;
    }
    if ( IsConnected() == false )
    {
        ConnectToCtrlServer( HostName, ControlPort );
    }
    if ( QueryDetailedDescription() == true )
    {
        FullDescription = true;
    }
    // else the value of FullDescription remain the same
}
SimpleString ServiceProxy::GetHostName ()
Host name where the remote service is located
Returns:
the host name
Definition at line 328 of file ServiceProxy.cpp.
Referenced by Omiscid::Service::ConnectTo().
{
    return HostName;
}
unsigned int ServiceProxy::GetPeerId ()
The Peer Id of the remote Omiscid service
Returns:
the peer id
The Peer Id of the remote bip service
Returns:
the peer id
Definition at line 342 of file ServiceProxy.cpp.
References GetVariableValue(), and Omiscid::ComTools::PeerIdFromString().
Referenced by Omiscid::Service::CloseConnection(), and Omiscid::Service::SendToOneClient().
{
    try
    {
        SimpleString lPeerId = GetVariableValue( CommonServiceValues::NameForPeerIdString );
        return ComTools::PeerIdFromString(lPeerId);
    }
    catch( SimpleException & )
    {
    }
    return 0;
}
SimpleString ServiceProxy::GetPeerIdAsString ()
The string containing the Peer Id of the remote bip service
Returns:
the peer id as a string
Definition at line 361 of file ServiceProxy.cpp.
References Omiscid::SimpleString::EmptyString, and GetVariableValue().
{
    try
    {
        return GetVariableValue( CommonServiceValues::NameForPeerIdString );
    }
    catch( SimpleException& )
    {
    }
    return SimpleString::EmptyString;
}
SimpleString ServiceProxy::GetName ()
The name of the remote Omiscid service
Returns:
name
Reimplemented from Omiscid::MsgSocket.
Definition at line 333 of file ServiceProxy.cpp.
References GetVariableValue().
{
    return GetVariableValue( CommonServiceValues::NameForNameString );
}
bool ServiceProxy::HasVariable (const SimpleString VarName)
Check availability of a variable
Parameters:
VarName the name of the remote variable
Definition at line 636 of file ServiceProxy.cpp.
{
    return (FindVariable(VarName) != NULL);
}
bool ServiceProxy::SetVariableValue (const SimpleString VarName, const SimpleString Value)
Sets the new value of a remote variable
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
Definition at line 379 of file ServiceProxy.cpp.
References Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::MsgSocket::IsConnected(), Omiscid::ControlClient::QueryVariableModif(), and UpdateDescription().
{
    // Update description if needed
    if ( FullDescription == false )
    {
        UpdateDescription();
    }
    if ( IsConnected() == false )
    {
        // Update description if needed
        if ( ConnectToCtrlServer(HostName, ControlPort) == false )
        {
            throw SimpleException("Can not connect to the Service.");
        }
    }
    if ( QueryVariableModif(VarName, Value) == NULL )
    {
        return false;
    }
    return true;
}
SimpleString ServiceProxy::GetVariableValue (const SimpleString VarName)
Gets the value of a remote variable
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
Definition at line 409 of file ServiceProxy.cpp.
References Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::VariableAttribute::GetAccess(), Omiscid::VariableAttribute::GetValue(), Omiscid::MsgSocket::IsConnected(), Omiscid::VariableAttribute::IsInitialised(), and Omiscid::ControlClient::QueryVariableDescription().
Referenced by GetName(), GetPeerId(), and GetPeerIdAsString().
{
    VariableAttribute * pVar = FindVariable(VarName);
    if ( pVar == NULL )
    {
        SimpleString ErrMesg;
        ErrMesg = "Unknown variable '";
        ErrMesg += VarName;
        ErrMesg += "'. Call HasVariableFirst.";
        throw  SimpleException( ErrMesg );
    }
    // If the variable is initialised
    if ( pVar->IsInitialised() )
    {
        // If we can get the current value
        if ( pVar->GetAccess() == ConstantAccess && FullDescription == true )
        {
            return pVar->GetValue();
        }
    }
    if ( IsConnected() == false )
    {
        // Update description if needed
        if ( ConnectToCtrlServer(HostName, ControlPort) == false )
        {
            throw SimpleException("Can not connect to the Service.");
        }
    }
    // Il all other cases
    pVar = QueryVariableDescription( VarName );
    if ( pVar == NULL )
    {
        // This one *here* should not appear
        throw SimpleException( "Could not retrieve variable '" + VarName + "'." );
    }
    return pVar->GetValue();
}
SimpleString ServiceProxy::GetVariableType (const SimpleString VarName)
Gets the type of a remote variable
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
Definition at line 455 of file ServiceProxy.cpp.
References Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::VariableAttribute::GetType(), Omiscid::MsgSocket::IsConnected(), Omiscid::VariableAttribute::IsInitialised(), and Omiscid::ControlClient::QueryVariableDescription().
{
    VariableAttribute * pVar = FindVariable(VarName);
    if ( pVar == NULL )
    {
        SimpleString ErrMesg;
        ErrMesg = "Unknown variable '";
        ErrMesg += VarName;
        ErrMesg += "'. Call HasVariableFirst.";
        throw  SimpleException( ErrMesg );
    }
    // If the variable is initialised
    if ( pVar->IsInitialised() )
    {
        // return the current type
        return pVar->GetType();
    }
    if ( IsConnected() == false )
    {
        // Update description if needed
        if ( ConnectToCtrlServer(HostName, ControlPort) == false )
        {
            throw SimpleException("Can not connect to the Service.");
        }
    }
    // Il all other cases
    pVar = QueryVariableDescription( VarName );
    if ( pVar == NULL )
    {
        // This one *here* should not appear
        throw SimpleException( "Could not retrieve variable '" + VarName + "'." );
    }
    return pVar->GetType();
}
SimpleString ServiceProxy::GetVariableDescription (const SimpleString VarName)
Gets the description of a remote variable
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
Definition at line 499 of file ServiceProxy.cpp.
References Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::Attribute::GetDescription(), Omiscid::MsgSocket::IsConnected(), Omiscid::VariableAttribute::IsInitialised(), and Omiscid::ControlClient::QueryVariableDescription().
{
    VariableAttribute * pVar = FindVariable(VarName);
    if ( pVar == NULL )
    {
        SimpleString ErrMesg;
        ErrMesg = "Unknown variable '";
        ErrMesg += VarName;
        ErrMesg += "'. Call HasVariableFirst.";
        throw  SimpleException( ErrMesg );
    }
    // If the variable is initialised
    if ( pVar->IsInitialised() )
    {
        // return the current description
        return pVar->GetDescription();
    }
    if ( IsConnected() == false )
    {
        // Update description if needed
        if ( ConnectToCtrlServer(HostName, ControlPort) == false )
        {
            throw SimpleException("Can not connect to the Service.");
        }
    }
    // Il all other cases
    pVar = QueryVariableDescription( VarName );
    if ( pVar == NULL )
    {
        // This one *here* should not appear
        throw SimpleException( "Could not retrieve variable '" + VarName + "'." );
    }
    return pVar->GetDescription();
}
VariableAccessType Omiscid::ServiceProxy::GetVariableAccessTypeType (const SimpleString VarName)
Gets the value of a remote variable
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
bool ServiceProxy::AddRemoteVariableChangeListener (const SimpleString VarName, RemoteVariableChangeListener * Listener)
Add a listener to monitor variable changes
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
Definition at line 543 of file ServiceProxy.cpp.
References Omiscid::VariableAttribute::AddListener(), Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::VariableAttribute::GetNumberOfListeners(), Omiscid::MsgSocket::IsConnected(), and Omiscid::ControlClient::Subscribe().
{
    // Serach the variable
    VariableAttribute * pVar = FindVariable( VarName );
    if ( pVar == NULL )
    {
        // not found
        return false;
    }
    if ( IsConnected() == false )
    {
        // Update description if needed
        if ( ConnectToCtrlServer(HostName, ControlPort) == false )
        {
            throw SimpleException("Can not connect to the Service.");
        }
    }
    // Add information about me
    Listener->SetUserData( this );
    // If we can not add the listener
    if ( pVar->AddListener( Listener ) == false )
    {
        // Add information about me
        Listener->SetUserData( NULL );
        // Say there was a problem
        return false;
    }
    // If it is the first listener, subscribe to the variable changes
    if ( pVar->GetNumberOfListeners() == 1 )
    {
        // first listener
        // Subscribe to the variable changes
        Subscribe( VarName );
    }
    // ok
    return true;
}
bool ServiceProxy::RemoveRemoteVariableChangeListener (const SimpleString VarName, RemoteVariableChangeListener * Listener)
Remove a listener to monitor variable changes
Parameters:
VarName the name of the remote variable
value the value (SimpleString format)
Definition at line 592 of file ServiceProxy.cpp.
References Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::VariableAttribute::GetNumberOfListeners(), Omiscid::MsgSocket::IsConnected(), Omiscid::VariableAttribute::RemoveListener(), and Omiscid::ControlClient::Unsubscribe().
{
    bool ret;
    // Serach for the variable
    VariableAttribute * pVar = FindVariable( VarName );
    if ( pVar == NULL )
    {
        // Not found
        return false;
    }
    if ( IsConnected() == false )
    {
        // Update description if needed
        if ( ConnectToCtrlServer(HostName, ControlPort) == false )
        {
            throw SimpleException("Can not connect to the Service.");
        }
    }
    // Aswk to remove the listener
    ret = pVar->RemoveListener( Listener );
    if ( ret == false )
    {
        // something goes wrong
        return false;
    }
    // Do we have any listener left ?
    if ( pVar->GetNumberOfListeners() == 0 )
    {
        // If no, unsubscribe to the variable changes
        Unsubscribe( VarName );
    }
    // say, it was ok
    return true;
}
bool ServiceProxy::HasConnector (const SimpleString ConnectorName, ConnectorKind ItsKind = UnkownConnectorKind)
search for a connector on the remote Omiscid service
Parameters:
ConnectorName the name of the remote variable
Returns:
true or false
Definition at line 647 of file ServiceProxy.cpp.
References FindConnector(), and Omiscid::InOutputAttribute::GetType().
{
    InOutputAttribute * pAtt = FindConnector(ConnectorName);
    if ( pAtt == NULL )
    {
        return false;
    }
    if ( ItsKind != UnkownConnectorKind && pAtt->GetType() != ItsKind )
    {
        return false;
    }
    return true;
}
SimpleString ServiceProxy::FindConnector (unsigned int PeerId)
Find a connector using its full or local PeerId
search for a connector on the remote Omiscid service
Parameters:
ConnectorName the name of the remote variable
Returns:
true or false
Definition at line 666 of file ServiceProxy.cpp.
References Omiscid::SimpleString::EmptyString, Omiscid::ControlClient::listInOutputAttr, Omiscid::ControlClient::listInputAttr, Omiscid::ControlClient::listOutputAttr, and UpdateDescription().
Referenced by GetConnectorDescription(), and HasConnector().
{
    // Update description if needed
    if ( FullDescription == false )
    {
        UpdateDescription();
    }
    // Serach for the connector
    for( listInputAttr.First(); listInputAttr.NotAtEnd(); listInputAttr.Next() )
    {
        if ( listInputAttr.GetCurrent()->GetPeerId() == PeerId )
        {
            return listInputAttr.GetCurrent()->GetName();
        }
    }
    for( listOutputAttr.First(); listOutputAttr.NotAtEnd(); listOutputAttr.Next() )
    {
        if ( listOutputAttr.GetCurrent()->GetPeerId() == PeerId )
        {
            return listOutputAttr.GetCurrent()->GetName();
        }
    }
    for( listInOutputAttr.First(); listInOutputAttr.NotAtEnd(); listInOutputAttr.Next() )
    {
        if ( listInOutputAttr.GetCurrent()->GetPeerId() == PeerId )
        {
            return listInOutputAttr.GetCurrent()->GetName();
        }
    }
    return SimpleString::EmptyString;
}
SimpleString ServiceProxy::GetConnectorDescription (const SimpleString ConnectorName)
Find a connector using its full or local PeerId
Retrieve the description of a remote controler
Parameters:
ConnectorName the name of the remote connector
Returns:
the description in a SimpleString
Definition at line 707 of file ServiceProxy.cpp.
References FindConnector(), and Omiscid::Attribute::GetDescription().
{
    InOutputAttribute * pAtt;
    pAtt = FindConnector( ConnectorName );
    if ( pAtt == (InOutputAttribute *)NULL )
    {
        SimpleString ErrMesg;
        ErrMesg = "Unknown Connector '";
        ErrMesg += ConnectorName;
        ErrMesg += "'. Call HasConnector First.";
        throw  SimpleException( ErrMesg );
    }
    return pAtt->GetDescription();
}
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/ServiceProxy.h
ServiceControl/ServiceProxy.cpp