OMiSCID(aka O3MiSCID): Omiscid::ServiceProperty Class Reference
Omiscid::ServiceProperty Class Reference
A basic property for a DNS-SD service.
#include <ServiceProperties.h>
Inherited by Omiscid::ServicePropertyNotify.
Public Member Functions
ServiceProperty ()
Default constructor.
ServiceProperty (const SimpleString Name, const SimpleString Value=SimpleString::EmptyString)
Alternate constructor.
void Empty ()
Empty a property.
virtual bool SetProperty (const SimpleString Name, const SimpleString Value=SimpleString::EmptyString)
Set name and optionaly value for a property.
virtual bool UpdateProperty (const SimpleString Value)
Change a value for a property that have already a name.
Detailed Description
A basic property for a DNS-SD service.
This class implements the basic properties for a service as defined in the DNS-SD documentation. It works using a real memory image of the final data : a 255 bytes buffer containing both name and optional value for the property. The first byte contains the full length of this property.
The ServiceProperties class is declared as a friend class of ServiceProperty. Thus, it can access to the private and protected members.
Definition at line 56 of file ServiceProperties.h.
Constructor & Destructor Documentation
ServiceProperty::ServiceProperty ()
Default constructor.
The default constructor constructs an empty property (see ServiceProperty::Empty).
Definition at line 41 of file ServiceProperties.cpp.
References Empty().
{
    // Just call the empty function
    Empty();
}
ServiceProperty::ServiceProperty (const SimpleString Name, const SimpleString Value = SimpleString::EmptyString)
Alternate constructor.
Parameters:
[in] Name a const c-SimpleString containing the property name.
[in] Value an optional const c-SimpleString containing the value of the property
Exceptions:
ServicePropertiesException The value of the error message sould be "Bad parameter(s) for the ServiceProperty constructor"
This constructor takes a name and optionaly a value for the new constructed property. See ServiceProperty::SetProperty.
Parameters:
[in] Name a const c-SimpleString containing the property name.
[in] Value an optional const c-SimpleString containing the value of the property
Exceptions:
ServicePropertiesException The value of the error message sould be "Bad parameter(s) for the ServiceProperty constructor"
This constructor takes a name and optionaly a value for the new constructed property. See ServiceProperty::SetProperty.
Definition at line 54 of file ServiceProperties.cpp.
References SetProperty().
{
    // Call the virtual function SetProperty
    if ( SetProperty( Name, Value ) == false )
    {
        // Can not set the name or value for this property. Raise an exception.
        throw ServicePropertiesException( "Bad parameter(s) for the ServiceProperty constructor" );
    }
}
Member Function Documentation
void ServiceProperty::Empty ()
Empty a property.
This function empty a property. The Length is set to 1 (just the byte containing the length of the property), the intinsect BinaryLength of the property (the only byte) is set to 0 as the NameLength and the ValueLength.
In debug mode, we also full the Hash with 0.
Definition at line 30 of file ServiceProperties.cpp.
References Omiscid::SimpleString::Empty().
Referenced by ServiceProperty(), and SetProperty().
{
    Length = 1;
    Name.Empty();
    Value.Empty();
}
bool ServiceProperty::SetProperty (const SimpleString eName, const SimpleString eValue = SimpleString::EmptyString) [virtual]
Set name and optionaly value for a property.
Parameters:
[in] Name a const c-SimpleString containing the property name.
[in] Value an optional const c-SimpleString containing the value of the property
Returns:
a boolean answer if changes are made.
This function changes name and optionaly value for a property. If a problem occurs, the property remains unchanged. You can define property as follow:
if Name equals "Property" and Value is NULL, we will have a flag : "Property".
if Name equals "Property" and Value is "", we will have an empty property : "Property=".
if Name equals "Property" and Value is "something", we will have : "Property=something".
Parameters:
[in] Name a const c-SimpleString containing the property name.
[in] Value an optional const c-SimpleString containing the value of the property
Returns:
a boolean answer if changes are made.
This function changes name and optionaly value for a property. If a problem occurs, the property will be empty. You can define property as follow:
if Name equals "Property" and Value is NULL, we will have a flag : "Property".
if Name equals "Property" and Value is "", we will have an empty property : "Property=".
if Name equals "Property" and Value is "something", we will have : "Property=something".
Definition at line 78 of file ServiceProperties.cpp.
References Empty(), Omiscid::SimpleString::GetLength(), and UpdateProperty().
Referenced by ServiceProperty().
{
    // First of all, empty the property
    Empty();
    // Empty names are illegals
    // Name + '=' + value must be 255 long at max !!!
    if ( eName.GetLength() == 0 || (eName.GetLength()+1+eValue.GetLength()) > 255 )
    {
        return false;
    }
    // Set Name
    Name = eName;
    // Set length to the Value of the name
    Length = Name.GetLength() + 1;
    if ( UpdateProperty( eValue ) == false )
    {
        Empty();
    }
    return true;
}
bool ServiceProperty::UpdateProperty (const SimpleString Value) [virtual]
Change a value for a property that have already a name.
Parameters:
[in] Value an mandatory const c-SimpleString containing the value of the property
Returns:
a boolean answer if changes are made.
This function changes value for a property. If a problem occurs, the property will be empty.
See ServiceProperty::SetProperty for possible values.
Definition at line 104 of file ServiceProperties.cpp.
References Omiscid::SimpleString::GetLength().
Referenced by SetProperty().
{
    if ( Name.GetLength() == 0 )
    {
        return false;
    }
    Value = eValue;
    Length = Name.GetLength() + 1 + Value.GetLength() + 1;
    return true;
}
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/ServiceProperties.h
ServiceControl/ServiceProperties.cpp