OMiSCID(aka O3MiSCID): Omiscid::Mutex Class Reference
Omiscid::Mutex Class Reference
Mutex Implementation.
#include <System/Mutex.h>
Public Member Functions
Mutex ()
Constructor.
virtual ~Mutex ()
Destructor.
bool Lock ()
Lock the mutex.
bool EnterMutex ()
Lock the mutex. Deprecated, use Mutex::Lock instead.
bool Unlock ()
Unlock the mutex.
bool LeaveMutex ()
Unlock the mutex. Deprecated, use Mutex::Unlock instead.
Detailed Description
Mutex Implementation.
Mutex enables to lock some code section to avoid multiple access by several threads. The mutex are not reentrant.
Author:
Dominique Vaufreydaz
Sebastien Pesnel
Definition at line 24 of file Mutex.h.
Member Function Documentation
bool Mutex::Lock () [virtual]
Lock the mutex.
Wait if the mutex is already locked, until it is unlocked, and then locks the mutex
Returns:
false if an error occured
Implements Omiscid::LockableObject.
Definition at line 51 of file Mutex.cpp.
References Omiscid::Thread::GetThreadId().
Referenced by EnterMutex(), and Omiscid::MsgSocket::SetCallbackSyncLink().
{
#ifdef WIN32
    unsigned int Result = WaitForSingleObject( mutex, INFINITE );
    if ( Result == WAIT_OBJECT_0 )
    {
#ifdef DEBUG
        // In debug mode, set the owner id
        OwnerId = Thread::GetThreadId();
#endif
        // Here we go, we've got the mutex
        return true;
    }
#else
    if( pthread_mutex_lock(&mutex) == 0 )
    {
#ifdef DEBUG
        // In debug mode, set the owner id
        OwnerId = Thread::GetThreadId();
#endif
        return true;
    }
#endif
    return false;
}
bool Omiscid::Mutex::EnterMutex () [inline]
Lock the mutex. Deprecated, use Mutex::Lock instead.
Wait if the mutex is already locked, until it is unlocked, and then locks the mutex
Returns:
false if an error occured
Definition at line 46 of file Mutex.h.
References Lock().
{ return Lock(); };
bool Mutex::Unlock () [virtual]
Unlock the mutex.
Enables other clients to use the critical section protected by this mutex.
Implements Omiscid::LockableObject.
Definition at line 78 of file Mutex.cpp.
Referenced by LeaveMutex(), and Omiscid::MsgSocket::SetCallbackSyncLink().
{
#ifdef WIN32
    // if ( !ReleaseMutex(mutex) )
    if ( !ReleaseSemaphore(mutex,1,NULL) )
    {
        return false;
    }
#else
    if( pthread_mutex_unlock(&mutex) != 0 )
    {
        return false;
    }
#endif
#ifdef DEBUG
    OwnerId = 0;
#endif
    return true;
}
bool Omiscid::Mutex::LeaveMutex () [inline]
Unlock the mutex. Deprecated, use Mutex::Unlock instead.
Enables other clients to use the critical section protected by this mutex.
Definition at line 60 of file Mutex.h.
References Unlock().
{ return Unlock(); };
The documentation for this class was generated from the following files:
System/System/Mutex.h
System/Mutex.cpp