OMiSCID(aka O3MiSCID): Omiscid::SmartLocker Class Reference
Omiscid::SmartLocker Class Reference
SmartLocker can check the lock is removed and them unlock it when destroyed. This class is designed to operate in functions. It is not thread safe.
#include <System/LockManagement.h>
Public Member Functions
SmartLocker (LockableObject &LockableObjectToManage, bool LockAtInit=true)
Constructor.
SmartLocker (const LockableObject &LockableObjectToManage, bool LockAtInit=true)
Constructor.
virtual ~SmartLocker ()
Constructor.
bool Lock ()
Function used to lock the LockableObject object.
bool Unlock ()
Function used to unlock the LockableObject object.
Detailed Description
SmartLocker can check the lock is removed and them unlock it when destroyed. This class is designed to operate in functions. It is not thread safe.
Author:
Dominique Vaufreydaz
Definition at line 52 of file LockManagement.h.
Constructor & Destructor Documentation
SmartLocker::SmartLocker (LockableObject & LockableObjectToManage, bool LockAtInit = true)
Constructor.
Parameters:
LockableObjectToManage a reference to the object to managed
LockAtInit do we lock this LockAtInit
Definition at line 13 of file LockManagement.cpp.
References Lock().
    : ManagedLoackableObject(LockableObjectToManage)
{
    // Initiate the LockCount
    LockCount = 0;
    // Here, we are ready to work
    if ( LockAtInit == true )
    {
        Lock();
    }
}
SmartLocker::SmartLocker (const LockableObject & LockableObjectToManage, bool LockAtInit = true)
Constructor.
Parameters:
LockableObjectToManage a reference to the object to managed
Definition at line 29 of file LockManagement.cpp.
References Lock().
    : ManagedLoackableObject(dynamic_cast<LockableObject&>((LockableObject&)LockableObjectToManage))
{
    // Initiate the LockCount
    LockCount = 0;
    // Here, we are ready to work
    if ( LockAtInit == true )
    {
        Lock();
    }
}
SmartLocker::~SmartLocker () [virtual]
Constructor.
Desonstructor.
Definition at line 46 of file LockManagement.cpp.
References Omiscid::LockableObject::Unlock().
{
    if ( LockCount > 0 )
    {
        // OmiscidError( "SmartLocker::SmartLocker~: warning object not unlock before exiting the scope\n" );
        while( LockCount > 0 )
        {
            ManagedLoackableObject.Unlock();
            LockCount--;
        }
    }
}
Member Function Documentation
bool SmartLocker::Lock ()
Function used to lock the LockableObject object.
Definition at line 62 of file LockManagement.cpp.
References Omiscid::LockableObject::Lock().
Referenced by SmartLocker(), and Omiscid::Thread::WaitAndGetMessage().
{
    if ( ManagedLoackableObject.Lock() == true )
    {
        LockCount++;
        return true;
    }
    return false;
}
bool SmartLocker::Unlock ()
Function used to unlock the LockableObject object.
Definition at line 75 of file LockManagement.cpp.
References Omiscid::LockableObject::Unlock().
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::Connector::AcceptConnection(), Omiscid::ServiceRepository::AddListener(), Omiscid::Connector::ConnectTo(), Omiscid::UdpExchange::FindConnectionFromId(), Omiscid::Accumulator::MessageReceived(), Omiscid::ServiceRepository::RemoveListener(), Omiscid::MsgSocket::Send(), Omiscid::MsgSocket::SendCuttedMsg(), Omiscid::Connector::SendToAll(), Omiscid::Connector::SendToPeer(), Omiscid::Thread::WaitAndGetMessage(), and Omiscid::ControlServer::~ControlServer().
{
    if ( LockCount == 0 )
    {
        OmiscidError( "SmartLocker::Unlock : the object is not lock." );
        return false;
    }
    if ( ManagedLoackableObject.Unlock() == true )
    {
        LockCount--;
        return true;
    }
    return false;
}
The documentation for this class was generated from the following files:
System/System/LockManagement.h
System/LockManagement.cpp