OMiSCID(aka O3MiSCID): Omiscid::UdpConnection Class Reference
Omiscid::UdpConnection Class Reference
Contains data about UDP Connection.
#include <Com/MsgSocket.h>
Public Member Functions
UdpConnection ()
Default Constructor.
UdpConnection (const SimpleString addr, int port)
Constructor.
UdpConnection (const UdpConnection &udp_connect)
Copy Constructor.
virtual ~UdpConnection ()
Destructor.
bool operator== (const UdpConnection &) const
Compare two UdpConnection objects. Comparaison of the structure address.
void SetAddr (const struct sockaddr_in *addr)
set the value of the address structure
struct sockaddr_in * getAddr () const
Public Attributes
struct sockaddr_in addr
unsigned int pid
Detailed Description
Contains data about UDP Connection.
Author:
Sebastien Pesnel
Definition at line 45 of file MsgSocket.h.
Constructor & Destructor Documentation
UdpConnection::UdpConnection (const SimpleString addr, int port)
Constructor.
Parameters:
addr [in] host address
port [in] port number
Definition at line 30 of file MsgSocket.cpp.
References addr.
{
    //REVIEW
    /*  addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    if(!strcmp(an_addr, ""))  addr.sin_addr.s_addr = INADDR_ANY;
    else addr.sin_addr.s_addr = inet_addr(an_addr);
    memset(&(addr.sin_zero), 0, 8); */
    Socket::FillAddrIn( &addr, an_addr, port );
}
UdpConnection::UdpConnection (const UdpConnection & udp_connect)
Copy Constructor.
Parameters:
udp_connect [in] the UdpConnection object to copy.
Definition at line 20 of file MsgSocket.cpp.
References addr.
: pid(udp_connect.pid)
{
    memcpy(&addr, &(udp_connect.addr), sizeof(struct sockaddr_in));
}
Member Function Documentation
bool UdpConnection::operator== (const UdpConnection & udp_connect) const
Compare two UdpConnection objects. Comparaison of the structure address.
Returns:
true if the two UdpConnection objects have the same address.
Definition at line 1454 of file MsgSocket.cpp.
References addr, and getAddr().
{
    return !memcmp(&addr, udp_connect.getAddr(), sizeof(struct sockaddr));
}
void UdpConnection::SetAddr (const struct sockaddr_in * addr)
set the value of the address structure
set the value of the structure sockaddr_in
Parameters:
addr [in] the structure to copy
Definition at line 41 of file MsgSocket.cpp.
References addr.
Referenced by Omiscid::Connector::AcceptConnection().
{
    memcpy(&addr, nv_addr, sizeof(struct sockaddr_in));
}
struct sockaddr_in * UdpConnection::getAddr () const [read]
Returns:
a pointer on the structure sockaddr_in
Definition at line 1449 of file MsgSocket.cpp.
References addr.
Referenced by Omiscid::Connector::AcceptConnection(), and operator==().
{
    return &addr;
}
Member Data Documentation
struct sockaddr_in Omiscid::UdpConnection::addr [read]
the address data
Definition at line 83 of file MsgSocket.h.
Referenced by getAddr(), operator==(), Omiscid::UdpExchange::SendTo(), Omiscid::MsgSocket::SendTo(), SetAddr(), and UdpConnection().
unsigned int Omiscid::UdpConnection::pid
the peer identifier
Definition at line 84 of file MsgSocket.h.
Referenced by Omiscid::Connector::AcceptConnection().
The documentation for this class was generated from the following files:
Com/Com/MsgSocket.h
Com/MsgSocket.cpp