OMiSCID(aka O3MiSCID): Omiscid::Socket Class Reference
Omiscid::Socket Class Reference
Socket for tcp or udp communication.
#include <System/Socket.h>
Public Types
enum SocketKind
Socket Kind.
Public Member Functions
Socket ()
Constructor.
Socket (SocketKind type)
Constructor.
virtual ~Socket ()
Destructor.
void SetDescriptor (SOCKET descr)
Define the socket descriptor, and retrieve data about this to set the socket type.
void Bind (const SimpleString addr, int port)
Bind the socket to addr:port.
void Listen ()
Listen for connections on a socket.
Exceptions:
SocketException error calling listen.
Socket * Accept ()
Wait for new connection during 100ms.
void Connect (const SimpleString addr, int port)
Initiate a connection on a socket.
void Close ()
Close the connection.
int Recv (int len, unsigned char *buf, struct sockaddr_in *pfrom=NULL)
receive data on the socket
int Send (int len, const char *buf)
Send a buffer of byte.
int SendTo (int len, const char *buf, struct sockaddr_in *dest)
Send a buffer of byte to a destination (for datagram).
bool Select ()
unsigned short GetPortNb ()
Access to the port number.
Static Public Member Functions
static SimpleString GetHostName ()
Detailed Description
Socket for tcp or udp communication.
Definition at line 26 of file Socket.h.
Constructor & Destructor Documentation
Socket::Socket ()
Constructor.
Create an instance. Don't create a socket descriptor. To use with a call to the dunction SetDescriptor.
See also:
SetDescriptor
Definition at line 61 of file Socket.cpp.
Referenced by Accept().
: socketType(SOCKET_KIND_UNDEFINED), descriptor((SOCKET)SOCKET_ERROR)
{}
Socket::Socket (SocketKind type)
Constructor.
Create an instance, and a socket descriptor according to 'type'
Parameters:
type [in] kind of socket : TCP or UDP.
Exceptions:
SocketException error during the creation of the socket descriptor.
Definition at line 65 of file Socket.cpp.
References SOCKET_ERROR.
: socketType(type), descriptor((SOCKET)SOCKET_ERROR)
{
    if((descriptor = socket(AF_INET, type, 0)) == SOCKET_ERROR)
    {
        throw SocketException("socket", Errno());
    }
}
Socket::~Socket () [virtual]
Destructor.
Close the socket by calling Close.
See also:
Close
Definition at line 74 of file Socket.cpp.
References Close().
{
    Close();
}
Member Function Documentation
void Socket::SetDescriptor (SOCKET descr)
Define the socket descriptor, and retrieve data about this to set the socket type.
Parameters:
descr [in] the socket descriptor
Exceptions:
SocketException error when retrieving information
Definition at line 88 of file Socket.cpp.
References SOCKET_ERROR.
Referenced by Accept().
{
    descriptor = descr;
    int t;
    int size = sizeof(int);
    if(getsockopt(descriptor, SOL_SOCKET,SO_TYPE , (char*)&t, (socklen_t*)&size) == SOCKET_ERROR)
    {
        throw SocketException("getsockopt", Errno());
    }
    socketType = (SocketKind)t;
    //   if(socketType == TCP)
    //   {
    //     std::cerr << "TCP\n";
    //   }
    //   else if(socketType == UDP)
    //   {
    //     std::cerr << "UDP\n";
    //   }
    //   else
    //   {
    //     std::cerr << "Unknown\n";
    //   }
}
void Socket::Bind (const SimpleString addr, int port)
Bind the socket to addr:port.
Parameters:
addr [in] host address or name. If addr is empty, the host is the local host.
port [in] port number where bind the socket. If port equals zero, a free port number is chosen.
Exceptions:
SocketException error during binding.
Definition at line 114 of file Socket.cpp.
References SOCKET_ERROR.
Referenced by Omiscid::MsgSocket::InitForTcpServer(), and Omiscid::MsgSocket::InitForUdpExchange().
{
    //   if(socketType == UDP)
    //   {
    //     unsigned long on = 1;
    //     setsockopt(descriptor, SOL_SOCKET, SO_BROADCAST, (char const*)&on, sizeof(on));
    //     dest.sin_family = AF_INET;
    //     dest.sin_port = htons(port);
    //     dest.sin_addr.s_addr = INADDR_BROADCAST;
    //     memset(&(dest.sin_zero), 0, 8);
    //   }
    struct sockaddr_in my_addr;
    // REVIEW
    /* my_addr.sin_family = AF_INET;
    my_addr.sin_port = htons(port);
    if(!strcmp(addr, ""))
    {
    my_addr.sin_addr.s_addr = INADDR_ANY;
    }
    else
    {
    my_addr.sin_addr.s_addr = inet_addr(addr);
    }
    memset(&(my_addr.sin_zero), 0, 8); */
    if ( FillAddrIn( &my_addr, addr, port ) == false )
    {
        throw SocketException("Socket::Bind FillAddrIn");
    }
    if( bind(descriptor, (struct sockaddr*)&my_addr, sizeof(struct sockaddr) ) == SOCKET_ERROR)
    {
        throw SocketException("Socket::Bind bind");
    }
}
Socket * Socket::Accept ()
Wait for new connection during 100ms.
Returns:
a pointer to Socket object associated to the new connection. Null is returned if there is nothing to accept
Definition at line 162 of file Socket.cpp.
References SetDescriptor(), and Socket().
{
    // Variables to use the select function on our descriptor
    timeval timeout;
    fd_set fds;
    int nReady;
    int MaxDesc = 0;    // Maximal descriptor for the select function
    // REVIEW : a revoir...
    struct sockaddr_in the_addr;
    int size = sizeof(struct sockaddr_in);
    SOCKET new_fd;
    // ok, we will wait for an accept attempt for 100 ms
    timeout.tv_sec = 0;
    timeout.tv_usec = 100000;
    FD_ZERO(&fds);
    FD_SET( descriptor, &fds );
#ifndef WIN32
    MaxDesc = descriptor + 1;
#else
    // On WIN32 plateform, the value is unused and remain 0
#endif
    // Ok, wait for the connection...
    nReady = select(MaxDesc, &fds, NULL, NULL, &timeout);
    // If our socket can accept a connection...
    if ( nReady > 0 )
    {
        new_fd = accept(descriptor, (struct sockaddr*)&the_addr, (socklen_t*)&size);
        Socket* s = new OMISCID_TLM Socket();
        if ( s )
        {
            s->SetDescriptor(new_fd);
            return s;
        }
        // else we will return NULL at the end of the function
    }
    // ok, nothing to accept, go up to see if there is a pending request...
    return NULL;
}
void Socket::Connect (const SimpleString addr, int port)
Initiate a connection on a socket.
Parameters:
addr [in] address where connect
port [in] port where connect
Definition at line 274 of file Socket.cpp.
References SOCKET_ERROR.
Referenced by Omiscid::MsgSocket::InitForTcpClient().
{
    if(socketType == TCP)
    {
        struct sockaddr_in the_addr;
        FillAddrIn(&the_addr, addr, port);
        if( connect(descriptor, (struct sockaddr*)&the_addr, sizeof(struct sockaddr)) == SOCKET_ERROR )
        {
#ifdef DEBUG
            SimpleString Mesg;
            Mesg = "connect to ";
            Mesg += addr;
            Mesg += ":";
            Mesg += port;
            throw SocketException(Mesg, Errno());
#else
            throw SocketException("connect", Errno());
#endif
        }
    }
    else /* UDP */
    {
        /*dest.sin_family = AF_INET;
        dest.sin_port = htons(port);
        dest.sin_addr = *((struct in_addr*)he->h_addr);
        //.s_addr = inet_addr(addr);
        memset(&(dest.sin_zero), 0, 8); */
        FillAddrIn(&dest, addr, port);
    }
}
int Socket::Recv (int len, unsigned char * buf, struct sockaddr_in * pfrom = NULL)
receive data on the socket
Parameters:
len [in] size of the buffer
buf [in] buffer where store the received bytes.
pfrom [in, out] receive the source of received byte in case of datagrams
Returns:
the number of byte received
Exceptions:
raise SocketException if error during receive
Definition at line 322 of file Socket.cpp.
References SOCKET_ERROR.
{
    int res = 0;
    if(socketType == TCP)
    {
        if((res = recv(descriptor, (char*)buf, len, 0)) == SOCKET_ERROR)
        {
            res = Errno();
            throw SocketException("recv_sock_stream", res );
        }
    }
    else
    {
        struct sockaddr_in from;
        struct sockaddr_in* fromptr = (pfrom)? pfrom : &from;
        int from_len = sizeof(struct sockaddr);
        if((res = recvfrom(descriptor, (char*)buf, len, 0,
            (struct sockaddr*)fromptr, (socklen_t*)&from_len)) == SOCKET_ERROR)
        {
            throw SocketException("recv_sock_dgram", Errno());
        }
    }
    return res;
}
int Socket::Send (int len, const char * buf)
Send a buffer of byte.
Send the message on the stream or the destination 'dest' in case of datagram
Parameters:
len [in] the length of the buffer
buf [in] the buffer of byte to send
Returns:
the number of send byte
Exceptions:
raise SocketException if error during sending
Definition at line 347 of file Socket.cpp.
References SOCKET_ERROR.
Referenced by Omiscid::MsgSocket::Send(), Omiscid::MsgSocket::SendCuttedMsg(), and Omiscid::MsgSocket::SendPreparedBuffer().
{
    const int socket_send_flag = MSG_NOSIGNAL;
    int res = 0;                // as gcc on gentoo seems not understand that this will be initialised
    if ( len <= 0 || buf == (const char*)NULL )
    {
        return SOCKET_ERROR;
    }
    if ( socketType == TCP )
    {
        if ( len > (TCP_BUFFER_SIZE-1) )
        {
            int TotalLen = 0;
            // Send all parts of the message in maximum TCP_BUFFER_SIZE frame
            // Let's send data... For linux, we can not send it as a single call to
            // send, so let's do it the other way... Naggle will do the rest...
            while( TotalLen < len )
            {
                if ( (len-TotalLen) >= (TCP_BUFFER_SIZE-1) )    // 60 Ko
                {
                    res = send(descriptor, (char*)(buf+TotalLen), (TCP_BUFFER_SIZE-1), socket_send_flag );
                }
                else
                {
                    res = send(descriptor, (char*)(buf+TotalLen), len-TotalLen, socket_send_flag );
                }
                if ( res == SOCKET_ERROR )
                {
                    throw SocketException("send_sock_stream", Errno());
                }
                TotalLen += res;
            }
            return TotalLen;
        }
        else
        {
            if ( (res = send(descriptor, buf, len, socket_send_flag)) == SOCKET_ERROR )
            {
                throw SocketException("send_sock_stream", Errno());
            }
        }
    }
    else
    {
        if((res = sendto(descriptor, buf, len, socket_send_flag,
            (struct sockaddr*)&dest, sizeof(struct sockaddr))) == SOCKET_ERROR)
        {
            throw SocketException("send_sock_dgram", Errno());
        }
    }
    return res;
}
int Socket::SendTo (int len, const char * buf, struct sockaddr_in * dest)
Send a buffer of byte to a destination (for datagram).
Parameters:
len [in] the length of the buffer
buf [in] the buffer of byte to send
dest [in] the destination of the message
Returns:
the number of send byte
Exceptions:
raise SocketException if error during sending
Definition at line 405 of file Socket.cpp.
References SOCKET_ERROR.
Referenced by Omiscid::MsgSocket::SendTo().
{
    const int socket_send_flag = MSG_NOSIGNAL;
    int res;
    if((res = sendto(descriptor, buf, len, socket_send_flag,
        (struct sockaddr*)adest, sizeof(struct sockaddr))) == SOCKET_ERROR)
    {
        throw SocketException("send_sock_dgram", Errno());
    }
    return res;
}
bool Socket::Select ()
Returns:
true if there are bytes to read
Definition at line 418 of file Socket.cpp.
References SOCKET_ERROR.
{
    // Done, change it to non full blocking mode....
    fd_set socketfds;
    timeval timeout;
    FD_ZERO(&socketfds);
    FD_SET(descriptor, &socketfds);
    // First check for event (like disconnection...)
    timeout.tv_sec = 0;
    timeout.tv_usec = 10;       // 10 micro seconds
    // Ask if some event are waiting on this socket
    if ( select((int)descriptor+1, NULL, NULL, &socketfds, &timeout) > 0 )
    {
        // Ok, something happens
        throw SocketException("select", Errno());
    }
    timeout.tv_sec = 0;
    timeout.tv_usec = 100000;   // 100 ms
    FD_ZERO(&socketfds);
    FD_SET(descriptor, &socketfds);
    if( select((int)descriptor+1, &socketfds, NULL, NULL, &timeout) == SOCKET_ERROR )
    {
        // A problem occurs
#ifdef WIN32
        throw SocketException("select",  Errno());
#else
        int err = Errno();
        if ( err != EINTR )
        {
            // This error is sent when there is a pending signal (not necessary
            // related to this socket) in order to get out of low level system
            // and let the appropriate process of the signal, so it is not an
            // error
            throw SocketException("select", err);
        }
#endif
    }
    return FD_ISSET(descriptor, &socketfds);
}
unsigned short Socket::GetPortNb ()
Access to the port number.
Returns:
the port where the socket is connected.
Definition at line 465 of file Socket.cpp.
Referenced by Omiscid::MsgSocket::GetPortNb(), and Omiscid::ControlServer::StartServer().
{
    struct sockaddr_in name;
    socklen_t size = sizeof(struct sockaddr_in);
    memset(&name, 0, size);
    if(getsockname(descriptor, (struct sockaddr*)&name, &size))
        throw SocketException("getsockname", Errno());
    return ntohs(name.sin_port);
}
SimpleString Socket::GetHostName () [static]
Return the host name on which the socket is connected.
Parameters:
name [in out] buffer of length 'len' where the name will copied.
len [in] lenght of the buffer name, where the result will be put.
Definition at line 477 of file Socket.cpp.
{
    TemporaryMemoryBuffer HostName(1024);
    if(::gethostname( HostName, 1023))
    {
        throw SocketException("GetHostName", Errno());
    }
    return SimpleString( HostName );
}
The documentation for this class was generated from the following files:
System/System/Socket.h
System/Socket.cpp