OMiSCID(aka O3MiSCID): Omiscid::StringVariableAttribute Class Reference
Omiscid::StringVariableAttribute Class Reference
Group an integer with its representation in the service description.
#include <ServiceControl/IntVariableAttribute.h>
Public Member Functions
StringVariableAttribute (VariableAttribute *va, SimpleString value)
Constructor.
SimpleString GetValue () const
Read access to the integer value.
void SetValue (SimpleString value)
Write access to the integer value.
Detailed Description
Group an integer with its representation in the service description.
The methods enable to manipulate the integer value, and to modify the description automatically.
Author:
Vaufreydaz Dominique
Definition at line 29 of file StringVariableAttribute.h.
Constructor & Destructor Documentation
StringVariableAttribute::StringVariableAttribute (VariableAttribute * va, SimpleString value)
Constructor.
Parameters:
va the description object
value the initial value for the integer
Definition at line 12 of file StringVariableAttribute.cpp.
References SetValue().
{
  VariableAtt = va;
  SetValue(value);
}
Member Function Documentation
SimpleString StringVariableAttribute::GetValue () const
Read access to the integer value.
Returns:
the integer value
Definition at line 24 of file StringVariableAttribute.cpp.
Referenced by Omiscid::ControlServer::GetClass(), Omiscid::Service::GetPeerId(), Omiscid::Service::GetPeerIdAsString(), and Omiscid::ControlServer::StartServer().
{
    return StringValue;
}
void StringVariableAttribute::SetValue (SimpleString value)
Write access to the integer value.
Change the integer value, and also the description for the service
Parameters:
value the new value for the integer
Definition at line 18 of file StringVariableAttribute.cpp.
References Omiscid::VariableAttribute::SetValueFromControl().
Referenced by Omiscid::ControlServer::SetClass(), Omiscid::ControlServer::StartServer(), and StringVariableAttribute().
{
    StringValue = value;
    VariableAtt->SetValueFromControl( StringValue );
}
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/StringVariableAttribute.h
ServiceControl/StringVariableAttribute.cpp