OMiSCID(aka O3MiSCID): Omiscid::ComTools Class Reference
Omiscid::ComTools Class Reference
Interface the communication tools.
#include <Com/ComTools.h>
Public Member Functions
virtual unsigned short GetTcpPort ()
Access to the TCP port.
virtual unsigned short GetUdpPort ()
Access to the UDP port.
virtual int GetListPeerId (SimpleList< unsigned int > &listId)=0
virtual unsigned int GetServiceId () const =0
Access to the service Id.
virtual void SetServiceId (unsigned int service_id)=0
Define the service id.
virtual ComTools * Cast ()=0
Cast in ComTools.
Static Public Member Functions
static unsigned int GeneratePeerId ()
Generation of service id.
static unsigned int PeerIdFromString (const SimpleString &StringPeerId)
transcode peer Id from strinf to unsigned int
static SimpleString PeerIdAsString (unsigned int PeerId)
transcode peer Id from strinf to unsigned int
Static Public Attributes
static const SimpleString MagicUdp
Gestion of Magic paquet.
Detailed Description
Interface the communication tools.
Common interface for TcpServer, TcpClient, UdpExchange, Connector
Author:
Sebastien Pesnel
Dominique Vaufreydaz
Definition at line 25 of file ComTools.h.
Member Function Documentation
unsigned short ComTools::GetTcpPort () [virtual]
Access to the TCP port.
Returns:
0 if there is no TCP port (default implementation do that)
Reimplemented in Omiscid::Connector, and Omiscid::TcpServer.
Definition at line 8 of file ComTools.cpp.
Referenced by Omiscid::InOutputAttribute::GenerateRecordData(), and Omiscid::InOutputAttribute::GetTcpPort().
{
  return 0;
}
unsigned short ComTools::GetUdpPort () [virtual]
Access to the UDP port.
Returns:
0 if there is no UDP port (default implementation do that)
Reimplemented in Omiscid::Connector, and Omiscid::UdpExchange.
Definition at line 12 of file ComTools.cpp.
Referenced by Omiscid::InOutputAttribute::GenerateRecordData(), and Omiscid::InOutputAttribute::GetUdpPort().
{
  return 0;
}
virtual int Omiscid::ComTools::GetListPeerId (SimpleList< unsigned int > & listId) [pure virtual]
List of Connected Peer
Parameters:
listId [in,out] add to this list the peer id connected to this tool of communication
Returns:
the number of id added to the list
Implemented in Omiscid::Connector, Omiscid::TcpClient, Omiscid::TcpServer, and Omiscid::UdpExchange.
Referenced by Omiscid::InOutputAttribute::GenerateLongDescription(), and Omiscid::InOutputAttribute::GetListPeerId().
virtual unsigned int Omiscid::ComTools::GetServiceId () const [pure virtual]
Access to the service Id.
Returns:
the service id
Implemented in Omiscid::Connector, Omiscid::TcpClient, Omiscid::TcpServer, Omiscid::UdpExchange, and Omiscid::ControlServer.
Referenced by Omiscid::InOutputAttribute::GenerateLongDescription(), and Omiscid::InOutputAttribute::GetPeerId().
virtual ComTools* Omiscid::ComTools::Cast () [pure virtual]
Cast in ComTools.
Returns:
the Comtool pointer on an object that derived Comtool
Implemented in Omiscid::Connector, Omiscid::TcpClient, Omiscid::TcpServer, and Omiscid::UdpExchange.
unsigned int ComTools::GeneratePeerId () [static]
Generation of service id.
The generated value is composed of 2 bytes created by using the current time and 2 other bytes obtained by using a random generator
Returns:
a value that can be used as service Id
Definition at line 26 of file ComTools.cpp.
Referenced by Omiscid::ControlServer::StartServer().
{
    unsigned int res;
    res = random();
    return (res & SERVICE_PEERID);
}
unsigned int ComTools::PeerIdFromString (const SimpleString & StringPeerId) [static]
transcode peer Id from strinf to unsigned int
Parameters:
StringPeerId [in] a simplestring containing a peerId
Returns:
the peerId as an unsigned int if StringPeerId was correct 0 otherwise
Definition at line 35 of file ComTools.cpp.
References Omiscid::SimpleString::GetStr(), and Omiscid::SimpleString::IsEmpty().
Referenced by Omiscid::ServiceProxy::GetPeerId(), and Omiscid::Service::GetPeerId().
{
    unsigned int res;
    if ( StringPeerId.IsEmpty() )
    {
        return 0;
    }
    if ( sscanf( StringPeerId.GetStr(), "%x", &res ) == 1 )
    {
        return res;
    }
    return 0;
}
SimpleString ComTools::PeerIdAsString (unsigned int PeerId) [static]
transcode peer Id from strinf to unsigned int
Parameters:
PeerId [in] an unsigned int containing a peerId
Returns:
the string représentation of the given peerId
Definition at line 51 of file ComTools.cpp.
Referenced by Omiscid::Message::ToString().
{
    TemporaryMemoryBuffer tmp(30);
    (*(char*)tmp) = '\0';
    sprintf( (char*)tmp, "%8.8x", PeerId );
    return SimpleString(tmp);
}
Member Data Documentation
const SimpleString ComTools::MagicUdp [static]
Gestion of Magic paquet.
Definition at line 85 of file ComTools.h.
Referenced by Omiscid::Connector::ConnectTo(), and Omiscid::Connector::Create().
The documentation for this class was generated from the following files:
Com/Com/ComTools.h
Com/ComTools.cpp