OMiSCID(aka O3MiSCID): Omiscid::Accumulator Class Reference
Omiscid::Accumulator Class Reference
[Examples of how to use OMiSCID.]
this class is used to managed an accumulator service. Is is also used to monitor incomming activity from intput connector of the service
#include <Accumulator.h>
Public Member Functions
virtual void MessageReceived (Service &TheService, const SimpleString LocalConnectorName, const Message &Msg)
Detailed Description
this class is used to managed an accumulator service. Is is also used to monitor incomming activity from intput connector of the service
Definition at line 28 of file Accumulator.h.
Member Function Documentation
void Accumulator::MessageReceived (Service & TheService, const SimpleString LocalConnectorName, const Message & Msg) [virtual]
Processes a received Omiscid message. As a given message could be processed by several others listeners, the message must not be modified by its processing.
Parameters:
TheService the service which received the message
LocalConnectorName the name of the connector that has received the message
Msg the message to process
Processes a received Omiscid message. As a given message could be processed by several others listeners, the message must not be modified by its processing.
Parameters:
service the service receiving the message
localConnectorName the name of the connector that has received the message
Msg the message to process
Reimplemented from Omiscid::ConnectorListener.
Definition at line 78 of file Accumulator.cpp.
References Omiscid::Message::GetBuffer(), Omiscid::SimpleString::GetLength(), Omiscid::SimpleString::GetStr(), Omiscid::Service::SendReplyToMessage(), Omiscid::Service::SetVariableValue(), and Omiscid::SmartLocker::Unlock().
{
    // Error management
    bool IsWrong = true;        // by default, the command is wrong
    SimpleString ErrorMessage = "Bad command.";
    // Used to read operand ?
    float fRightOperand = 0.0f;
    // A pointer to the command line and to the begining of the usufull data
    char * Command;
    int  StartUsefullInfo;
    // parse string to understand command
    // Start lock myself using my mutex (needed if multiple clients)
    SmartLocker SL_Locker(Locker);
    // Get the pointer to the data
    Command = Msg.GetBuffer();
    // skip data while there are spaces...
    for( StartUsefullInfo = 0; Command[StartUsefullInfo] != '\0'; StartUsefullInfo++ )
    {
        if ( Command[StartUsefullInfo] != ' ' &&  Command[StartUsefullInfo] != '\t' &&
             Command[StartUsefullInfo] != '\r' && Command[StartUsefullInfo] != '\n' )
        {
            break;
        }
    }
    // Is it a legal command ?
    if ( Command[StartUsefullInfo] == '-' || Command[StartUsefullInfo] == '+' ||
            Command[StartUsefullInfo] == '/' || Command[StartUsefullInfo] == '*' ||
            Command[StartUsefullInfo] == '=' )
    {
        // look for a float like 3.14 and then for
        if ( sscanf( &Command[StartUsefullInfo+1], "%f", &fRightOperand ) == 1 )
        {
            IsWrong = false;
        }
        // else IsWrong == true;
        // If it is ok,
        if ( IsWrong == false )
        {
            // run the command
            switch( Command[StartUsefullInfo] )
            {
                case '-':
                    // Compute new value
                    Accu -= fRightOperand;
                    break;
                case '+':
                    // Compute new value
                    Accu += fRightOperand;
                    break;
                case '*':
                    // Compute new value
                    Accu *= fRightOperand;
                    break;
                case '/':
                    if ( fRightOperand == 0.0f )
                    {
                        // we can not divide by 0
                        IsWrong = true;
                    }
                    else
                    {
                        // Compute new value
                        Accu /= fRightOperand;
                    }
                    break;
                default:         // here, Command[0] == '='
                    Accu = fRightOperand;
                    break;
            }
        }
    }
    if ( IsWrong == false )
    {
        // export the new Accu value, so the clients will receive notification
        TheService.SetVariableValue("Accu", Accu);
    }
    else
    {
        // Discard value and send back to the rigth "person" an error message in safe mode (TCP)
        TheService.SendReplyToMessage( (char*)ErrorMessage.GetStr(), (int)ErrorMessage.GetLength(), Msg, false );
    }
    // Unlock myself
    SL_Locker.Unlock();
}
The documentation for this class was generated from the following files:
Examples/Accumulator.h
Examples/Accumulator.cpp