OMiSCID(aka O3MiSCID): Omiscid::SimpleList< TYPE > Class Template Reference
Omiscid::SimpleList< TYPE > Class Template Reference
Template class to manage list of object.
#include <System/SimpleList.h>
Public Member Functions
SimpleList ()
Constructor.
virtual ~SimpleList ()
Destructor.
bool Add (const TYPE &Val)
Function to add an item at tail of the list.
bool AddHead (const TYPE &Val)
Function to add an item at head of the list.
bool AddTail (const TYPE &Val)
Function to add an item at tail of the list.
unsigned int GetNumberOfElements () const
Retrieve the current number of elements in the list.
TYPE & GetFirst () const
Get the first element of the list.
TYPE & GetHead () const
Get the first element of the list. Equivalent to GetFirst().
TYPE & GetLast () const
Get the last element of the list.
TYPE & GetTail () const
Get the first element of the list. Equivalent to GetFirst().
bool IsEmpty () const
Test if the list is empty or not.
bool IsNotEmpty () const
Test if the list is empty or not.
TYPE ExtractFirst ()
Extract the first element of the list.
bool Remove (const TYPE &Element)
Remove a specific element.
void Empty ()
Empty (so empty) the whole list.
First, Next, GetCurrent, AtEnd, NotAtEnd RemoveCurrent
void First ()
Set position to the first element.
bool Next ()
Set position to the next element.
bool AtEnd () const
Do we reach the end of the list.
bool NotAtEnd () const
Are we at the begining of the middle of the list ?
TYPE & GetCurrent () const
Get the current element of the list.
bool RemoveCurrent ()
Remove the current element.
Protected Member Functions
SimpleListElement< TYPE > * GetNewSimpleListElement () const
Obtain a new SimpleListElement object.
void ReleaseSimpleListElement (SimpleListElement< TYPE > *elt) const
Release a SimpleListElement object.
Detailed Description
template<typename TYPE>
class Omiscid::SimpleList< TYPE >
Template class to manage list of object.
This class provides methods to go through the list elements. It is possble to delete an element and then go to the next. It is possible to delete an element by giving its value.
Author:
Dominique Vaufreydaz
Definition at line 77 of file SimpleList.h.
Constructor & Destructor Documentation
template<typename TYPE> Omiscid::SimpleList< TYPE >::SimpleList () [inline]
Constructor.
Build an empty list
Definition at line 221 of file SimpleList.h.
{
    // There is nothing in the list
    NumberOfElements = 0;
    Head = NULL;
    Tail = NULL;
    // There is no position at all
    PreviousElement = NULL;
    CurrentElement = NULL;
    RemoveCurrentHasOccured = false;
}
Member Function Documentation
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::Add (const TYPE & Val) [inline]
Function to add an item at tail of the list.
Parameters:
Val [in] the item to add
Returns:
false if a new cell has not been allocated
Definition at line 242 of file SimpleList.h.
References Omiscid::SimpleListElement< TYPE >::ElementContainer, and Omiscid::SimpleList< TYPE >::GetNewSimpleListElement().
Referenced by Omiscid::ValueListener::AddListener(), Omiscid::SimpleList< TYPE >::AddTail(), Omiscid::UdpExchange::GetListPeerId(), Omiscid::TcpServer::GetListPeerId(), Omiscid::TcpClient::GetListPeerId(), and Omiscid::Connector::GetListPeerId().
{
    SimpleListElement<TYPE> * tmp = GetNewSimpleListElement();
    if ( tmp == NULL ) // Plus assez de memoire
        return false;
    tmp->ElementContainer = Val;
    if ( Head == NULL ) // La liste etait vide
    {
        Tail =  Head = tmp;
    }
    else
    {
        // Le nouveau devient le dernier
        Tail->NextElement = tmp;
        Tail = tmp;
        //if ( Head->NextElement == NULL )
        //{
        //      Head->NextElement = tmp;
        //}
    }
    // On incremente le nombre d'objet dans la liste
    NumberOfElements++;
    // Tout est ok
    return true;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::AddHead (const TYPE & Val) [inline]
Function to add an item at head of the list.
Parameters:
Val [in] the item to add
Returns:
false if a new cell has not been allocated
Definition at line 277 of file SimpleList.h.
References Omiscid::SimpleListElement< TYPE >::ElementContainer, Omiscid::SimpleList< TYPE >::GetNewSimpleListElement(), and Omiscid::SimpleListElement< TYPE >::NextElement.
{
    SimpleListElement<TYPE> * tmp = GetNewSimpleListElement();
    if ( tmp == NULL ) // Plus assez de memoire
        return false;
    tmp->ElementContainer = Val;
    if ( Head == NULL ) // La liste etait vide
    {
        Tail =  Head = tmp;
    }
    else
    {
        // Le nouveau devient le dernier
        // Head->NextElement = tmp;
        tmp->NextElement = Head;
        Head = tmp;
    }
    // On incremente le nombre d'objet dans la liste
    NumberOfElements++;
    // Tout est ok
    return true;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::AddTail (const TYPE & Val) [inline]
Function to add an item at tail of the list.
Parameters:
Val [in] the item to add
Returns:
false if a new cell has not been allocated
Definition at line 308 of file SimpleList.h.
References Omiscid::SimpleList< TYPE >::Add().
Referenced by Omiscid::Service::FindServices().
{
    // just call the add function
    return Add(Val);
}
template<typename TYPE> unsigned int Omiscid::SimpleList< TYPE >::GetNumberOfElements () const [inline]
Retrieve the current number of elements in the list.
Returns:
the current number of elements
Definition at line 315 of file SimpleList.h.
Referenced by Omiscid::ControlClient::EmptyInOutputAttributeList(), Omiscid::Service::FindServices(), Omiscid::InOutputAttribute::GenerateLongDescription(), Omiscid::Service::GetConnectorClientCount(), and Omiscid::ValueListener::HasListener().
{
    return NumberOfElements;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::Next () [inline]
Set position to the next element.
Returns:
false if there is not a next element : it is the end of the list.
Definition at line 331 of file SimpleList.h.
Referenced by Omiscid::ServiceProxyList::Empty(), Omiscid::ServiceFilterList::Empty(), Omiscid::Service::FindServices(), Omiscid::InOutputAttribute::GenerateLongDescription(), and Omiscid::SimpleList< TYPE >::Remove().
{
    // Ok, we do not have any other element
    if ( CurrentElement == NULL )
    {
        RemoveCurrentHasOccured = false;
        return false;
    }
    //seb
    if ( RemoveCurrentHasOccured == true )
    {
        RemoveCurrentHasOccured = false;
        // Previous and Current have already the good value
        return true;
    }
    // Here we can go forward in the list
    PreviousElement = CurrentElement;
    CurrentElement  = CurrentElement->NextElement;
    // Have we reach the end of the list ?
    if ( CurrentElement == NULL )
    {
        return false;
    }
    return true;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::AtEnd () const [inline]
Do we reach the end of the list.
Returns:
true is we have reached the end of the list
Definition at line 363 of file SimpleList.h.
{
    // Ok, we do not have any other element
    if ( CurrentElement == NULL )
        return true;
    return false;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::NotAtEnd () const [inline]
Are we at the begining of the middle of the list ?
Returns:
true is we don't have reached the end of the list
Definition at line 374 of file SimpleList.h.
Referenced by Omiscid::ServiceProxyList::Empty(), Omiscid::ServiceFilterList::Empty(), Omiscid::Service::FindServices(), Omiscid::InOutputAttribute::GenerateLongDescription(), and Omiscid::SimpleList< TYPE >::Remove().
{
    // Ok, we do not have any other element
    if ( CurrentElement != NULL )
        return true;
    return false;
}
template<typename TYPE> TYPE & Omiscid::SimpleList< TYPE >::GetCurrent () const [inline]
Get the current element of the list.
Returns:
the current element of the list
Exceptions:
SimpleListException raised if GetCurrent is called after a call to RemoveCurrent
Definition at line 385 of file SimpleList.h.
Referenced by Omiscid::ServiceProxyList::Empty(), Omiscid::ServiceFilterList::Empty(), Omiscid::Service::FindServices(), Omiscid::InOutputAttribute::GenerateLongDescription(), and Omiscid::SimpleList< TYPE >::Remove().
{
    if ( RemoveCurrentHasOccured == true )
    {
        throw SimpleListException("SimpleList<TYPE>::GetCurrent : Forbidden after a call to RemoveCurrent");
    }
#ifdef DEBUG
    if ( CurrentElement== NULL )
    {
        OmiscidError( "Warning :  In SimpleList<TYPE>::GetCurrent() CurrentElement == NULL\n" );
    }
#endif
    return CurrentElement->ElementContainer;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::RemoveCurrent () [inline]
Remove the current element.
Returns:
false if called on an empty list
Exceptions:
SimpleListException raised if this method has already been called on the same element
Definition at line 404 of file SimpleList.h.
References Omiscid::SimpleListElement< TYPE >::NextElement, and Omiscid::SimpleList< TYPE >::ReleaseSimpleListElement().
Referenced by Omiscid::ServiceProxyList::Empty(), Omiscid::ServiceFilterList::Empty(), and Omiscid::SimpleList< TYPE >::Remove().
{
    if ( RemoveCurrentHasOccured == true )
    {
        throw SimpleListException("SimpleList<TYPE>::RemoveCurrent : Forbidden after a previous call to RemoveCurrent");
    }
    RemoveCurrentHasOccured = true;
    SimpleListElement<TYPE> * tmp = CurrentElement;
    if ( tmp == NULL )
    {
        // We must call at least First on a non empty list
        return false;
    }
    // Here we have a current element...
    // Are we at the begining of the SimpleList ?
    if ( Head == tmp )
    {
        // Yes, wa are !
        Head = tmp->NextElement;
        // PreviousElement remains the same :
        // PreviousElement == NULL
        // The new current element if the next in the list, so the head
        CurrentElement = Head;
    }
    else
    {
        // We are not at the begining of the list
        // Here we can remove directly the element within the list
        tmp = CurrentElement;
        PreviousElement->NextElement = tmp->NextElement;
        CurrentElement = tmp->NextElement;
    }
    // Was the element the last item of the list ?
    if ( Tail == tmp )
    {
        // We have remove the last item of the list
        Tail = PreviousElement;
    }
    // Delete the old current element
    ReleaseSimpleListElement(tmp);
    // Change the element count
    NumberOfElements--;
    return true;
}
template<typename TYPE> TYPE & Omiscid::SimpleList< TYPE >::GetFirst () const [inline]
Get the first element of the list.
Returns:
the first element of the list
Exceptions:
SimpleListException raised if the list is empty
Definition at line 487 of file SimpleList.h.
{
    if ( Head == NULL )
    {
        throw SimpleException( "Could not call GetFirst() or GetHead() on a empty list" );
    }
    return Head->ElementContainer;
}
template<typename TYPE> TYPE& Omiscid::SimpleList< TYPE >::GetHead () const [inline]
Get the first element of the list. Equivalent to GetFirst().
Returns:
the first element of the list
Exceptions:
SimpleListException raised if the list is empty
Definition at line 155 of file SimpleList.h.
{ return GetFirst(); };
template<typename TYPE> TYPE & Omiscid::SimpleList< TYPE >::GetLast () const [inline]
Get the last element of the list.
Returns:
the last element of the list
Exceptions:
SimpleListException raised if the list is empty
Definition at line 498 of file SimpleList.h.
{
    if ( Tail == NULL )
    {
        throw SimpleException( "Could not call GetLast() or GetTail() on a empty list" );
    }
    return Tail->ElementContainer;
}
template<typename TYPE> TYPE& Omiscid::SimpleList< TYPE >::GetTail () const [inline]
Get the first element of the list. Equivalent to GetFirst().
Returns:
the first element of the list
Exceptions:
SimpleListException raised if the list is empty
Definition at line 167 of file SimpleList.h.
{ return GetLast(); };
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::IsEmpty () const [inline]
Test if the list is empty or not.
Returns:
true if the list is empty
Definition at line 509 of file SimpleList.h.
Referenced by Omiscid::SimpleList< TYPE >::ExtractFirst().
{
    return Head == NULL;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::IsNotEmpty () const [inline]
Test if the list is empty or not.
Returns:
true if the list is not empty
Definition at line 515 of file SimpleList.h.
Referenced by Omiscid::Service::CloseAllConnections().
{
    return Head != NULL;
}
template<typename TYPE> TYPE Omiscid::SimpleList< TYPE >::ExtractFirst () [inline]
Extract the first element of the list.
Return the first element in the list and remove it from the list
Returns:
the first element in the list
Exceptions:
SimpleListException raised if the list is empty
Definition at line 521 of file SimpleList.h.
References Omiscid::SimpleListElement< TYPE >::ElementContainer, Omiscid::SimpleList< TYPE >::IsEmpty(), Omiscid::SimpleListElement< TYPE >::NextElement, and Omiscid::SimpleList< TYPE >::ReleaseSimpleListElement().
Referenced by Omiscid::Service::CloseAllConnections(), and Omiscid::ControlClient::EmptyInOutputAttributeList().
{
    if ( IsEmpty() == true )
    {
        throw SimpleListException("SimpleList<TYPE>::ExtractFirst : Forbidden when the list is empty");
    }
    SimpleListElement<TYPE>* elt = Head;
    if(Head == Tail)
    {
        Head = NULL; Tail = NULL;
    }
    else
    {
        Head = elt->NextElement;
    }
    NumberOfElements--;
    TYPE tmp = elt->ElementContainer;
    ReleaseSimpleListElement(elt);
    return tmp;
}
template<typename TYPE> bool Omiscid::SimpleList< TYPE >::Remove (const TYPE & Element) [inline]
Remove a specific element.
Parameters:
Element [in] the element to remove
Returns:
false if the element to delete has not been found in the list
Definition at line 459 of file SimpleList.h.
References Omiscid::SimpleList< TYPE >::First(), Omiscid::SimpleList< TYPE >::GetCurrent(), Omiscid::SimpleList< TYPE >::Next(), Omiscid::SimpleList< TYPE >::NotAtEnd(), and Omiscid::SimpleList< TYPE >::RemoveCurrent().
Referenced by Omiscid::ValueListener::RemoveListener().
{
    for( First(); NotAtEnd(); Next() )
    {
        if ( GetCurrent() == Element )
        {
            RemoveCurrent();
            return true;
        }
    }
    return false;
}
template<typename TYPE> SimpleListElement< TYPE > * Omiscid::SimpleList< TYPE >::GetNewSimpleListElement () const [inline, protected]
Obtain a new SimpleListElement object.
Create a new instance of SimpleListElement object
Reimplemented in Omiscid::SimpleRecycleList< TYPE >.
Definition at line 545 of file SimpleList.h.
Referenced by Omiscid::SimpleList< TYPE >::Add(), and Omiscid::SimpleList< TYPE >::AddHead().
{
    return new OMISCID_TLM SimpleListElement<TYPE>;
}
template<typename TYPE> void Omiscid::SimpleList< TYPE >::ReleaseSimpleListElement (SimpleListElement< TYPE > * elt) const [inline, protected]
Release a SimpleListElement object.
Delete the SimpleListElement object
Parameters:
elt the element to release
Reimplemented in Omiscid::SimpleRecycleList< TYPE >.
Definition at line 551 of file SimpleList.h.
Referenced by Omiscid::SimpleList< TYPE >::Empty(), Omiscid::SimpleList< TYPE >::ExtractFirst(), and Omiscid::SimpleList< TYPE >::RemoveCurrent().
{
    delete elt;
}
The documentation for this class was generated from the following file:
System/System/SimpleList.h