OMiSCID(aka O3MiSCID): Omiscid::VariableAttribute Class Reference
Omiscid::VariableAttribute Class Reference
Class to manage the variable of a service.
#include <ServiceControl/VariableAttribute.h>
Write Accessors
void SetType (const SimpleString str)
void SetDefaultValue (const SimpleString str)
void SetAccess (VariableAccessType)
void SetAccessConstant ()
void SetAccessRead ()
void SetAccessReadWrite ()
void SetAccessReadWriteBeforeInit ()
bool IsInitialised ()
void SetValue (const SimpleString value_str)
Set the value and signal that the value has changed.
void SetValueFromControl (const SimpleString value_str)
Set the value and signal that the value has changed.
bool CanBeModifiedFromInside (ControlServerStatus status) const
define if a variable can be modified according to its kid of access.
bool CanBeModifiedFromOutside (ControlServerStatus status) const
define if a variable can be modified according to its kid of access.
static const SimpleString & AccessToStr (VariableAccessType accesskind)
Associate a SimpleString to a kind of access.
Public Member Functions
virtual ~VariableAttribute ()
Destructor.
void Display ()
Add to atring a XML message containing the variable and its value.
bool AddListener (VariableAttributeListener *ListenerToAdd)
Add a listener to this variable.
bool RemoveListener (VariableAttributeListener *ListenerToAdd)
remove a listener to this variable.
unsigned int GetNumberOfListeners ()
remove a listener to this variable.
void ExtractDataFromXml (xmlNodePtr node)
Extract data from a XML node.
Read Accessors
SimpleString & GetType ()
SimpleString & GetValue ()
SimpleString & GetDefaultValue ()
VariableAccessType GetAccess ()
XML Generation
void GenerateShortDescription (SimpleString &str)
Add to a SimpleString a short XML description of the variable.
void GenerateLongDescription (SimpleString &str)
Add to a SimpleString a long XML description of the variable.
Static Public Attributes
static const SimpleString VariableStr
to parse/generate XML data.
Protected Attributes
SimpleString type
SimpleString defaultValue
VariableAccessType access
SimpleString valueStr
Static Protected Attributes
static const SimpleString AccessConstantStr
static const SimpleString AccessReadStr
static const SimpleString AccessReadWriteStr
Detailed Description
Class to manage the variable of a service.
Contains the description of the variable, the value as a string representation, the access restriction (read-only, read-write, read-write before init) for external users. The users must change the value of this symbolic variable when the asscoiated variable in its program change. When the value change, a callback can be called : used by ControlServer to enable users to subscribe to variable modification.
Definition at line 34 of file VariableAttribute.h.
Member Function Documentation
void VariableAttribute::SetValue (const SimpleString value_str)
Set the value and signal that the value has changed.
Parameters:
value_str [in] the new string representaion of the value
Definition at line 102 of file VariableAttribute.cpp.
References valueStr.
Referenced by Omiscid::ControlClient::CtrlEventProcess(), ExtractDataFromXml(), Omiscid::Service::SetVariableValue(), and Omiscid::ControlServer::VariableChange().
{
    if ( valueStr == value_str )
    {
        // This appends when we remotely ask for a change
        // we were already notified that the value was changed
        // nothing to do, neither validate change nor change value
        return;
    }
    // ask to all listener if we can change the value
    SmartLocker SL_Listeners(Listeners);
    for( Listeners.First(); Listeners.NotAtEnd(); Listeners.Next() )
    {
        VariableAttributeListener * pListener = Listeners.GetCurrent();
        if ( pListener->IsValid( this, value_str ) == false )
        {
            // OmiscidError( "VariableAttribute::SetValue: someone disagree on variable change\n");
            return;
        }
    }
    // Ok, change my value
    valueStr = value_str;
    // Initialised !!
    Initialised = true;
    // Ok the value has change, send information back to people
    for( Listeners.First(); Listeners.NotAtEnd(); Listeners.Next() )
    {
        Listeners.GetCurrent()->VariableChanged( this );
    }
}
void VariableAttribute::SetValueFromControl (const SimpleString value_str)
Set the value and signal that the value has changed.
Parameters:
value_str [in] the new string representaion of the value
Definition at line 138 of file VariableAttribute.cpp.
References valueStr.
Referenced by Omiscid::StringVariableAttribute::SetValue(), Omiscid::IntVariableAttribute::SetValue(), and Omiscid::Service::SetVariableValue().
{
    if ( valueStr == value_str )
    {
        // This appends when we ask for a change without validation
        // and e ask for several time to change to the same value
        // we were already notified that the value was changed
        // nothing to do, neither validate change nor change value
        return;
    }
    // Ok, change my value
    valueStr = value_str;
    // Initialised !!
    Initialised = true;
    // Ok the value has change, send information back to people
    SmartLocker SL_Listeners(Listeners);
    for( Listeners.First(); Listeners.NotAtEnd(); Listeners.Next() )
    {
        Listeners.GetCurrent()->VariableChanged( this );
    }
}
bool VariableAttribute::CanBeModifiedFromInside (ControlServerStatus status) const
define if a variable can be modified according to its kid of access.
Parameters:
status [in] the current status of the ControlServer who manage the VariableAttribute object.
Returns:
true if access is 'read-write' or 'read-write only before init' and the status is different of STATUS_RUNNING (: 2).
Definition at line 289 of file VariableAttribute.cpp.
References access.
{
    if ( access == ConstantAccess && status == STATUS_RUNNING )
    {
        return false;
    }
    return true;
}
bool VariableAttribute::CanBeModifiedFromOutside (ControlServerStatus status) const
define if a variable can be modified according to its kid of access.
Parameters:
status [in] the current status of the ControlServer who manage the VariableAttribute object.
Returns:
true if access is 'read-write' or 'read-write only before init' and the status is different of STATUS_RUNNING (: 2).
Definition at line 298 of file VariableAttribute.cpp.
References access.
{
    return (access == ReadWriteAccess || (access == ConstantAccess && status != STATUS_RUNNING));
}
const SimpleString & VariableAttribute::AccessToStr (VariableAccessType accesskind) [static]
Associate a SimpleString to a kind of access.
Parameters:
accesskind [in] access kind that we want to change in SimpleString
Returns:
the associated SimpleString
Definition at line 42 of file VariableAttribute.cpp.
References AccessConstantStr, AccessReadStr, and AccessReadWriteStr.
Referenced by Display(), GenerateLongDescription(), and Omiscid::Service::GetVariableAccessTypeType().
{
    if(a == ConstantAccess) return AccessConstantStr;
    if(a == ReadAccess) return AccessReadStr;
    return AccessReadWriteStr;
}
void VariableAttribute::GenerateShortDescription (SimpleString & str) [virtual]
Add to a SimpleString a short XML description of the variable.
The description has the form : <variable name="name of the variable">
Parameters:
str [in, out] the SimpleString where add the description.
Implements Omiscid::Attribute.
Definition at line 54 of file VariableAttribute.cpp.
References Omiscid::Attribute::GenerateHeaderDescription(), and VariableStr.
{
    GenerateHeaderDescription(VariableStr, GetName(), str);
}
void VariableAttribute::GenerateLongDescription (SimpleString & str) [virtual]
Add to a SimpleString a long XML description of the variable.
The description has the form :
    <variable name="name of the variable">
     <value>the value</value>
     <default>the default value</value>
     <access>the kind of access</access>
     <type>the type of the variable</type>
     <description>the description</description> (if there is a description)
     <formatDescription>the description of the format </formatDescription> (if there is a description for the format)
    </variable>
Parameters:
str [in, out] the SimpleString where add the description.
Implements Omiscid::Attribute.
Definition at line 59 of file VariableAttribute.cpp.
References access, AccessToStr(), Omiscid::Attribute::AddTagDescriptionToStr(), defaultValue, Omiscid::Attribute::GenerateHeaderDescription(), Omiscid::Attribute::PutAValueInCData(), type, and VariableStr.
{
    GenerateHeaderDescription(VariableStr, GetName(), str, false);
    str += "<value>";
    PutAValueInCData(GetValue(), str);
    str += "</value>";
    if(defaultValue != "")
    {
        str += "<default>";
        PutAValueInCData(defaultValue, str);
        str += "</default>";
    }
    str = str + "<access>"+AccessToStr(access)+"</access>";
    str = str + "<type>"+type+"</type>";
    AddTagDescriptionToStr(str);
    str = str + "</variable>";
}
void VariableAttribute::Display ()
Add to atring a XML message containing the variable and its value.
It has the form :
    <variable name="name of the variable">
     <value> the value of the variable </value>
    </variable>
Parameters:
str [in, out] the SimpleString where add the description. Display on standard output the data about the variable. The display is a set of line as 'name attribute : value'
Definition at line 92 of file VariableAttribute.cpp.
References access, AccessToStr(), defaultValue, Omiscid::SimpleString::GetStr(), type, and valueStr.
{
    printf("Name : %s\n", GetName().GetStr() );
    printf("Type : %s\n", type.GetStr());
    printf("Default Value : %s\n", defaultValue.GetStr());
    printf("Last Value : %s\n", valueStr.GetStr());
    printf("Access : %s\n", AccessToStr(access).GetStr());
}
bool VariableAttribute::AddListener (VariableAttributeListener * ListenerToAdd)
Add a listener to this variable.
Definition at line 306 of file VariableAttribute.cpp.
Referenced by Omiscid::Service::AddLocalVariableListener(), Omiscid::ServiceProxy::AddRemoteVariableChangeListener(), and Omiscid::ControlServer::AddVariable().
{
    if ( ListenerToAdd == NULL )
    {
        return false;
    }
    SmartLocker SL_Listeners(Listeners);
    // look if it is already there..
    for( Listeners.First(); Listeners.NotAtEnd(); Listeners.Next() )
    {
        if ( Listeners.GetCurrent() == ListenerToAdd )
        {
            return false;
        }
    }
    // add it
    Listeners.Add( ListenerToAdd );
    return true;
}
bool VariableAttribute::RemoveListener (VariableAttributeListener * ListenerToAdd)
remove a listener to this variable.
Definition at line 333 of file VariableAttribute.cpp.
Referenced by Omiscid::Service::RemoveLocalVariableListener(), and Omiscid::ServiceProxy::RemoveRemoteVariableChangeListener().
{
    bool ret;
    if ( ListenerToAdd == NULL )
    {
        return false;
    }
    // Remove it if any
    SmartLocker SL_Listeners(Listeners);
    ret = Listeners.Remove(ListenerToAdd);
    return ret;
}
unsigned int VariableAttribute::GetNumberOfListeners ()
remove a listener to this variable.
Definition at line 350 of file VariableAttribute.cpp.
Referenced by Omiscid::ServiceProxy::AddRemoteVariableChangeListener(), and Omiscid::ServiceProxy::RemoveRemoteVariableChangeListener().
{
    unsigned int ret;
    SmartLocker SL_Listeners(Listeners);
    ret = Listeners.GetNumberOfElements();
    return ret;
}
void VariableAttribute::ExtractDataFromXml (xmlNodePtr node)
Extract data from a XML node.
Extract attribute 'name', and child node.
Parameters:
node A node of service description with the tag VariableAttribute::VariableStr
Definition at line 164 of file VariableAttribute.cpp.
References AccessConstantStr, AccessReadStr, AccessReadWriteStr, Omiscid::XMLMessage::FindAttribute(), Omiscid::SimpleString::GetStr(), and SetValue().
{
    xmlAttrPtr attr_name = XMLMessage::FindAttribute("name", node);
    if(attr_name)
    {
        SetName(SimpleString((const char*)attr_name->children->content));
    }
    //child value
    SimpleString tmp_value("");
    xmlNodePtr cur_node = node->children;
    for(; cur_node; cur_node = cur_node->next)
    {
        if (cur_node->type == XML_ELEMENT_NODE)
        {
            SimpleString cur_name = (const char*)cur_node->name;
            if( cur_name == "description" )
            {
                SetDescription(XMLMessage::ExtractTextContent(cur_node->children));
            }
            else if( cur_name == "formatDescription" )
            {
                SetFormatDescription(XMLMessage::ExtractTextContent(cur_node->children));
            }
            else if ( cur_name == "value" )
            {
                tmp_value = XMLMessage::ExtractTextContent(cur_node->children);
                //vattr->SetValue((const char*)cur_node->children->content);
            }
            else if ( cur_name == "default" )
            {
                SetDefaultValue(XMLMessage::ExtractTextContent(cur_node->children));
            }
            else if ( cur_name == "type" )
            {
                SetType(XMLMessage::ExtractTextContent(cur_node->children).GetStr());
            }
            else if ( cur_name == "access" )
            {
                SimpleString content = XMLMessage::ExtractTextContent(cur_node->children);
                if( content == AccessReadStr )
                {
                    SetAccessRead();
                }
                else if( content == AccessReadWriteStr )
                {
                    SetAccessReadWrite();
                }
                else if( content == AccessConstantStr )
                {
                    SetAccessConstant();
                }
                else
                {
                    OmiscidError( "Unknow Access kind : %s\n", cur_node->children->content );
                }
            }
            else OmiscidError( "Unwaited Tag : %s\n", cur_name.GetStr() );
        }
    }
    SetValue(tmp_value);
}
Member Data Documentation
const SimpleString VariableAttribute::VariableStr [static]
to parse/generate XML data.
SimpleString representation for 'variable' (used in XML description)
Definition at line 172 of file VariableAttribute.h.
Referenced by Omiscid::ControlClient::CtrlEventProcess(), GenerateLongDescription(), GenerateShortDescription(), and Omiscid::ControlServer::ProcessAMessage().
SimpleString Omiscid::VariableAttribute::type [protected]
type of the variable
Definition at line 175 of file VariableAttribute.h.
Referenced by Display(), and GenerateLongDescription().
SimpleString Omiscid::VariableAttribute::defaultValue [protected]
default value
Definition at line 176 of file VariableAttribute.h.
Referenced by Display(), and GenerateLongDescription().
VariableAccessType Omiscid::VariableAttribute::access [protected]
kind of access.
Definition at line 177 of file VariableAttribute.h.
Referenced by CanBeModifiedFromInside(), CanBeModifiedFromOutside(), Display(), and GenerateLongDescription().
SimpleString Omiscid::VariableAttribute::valueStr [protected]
SimpleString representation of the value of the variable
Definition at line 178 of file VariableAttribute.h.
Referenced by Display(), SetValue(), and SetValueFromControl().
const SimpleString VariableAttribute::AccessConstantStr [static, protected]
SimpleString representation for 'constant' access (used in XML description)
Definition at line 183 of file VariableAttribute.h.
Referenced by AccessToStr(), and ExtractDataFromXml().
const SimpleString VariableAttribute::AccessReadStr [static, protected]
SimpleString representation for 'read' access (used in XML description)
Definition at line 188 of file VariableAttribute.h.
Referenced by AccessToStr(), and ExtractDataFromXml().
const SimpleString VariableAttribute::AccessReadWriteStr [static, protected]
SimpleString representation for 'read-write' access (used in XML description)
Definition at line 193 of file VariableAttribute.h.
Referenced by AccessToStr(), and ExtractDataFromXml().
The documentation for this class was generated from the following files:
ServiceControl/ServiceControl/VariableAttribute.h
ServiceControl/VariableAttribute.cpp