OMiSCID(aka O3MiSCID): Omiscid::MsgManager Class Reference
Omiscid::MsgManager Class Reference
Message Storing and Processing.
#include <Com/MsgManager.h>
Public Member Functions
MsgManager (unsigned int max=0)
Constructor.
virtual ~MsgManager ()
Destructor.
void PushMessage (Message *msg)
Adds a message in the list. Called by CumulMessage.
unsigned int GetNbMessages ()
Current number of message.
bool HasMessages ()
test the presence of message in the list
Message * GetMessage ()
void ClearMessages ()
Delete all the stored message delete all the messages in the list.
int ProcessMessages ()
Process each message in the list.
void Receive (MsgSocket &ConnectionPoint, MsgSocketCallBackData &ptr)
Callback for the reception of message by MsgSocket object.
bool WaitForMessage (unsigned long timer=0)
Set the callback method of a MsgSocket object.
Protected Member Functions
virtual void ProcessAMessage (Message *msg)
Processing a message.
Detailed Description
Message Storing and Processing.
An object MsgManager is used to accumulate messages. The object Message buffer must be deleted by the user after a call to GetMessage. The messages can be processed with ProcessMessages. This function calls the virtual method ProcessAMessage on each Message, and then delete the message. The destructor destroy the no read message.
Author:
Sebastien Pesnel
Definition at line 37 of file MsgManager.h.
Constructor & Destructor Documentation
MsgManager::MsgManager (unsigned int max = 0)
Constructor.
Parameters:
max [in] max of stored message, before deleting the older. (0 for unlimited)
Definition at line 10 of file MsgManager.cpp.
: maxMessage(max)
{}
MsgManager::~MsgManager () [virtual]
Destructor.
Deletes the no read messages.
Definition at line 14 of file MsgManager.cpp.
References ClearMessages().
{
    ClearMessages();
}
Member Function Documentation
void MsgManager::PushMessage (Message * msg)
Adds a message in the list. Called by CumulMessage.
Parameters:
msg [in] the message to add.
See also:
CumulMessage.
Definition at line 19 of file MsgManager.cpp.
Referenced by Receive().
{
    SmartLocker SL_listMsg(listMsg);
    if(maxMessage && listMsg.GetNumberOfElements() == maxMessage)
    {
        listMsg.First();
        Message* m = listMsg.GetCurrent();
        listMsg.RemoveCurrent();
        delete m;
    }
    listMsg.Add(msg);
    event.Signal();
    event.Reset();
}
unsigned int MsgManager::GetNbMessages ()
Current number of message.
Returns:
the number of message in the list
Definition at line 35 of file MsgManager.cpp.
Referenced by HasMessages().
{
    SmartLocker SL_listMsg(listMsg);
    int nb =listMsg.GetNumberOfElements();
    return nb;
}
bool MsgManager::HasMessages ()
test the presence of message in the list
Returns:
true if there are messages in the list
Definition at line 135 of file MsgManager.cpp.
References GetNbMessages().
Referenced by WaitForMessage().
{
    return GetNbMessages() != 0;
}
Message * MsgManager::GetMessage ()
Remove the first message object in the list and return it.
Returns:
a message object or NULL if there is no available message
Definition at line 44 of file MsgManager.cpp.
{
    Message* msg = NULL;
    SmartLocker SL_listMsg(listMsg);
    if(listMsg.GetNumberOfElements())
    {
        listMsg.First();
        msg = listMsg.GetCurrent();
        listMsg.RemoveCurrent();
    }
    return msg;
}
int MsgManager::ProcessMessages ()
Process each message in the list.
Call for each message the virtual method ProcessAMessage and then delete the buffer.
Returns:
the number of processed messages.
Definition at line 73 of file MsgManager.cpp.
References Omiscid::SimpleException::err, Omiscid::SimpleException::GetExceptionType(), Omiscid::SimpleString::GetStr(), Omiscid::SimpleException::msg, and ProcessAMessage().
{
    Message* msg;
    SmartLocker SL_listMsg(listMsg);
    int nb = 0;
    for(listMsg.First(); listMsg.NotAtEnd(); listMsg.Next() )
    {
        msg = listMsg.GetCurrent();
        listMsg.RemoveCurrent();
        try
        {
            ProcessAMessage(msg);
        }
        catch(SimpleException &e) // Catch every Omiscid exception within this, can break the whole system
        {
            OmiscidTrace( "'%s' exception occurs while processing message : %s (%d)\n", e.GetExceptionType().GetStr(), e.msg.GetStr(), e.err );
        }
        delete msg;
        nb++;
    }
    return nb;
}
void MsgManager::Receive (MsgSocket & ConnectionPoint, MsgSocketCallBackData & ptr) [virtual]
Callback for the reception of message by MsgSocket object.
use the user data pointer of the MsgSocketCallBackData object. The user data points on a MsgManager object. This method create a message and add it to the MsgManager object (by calling PushMessage).
Parameters:
ptr pointer on a MsgSocketCallBackData object
See also:
MsgSocketCallBackData
Implements Omiscid::MsgSocketCallbackObject.
Definition at line 105 of file MsgManager.cpp.
References Omiscid::Message::buffer, Omiscid::Message::GetMsgId(), Omiscid::Message::GetOrigine(), Omiscid::Message::GetPeerId(), Omiscid::Message::len, Omiscid::Message::mid, Omiscid::MsgSocketCallBackData::Msg, Omiscid::Message::origine, Omiscid::Message::pid, and PushMessage().
{
    Message* msg = new OMISCID_TLM Message(cd.Msg.len + 1);
    msg->len = cd.Msg.len;
    memcpy(msg->buffer, cd.Msg.buffer, cd.Msg.len + 1);
    msg->origine = cd.Msg.GetOrigine();
    msg->pid = cd.Msg.GetPeerId();
    msg->mid = cd.Msg.GetMsgId();
    PushMessage(msg);
}
bool MsgManager::WaitForMessage (unsigned long timer = 0)
Set the callback method of a MsgSocket object.
call the method SetCallBackOnRecv of the tools of communication (derived from MsgSocket) with the function CumulMessage and this object MsgManager
Parameters:
ms communication tool who will provide the message Wait for new message Block until there is a message in the list or timer is expired (except if timer equals 0).
[in] timer timeout in milliseconds.
Returns:
false if timer is expired or true if a message is in the list.
Definition at line 122 of file MsgManager.cpp.
References HasMessages().
{
    event.Reset();
    if(!HasMessages())
    {
        if(timer)
            return event.Wait(timer);
        else
            return event.Wait();
    }
    return true;
}
void MsgManager::ProcessAMessage (Message * msg) [protected, virtual]
Processing a message.
Define how process a message. Can be reimplemented to define another way to process message. ProcessMessages call this methods on each stored message.
here : display the message
Parameters:
[in] msg the message to process.
Definition at line 99 of file MsgManager.cpp.
References Omiscid::Message::GetMsgId(), and Omiscid::Message::GetPeerId().
Referenced by ProcessMessages().
{
    OmiscidTrace( "processAMessage (pid= %u, mid=%u)\n", msg->GetPeerId(), msg->GetMsgId());
}
The documentation for this class was generated from the following files:
Com/Com/MsgManager.h
Com/MsgManager.cpp