OMiSCID(aka O3MiSCID): Omiscid::Message Class Reference
Omiscid::Message Class Reference
[Layer 1 : Omiscid multiplateform Communication layer., User friendly high-level API for Omiscid]
Group Data about a received message.
#include <Com/Message.h>
Inherited by Omiscid::ConnectorListener::ExtendedMessageForService.
Public Member Functions
Message (int size=0)
Constructor.
virtual ~Message ()
Destructor.
SimpleString ToString (unsigned int MaxBufferLenToWrite=30) const
ToString.
Access to information via functions
char * GetBuffer () const
int GetLength () const
MessageOrigine GetOrigine () const
unsigned int GetPeerId () const
unsigned int GetMsgId () const
Protected Attributes
char * realBuffer
Direct access to data, for members and friens classes MsgSocket and MsgManager
char * buffer
int len
MessageOrigine origine
unsigned int pid
unsigned int mid
Friends
class MsgSocket
The MsgSocket class can acces directly to private members of this class.
class MsgManager
The MsgManager class can acces directly to private members of this class.
Detailed Description
Group Data about a received message.
contain the data about a received message :
the length of the message
the message
a pointer on the source of the message
the PerrId of the sender
the id for the message
Definition at line 30 of file Message.h.
Constructor & Destructor Documentation
Message::Message (int size = 0)
Constructor.
Allocates a size+1 bytes buffer to contains the data of a message (the added byte is kept before the message, so buffer is a pointer on a buffer of length 'size').
Parameters:
size [in] the size of the buffer containing the message if size = 0 (default), no allocation are done. Usefull for pointer container.
Definition at line 8 of file Message.cpp.
References buffer, len, and realBuffer.
{
  realBuffer = NULL;
  buffer = NULL;
  len = 0;
  origine = UnknownOrigine;
  OriginalSize = size;
  if ( OriginalSize > 0 )
  {
    realBuffer = new OMISCID_TLM char[size+1];
    buffer = realBuffer+1;
  }
}
Message::~Message () [virtual]
Destructor.
Free the buffer if previsously allocated.
Definition at line 24 of file Message.cpp.
References realBuffer.
{
    if ( OriginalSize != 0 )
    {
        delete [] realBuffer;
    }
}
Member Function Documentation
char * Message::GetBuffer () const
A Pointer on the beginning of message data
Definition at line 32 of file Message.cpp.
References buffer.
Referenced by Omiscid::Accumulator::MessageReceived(), and Omiscid::XMLMessage::XMLMessage().
{
    return buffer;
}
int Message::GetLength () const
The message length
Definition at line 37 of file Message.cpp.
References len.
Referenced by Omiscid::XMLMessage::XMLMessage().
{
    return len;
}
MessageOrigine Message::GetOrigine () const
The origine of the Message (udp, tcp, shared memory, maybe other (??) in future work)
Definition at line 42 of file Message.cpp.
Referenced by Omiscid::MsgManager::Receive(), and Omiscid::XMLMessage::XMLMessage().
{
    return origine;
}
unsigned int Message::GetPeerId () const
The PeerId who send this message
Definition at line 47 of file Message.cpp.
References pid.
Referenced by Omiscid::MsgManager::ProcessAMessage(), Omiscid::MsgManager::Receive(), Omiscid::Service::SendReplyToMessage(), and Omiscid::XMLMessage::XMLMessage().
{
    return pid;
}
unsigned int Message::GetMsgId () const
The unique message id comming from a Peer
Definition at line 52 of file Message.cpp.
References mid.
Referenced by Omiscid::MsgManager::ProcessAMessage(), Omiscid::MsgManager::Receive(), and Omiscid::XMLMessage::XMLMessage().
{
    return mid;
}
SimpleString Message::ToString (unsigned int MaxBufferLenToWrite = 30) const
ToString.
Generate a description of the message
Definition at line 61 of file Message.cpp.
References buffer, Omiscid::SimpleString::GetStr(), len, mid, Omiscid::ComTools::PeerIdAsString(), and pid.
{
    TemporaryMemoryBuffer TmpBuffer(300);
    SimpleString TmpMessage = "Message ";
    TmpMessage   += mid;
    TmpMessage   += " (";
    if ( len < 1024 )   // less that 1 KB
    {
        TmpMessage += len;
        TmpMessage += "bytes)";
    }
    else if ( len >= 1024 && len < (1024*1024) ) // from 1KB to 1Mo
    {
        // compute size in ko
        *((char*)TmpBuffer) = '\0';     // Empty string
        snprintf( (char*)TmpBuffer, TmpBuffer.GetLength(), "%.2f Kbytes)", ((float)len)/1024.f );
        TmpMessage += (char*)TmpBuffer;
    }
    else        // over 1 Mo
    {
        // compute size in ko
        *((char*)TmpBuffer) = '\0';     // Empty string
        snprintf( (char*)TmpBuffer, TmpBuffer.GetLength(), "%.2f Mbytes)", ((float)len)/(1024.0f*1024.0f) );
        TmpMessage += (char*)TmpBuffer;
    }
    if ( origine == FromUDP )
    {
        TmpMessage += " on UDP from ";
    }
    else
    {
        TmpMessage += " on TCP from ";
    }
    TmpMessage += ComTools::PeerIdAsString(pid);
    if ( MaxBufferLenToWrite == 0 || MaxBufferLenToWrite > 256 )
    {
        TmpMessage += "\n";
    }
    else
    {
        SimpleString Format = ":\n%";
        Format += MaxBufferLenToWrite;
        Format += ".";
        Format += MaxBufferLenToWrite;
        Format += "s\n";
        *((char*)TmpBuffer) = '\0';     // Empty string
        snprintf( (char*)TmpBuffer, TmpBuffer.GetLength(), (const char*)Format.GetStr(), buffer );
        TmpMessage += (char*)TmpBuffer;
    }
    return TmpMessage;
}
Member Data Documentation
char* Omiscid::Message::buffer [protected]
The message address
Definition at line 77 of file Message.h.
Referenced by GetBuffer(), Message(), Omiscid::MsgManager::Receive(), Omiscid::MsgSocket::SetCallbackSyncLink(), and ToString().
int Omiscid::Message::len [protected]
The message Length
Definition at line 78 of file Message.h.
Referenced by GetLength(), Message(), Omiscid::MsgManager::Receive(), Omiscid::MsgSocket::SetCallbackSyncLink(), and ToString().
unsigned int Omiscid::Message::pid [protected]
peer id
Definition at line 80 of file Message.h.
Referenced by GetPeerId(), Omiscid::MsgManager::Receive(), and ToString().
unsigned int Omiscid::Message::mid [protected]
message id
Definition at line 81 of file Message.h.
Referenced by GetMsgId(), Omiscid::MsgManager::Receive(), and ToString().
char* Omiscid::Message::realBuffer [protected]
the buffer allocated for the message with a byte before the message data. (Rq : buffer = realBuffer + 1)
Definition at line 87 of file Message.h.
Referenced by Message(), and ~Message().
The documentation for this class was generated from the following files:
Com/Com/Message.h
Com/Message.cpp