OMiSCID(aka O3MiSCID): Omiscid::UdpExchange Class Reference
Omiscid::UdpExchange Class Reference
Class to manage with UDP exchange using BIP.
#include <Com/UdpExchange.h>
Public Member Functions
UdpExchange ()
Default Constructor.
UdpExchange (int port)
Constructor.
virtual ~UdpExchange ()
Destructor.
void Create (int port)
Bind UDP socket to a port.
void Disconnect ()
Destroy all UDP connections on this socket.
bool DisconnectPeerId (unsigned int PeerId)
Destroy a specific connection.
void Close ()
Close this socket.
int SendTo (int len, const char *buf, const char *addr, int port)
Send a message to a particular address.
int SendTo (int len, const char *buf, UdpConnection *ptr)
Send a message to a particular address, already known by the object.
int SendTo (int len, const char *buf, unsigned int pid)
Send a message to a particular point identify by a peer id.
void SendToAll (int len, const char *buf)
Send a message to all the known client.
int GetNbConnections ()
Access to the number of current connections.
void SetServiceId (unsigned int pid)
unsigned int GetServiceId () const
Access to the service Id.
unsigned short GetUdpPort ()
Access to the UDP port.
int GetListPeerId (SimpleList< unsigned int > &listId)
List of peer Id.
virtual ComTools * Cast ()
Cast in ComTools.
Protected Member Functions
virtual UdpConnection * AcceptConnection (const UdpConnection &udp_connect, bool msg_empty)
Call when message arrives from a UDP source.
UdpConnection * FindConnectionFromId (unsigned int id)
find the data about a connection with a particular id
bool RemoveConnectionWithId (unsigned int pid)
Remove the data about a connection with a particular id.
Protected Attributes
MutexedSimpleList
< UdpConnection * > listUdpConnections
Detailed Description
Class to manage with UDP exchange using BIP.
The implementation does not use Client / Server aspect, since this distinction does not exist with UDP. This class manages client or server in a symetric way.
In some description, the term of client is employed, a client is an UDP socket who send a message (an empty message), the source of the message is kept in a list.
Author:
Sebastien Pesnel
Definition at line 33 of file UdpExchange.h.
Constructor & Destructor Documentation
UdpExchange::UdpExchange ()
Default Constructor.
Create a UDP socket
Definition at line 8 of file UdpExchange.cpp.
: MsgSocket(Socket::UDP)
{
}
UdpExchange::UdpExchange (int port)
Constructor.
Create a UDP socket. Bind the socket to a port
Parameters:
port [in] port where listen.
See also:
Create
Definition at line 13 of file UdpExchange.cpp.
References Create().
: MsgSocket(Socket::UDP)
{
    Create(port);
}
Member Function Documentation
void UdpExchange::Create (int port)
Bind UDP socket to a port.
Parameters:
port [in] port where listen. Note : if port value is 0, a free port is chosen.
Definition at line 25 of file UdpExchange.cpp.
References Omiscid::MsgSocket::InitForUdpExchange(), and Omiscid::Thread::StartThread().
Referenced by Omiscid::Connector::ConnectTo(), Omiscid::Connector::Create(), and UdpExchange().
{
    InitForUdpExchange(port);
    StartThread();
}
int UdpExchange::SendTo (int len, const char * buf, const char * addr, int port)
Send a message to a particular address.
Parameters:
len [in] the length of the message
buf [in] array containing the message.
addr [in] the address of the host to contact
port [in] the port number where sent the data.
Returns:
the number of sent bytes.
Definition at line 49 of file UdpExchange.cpp.
References Omiscid::UdpConnection::addr, and Omiscid::MsgSocket::SendTo().
Referenced by SendToAll(), Omiscid::Connector::SendToAll(), and Omiscid::Connector::SendToPeer().
{
    UdpConnection udp_connect;
    //REVIEW
    /*
    udp_connect.addr.sin_family = AF_INET;
    udp_connect.addr.sin_port = htons(port);
    if(!strcmp(addr, ""))  udp_connect.addr.sin_addr.s_addr = INADDR_ANY;
    else udp_connect.addr.sin_addr.s_addr = inet_addr(addr);
    memset(&(udp_connect.addr.sin_zero), 0, 8); */
    if ( Socket::FillAddrIn( &udp_connect.addr, addr, port ) == false )
        return -1;      // Socket error
    return MsgSocket::SendTo(len, buf, &udp_connect);
}
int UdpExchange::SendTo (int len, const char * buf, UdpConnection * ptr)
Send a message to a particular address, already known by the object.
This function can be used to answer to a request.
Parameters:
len [in] the length of the message
buf [in] array containing the message.
ptr [in] a pointer to an UdpConnection object containing the address where send the message.
Returns:
the number of sent bytes.
Reimplemented from Omiscid::MsgSocket.
Definition at line 248 of file UdpExchange.cpp.
References Omiscid::MsgSocket::SendTo().
{
    return MsgSocket::SendTo(len, buf, ptr);
}
int UdpExchange::SendTo (int len, const char * buf, unsigned int pid)
Send a message to a particular point identify by a peer id.
This function can be used to answer to a request.
Parameters:
len [in] the length of the message
buf [in] array containing the message.
pid [in] the id of the client.
Returns:
the number of sent bytes.
Definition at line 66 of file UdpExchange.cpp.
References Omiscid::SimpleException::err, FindConnectionFromId(), Omiscid::SimpleString::GetStr(), listUdpConnections, Omiscid::SimpleException::msg, and Omiscid::MsgSocket::SendTo().
{
    int nb_send = 0;
    SmartLocker SL_listUdpConnections(listUdpConnections);
    UdpConnection* ptr = FindConnectionFromId(pid);
    if(ptr)
    {
        try
        {
            nb_send = MsgSocket::SendTo(len, buf, ptr);
        }
        catch( SocketException &e )
        {
            OmiscidTrace( "Error while sending to all peer %8.8x : %s (%d)\n", pid, e.msg.GetStr(), e.err );
        }
    }
    return nb_send;
}
void UdpExchange::SendToAll (int len, const char * buf)
Send a message to all the known client.
Parameters:
len [in] the length of the message
buf [in] array containing the message.
Definition at line 88 of file UdpExchange.cpp.
References Omiscid::SimpleException::err, Omiscid::SimpleString::GetStr(), listUdpConnections, Omiscid::SimpleException::msg, and SendTo().
{
    SmartLocker SL_listUdpConnections(listUdpConnections);
    for(listUdpConnections.First(); listUdpConnections.NotAtEnd(); listUdpConnections.Next())
    {
        try
        {
            SendTo(len, buf, (listUdpConnections.GetCurrent()));
        }
        catch( SocketException &e )
        {
            OmiscidTrace( "Error while sending to all peers : %s (%d)\n", e.msg.GetStr(), e.err );
        }
    }
}
int UdpExchange::GetNbConnections ()
Access to the number of current connections.
Returns:
the number of known connections
Definition at line 105 of file UdpExchange.cpp.
References listUdpConnections.
{
    SmartLocker SL_listUdpConnections(listUdpConnections);
    int nb = listUdpConnections.GetNumberOfElements();
    return nb;
}
void UdpExchange::SetServiceId (unsigned int pid) [virtual]
define the identifier of the service associated to this object
Parameters:
pid [in] the value for the identifier
Implements Omiscid::ComTools.
Reimplemented in Omiscid::Connector.
Definition at line 225 of file UdpExchange.cpp.
References Omiscid::MsgSocket::SetServiceId().
Referenced by Omiscid::Connector::SetServiceId().
{
    // Check validity of a service Id
    if ( (pid & ComTools::CONNECTOR_ID) == 0 )
    {
        // pid = pid | 0xffffff01;
#ifdef DEBUG
        //              fprintf( stderr, "Warning: ConnectorId could not be 0 for UdpExchange. Value changes to 1 (PeerId = %8.8x)\n", pid );
#endif
    }
    MsgSocket::SetServiceId(pid);
}
unsigned int UdpExchange::GetServiceId () const [virtual]
Access to the service Id.
Returns:
the service id
Implements Omiscid::ComTools.
Reimplemented in Omiscid::Connector.
Definition at line 243 of file UdpExchange.cpp.
References Omiscid::MsgSocket::GetServiceId().
{
    return MsgSocket::GetServiceId();
}
unsigned short UdpExchange::GetUdpPort () [virtual]
Access to the UDP port.
Returns:
the port where the socket listens
Reimplemented from Omiscid::ComTools.
Reimplemented in Omiscid::Connector.
Definition at line 253 of file UdpExchange.cpp.
References Omiscid::MsgSocket::GetPortNb().
Referenced by Omiscid::Connector::ConnectTo(), Omiscid::Connector::Create(), and Omiscid::Connector::GetUdpPort().
{
    return MsgSocket::GetPortNb();
}
int UdpExchange::GetListPeerId (SimpleList< unsigned int > & listId) [virtual]
List of peer Id.
Parameters:
listId [in,out] add to the end of this list the peer ids
Returns:
the number of peer id added to the list
Implements Omiscid::ComTools.
Reimplemented in Omiscid::Connector.
Definition at line 141 of file UdpExchange.cpp.
References Omiscid::SimpleList< TYPE >::Add(), and listUdpConnections.
{
    int nb =0;
    SmartLocker SL_listUdpConnections(listUdpConnections);
    for(listUdpConnections.First(); listUdpConnections.NotAtEnd(); listUdpConnections.Next())
    {
        listId.Add((listUdpConnections.GetCurrent())->pid);
        nb++;
    }
    return nb;
}
ComTools * UdpExchange::Cast () [virtual]
Cast in ComTools.
Returns:
the Comtool pointer on an object that derived Comtool
Implements Omiscid::ComTools.
Reimplemented in Omiscid::Connector.
Definition at line 238 of file UdpExchange.cpp.
{
    return dynamic_cast<ComTools*>(this);
}
UdpConnection * UdpExchange::AcceptConnection (const UdpConnection & udp_connect, bool msg_empty) [protected, virtual]
Call when message arrives from a UDP source.
find the UdpConnection object associated to an UDP connection, or create a new UdpConnection object if it is the first connection (first contact is done with empty message). The research is done by using the peer identifier
Parameters:
udp_connect [in] the data of the connection, base for the research or the creation of a new UdpConnection object, contains the peer identifier.
msg_empty [in] define if the message, sent by peer, was empty.
Returns:
NULL if connection refused, or the UdpConnection oebjct associated to the connection.
Reimplemented from Omiscid::MsgSocket.
Reimplemented in Omiscid::Connector.
Definition at line 114 of file UdpExchange.cpp.
References listUdpConnections.
{
    //std::cerr << "in UdpExchange::acceptConnection(UdpConnection*)\n";
    SmartLocker SL_listUdpConnections(listUdpConnections);
    UdpConnection* udp_found = NULL;
    for ( listUdpConnections.First(); !udp_found && listUdpConnections.NotAtEnd(); listUdpConnections.Next())
    {
        if(udp_connect == *(listUdpConnections.GetCurrent()))
        {
            udp_found = listUdpConnections.GetCurrent();
        }
    }
    if(!udp_found && msg_empty)
    {
        udp_found = new OMISCID_TLM UdpConnection(udp_connect);
        listUdpConnections.Add(udp_found);
    }
    else if (!msg_empty)
    {
        OmiscidTrace( "Connection UDP from refused (Unknown, not initialized with empty message)\n");
    }
    return udp_found;
}
UdpConnection * UdpExchange::FindConnectionFromId (unsigned int id) [protected]
find the data about a connection with a particular id
do not lock the list of connection during the research.
Parameters:
id the connection identifier : the distant peer
Returns:
NULL if not found, else the data about the peer
Definition at line 156 of file UdpExchange.cpp.
References listUdpConnections, and Omiscid::SmartLocker::Unlock().
Referenced by Omiscid::Connector::AcceptConnection(), SendTo(), and Omiscid::Connector::SendToAll().
{
    unsigned int SearchId = id;
    SmartLocker SL_listUdpConnections(listUdpConnections);
    for(listUdpConnections.First(); listUdpConnections.NotAtEnd(); listUdpConnections.Next())
    {
        if( listUdpConnections.GetCurrent()->pid == SearchId )
        {
            return listUdpConnections.GetCurrent();
        }
    }
    // By default search for the ServiceId
    SearchId = id & ComTools::SERVICE_PEERID;
    for(listUdpConnections.First(); listUdpConnections.NotAtEnd(); listUdpConnections.Next())
    {
        if ( SearchId == (listUdpConnections.GetCurrent()->pid & ComTools::SERVICE_PEERID) )
        {
            SL_listUdpConnections.Unlock();
            return listUdpConnections.GetCurrent();
        }
    }
    return NULL;
}
bool UdpExchange::RemoveConnectionWithId (unsigned int pid) [protected]
Remove the data about a connection with a particular id.
Do not lock the list of connection during the research
Parameters:
pid [in] connection id for the connection to remove
Returns:
true if a connection is removed, false otherwise.
Definition at line 209 of file UdpExchange.cpp.
References listUdpConnections.
Referenced by Omiscid::Connector::AcceptConnection(), and Omiscid::Connector::SendToAll().
{
    SmartLocker SL_listUdpConnections(listUdpConnections);
    for(listUdpConnections.First(); listUdpConnections.NotAtEnd(); listUdpConnections.Next())
    {
        if(listUdpConnections.GetCurrent()->pid == pid)
        {
            delete listUdpConnections.GetCurrent();
            listUdpConnections.RemoveCurrent();
            return true;
        }
    }
    return false;
}
Member Data Documentation
MutexedSimpleList<UdpConnection*> Omiscid::UdpExchange::listUdpConnections [protected]
list of the known UDP connections
Definition at line 148 of file UdpExchange.h.
Referenced by AcceptConnection(), Omiscid::Connector::AcceptConnection(), Disconnect(), DisconnectPeerId(), FindConnectionFromId(), GetListPeerId(), GetNbConnections(), RemoveConnectionWithId(), SendTo(), SendToAll(), and Omiscid::Connector::SendToAll().
The documentation for this class was generated from the following files:
Com/Com/UdpExchange.h
Com/UdpExchange.cpp