OMiSCID(aka O3MiSCID): Omiscid::Thread Class Reference
Omiscid::Thread Class Reference
Thread Implementation.
#include <System/Thread.h>
Public Member Functions
Thread ()
Constructor.
virtual ~Thread ()
Destructor.
virtual bool StartThread ()
Start the thread.
virtual bool StopThread (int wait_ms=DEFAULT_THREAD_DESTRUCTOR_TIMEOUT)
Stop the thread.
bool IsRunning () const
Return if the thread is running.
void SendMessage (int cCode, void *cParam1, void *cParam2=(void *) NULL)
Send message to a Thread.
void SendMessage (const ThreadMessage &MsgToSend)
Send message to a Thread.
Static Public Member Functions
static void Sleep (int nb_ms)
the calling thread sleep
static unsigned int GetThreadId ()
return an Id for the calling Thread
Protected Member Functions
bool WaitAndGetMessage (ThreadMessage &MsgToSend, unsigned int TimeOut=(unsigned int) DEFAULT_MESSAGE_TIMEOUT)
Retrieve message for a thread with timeout.
bool GetMessage (ThreadMessage &MsgToSend)
Get a message for a thread.
virtual void FUNCTION_CALL_TYPE Run ()=0
Method executed in a thread.
bool StopPending () const
Return if stop is required.
void WaitForStop ()
Wait until if stop is required.
Detailed Description
Thread Implementation.
Enable to execute methods in another thread. The users must inherite from this class and write the methods 'Run'. The code in 'Run' will executed in a new thread after a call to the method 'Start'. This code would have to check the value of StopPending to stop if stop is required.
Author:
Dominique Vaufreydaz
Sebastien Pesnel
Definition at line 69 of file Thread.h.
Constructor & Destructor Documentation
Thread::Thread ()
Constructor.
Definition at line 55 of file Thread.cpp.
{
#ifdef DEBUG_THREAD
    ThreadName = Name;
#endif
#ifdef WIN32
    ThreadID = 0;
    ThreadHandle  = NULL;
#else
    m_thread = (pthread_t)0;
#endif
    ThreadIsRunning = false;
    StopWasAsked = false;
}
Thread::~Thread () [virtual]
Destructor.
Ask the end of the thread, and wait that the thread terminates during maximum one second.
Definition at line 73 of file Thread.cpp.
References IsRunning(), and StopThread().
{
    if(IsRunning())
    {
        StopThread();
    }
}
Member Function Documentation
bool Thread::StartThread () [virtual]
Start the thread.
Execute the method Run in a new thread. Begin by stopping the thread if it is running.
Definition at line 81 of file Thread.cpp.
References IsRunning().
Referenced by Omiscid::TcpServer::AcceptConnection(), Omiscid::ControlClient::ConnectToCtrlServer(), Omiscid::TcpClient::ConnectToServer(), Omiscid::UdpExchange::Create(), Omiscid::TcpServer::Create(), and Omiscid::ControlServer::StartThreadProcessMsg().
{
    // do nothing if already running
    if ( IsRunning() )
    {
        return false;
    }
    ThreadIsRunning = false;
    StopWasAsked = false;
#ifdef DEBUG_THREAD
    OmiscidTrace( "StartThread : %s\n", ThreadName.GetStr() );
#endif
#ifdef WIN32
    ThreadID = 0;
    ThreadHandle = CreateThread( NULL, 0, CallRun, (void*)this, 0, &ThreadID );
    return (ThreadHandle != NULL);
#else
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    int rc = pthread_create(&m_thread, &attr, CallRun, this);
    pthread_attr_destroy(&attr);
    return (rc == 0);
#endif
}
bool Thread::StopThread (int wait_ms = DEFAULT_THREAD_DESTRUCTOR_TIMEOUT) [virtual]
Stop the thread.
Ask the thread to stop. Wait the end of the thread. If 'wait_ms' is not null, wait during a limited time of 'wait_ms' milliseconds.
Parameters:
wait_ms time to wait (0 for infinite time)
Definition at line 112 of file Thread.cpp.
References IsRunning(), Omiscid::Event::Signal(), and Omiscid::Event::Wait().
Referenced by Omiscid::TcpServer::Close(), Omiscid::MsgSocket::Stop(), Omiscid::ControlClient::~ControlClient(), Omiscid::ControlServer::~ControlServer(), ~Thread(), and Omiscid::XMLTreeParser::~XMLTreeParser().
{
    bool ThreadStopInTime = true;
    if (IsRunning())
    {
#ifdef DEBUG_THREAD
        OmiscidTrace( "Ask %s to stop.\n", ThreadName.GetStr() );
#endif
        // Notify thread !
        StopWasAsked = true;                    // Notification for pseudo active waiting
        StopWasAskedEvent.Signal();             // other notification
        ThreadStopInTime = IsEnded.Wait(wait_ms);
        if ( ThreadStopInTime == false )
        {
            // Timeout !!!
#ifdef DEBUG_THREAD
            OmiscidError( "Thread::StopThread: %s do not stop before timeout (%d).\n",  ThreadName.GetStr(), wait_ms );
#else
            OmiscidError( "Thread::StopThread: Thread do not stop before timeout (%d).\n",  wait_ms );
#endif
            // Destroy the thread...
#ifdef WIN32
            // TerminateThread( ThreadHandle, 0 );
            ThreadID = 0;
            ThreadHandle  = NULL;
#else
            // pthread_cancel(m_thread);
#endif
        }
    }
#ifdef DEBUG_THREAD
    OmiscidTrace( "Thread %s stopped.\n", ThreadName.GetStr() );
#endif
    return ThreadStopInTime;
}
void Thread::Sleep (int nb_ms) [static]
the calling thread sleep
Parameters:
nb_ms [in] number of milliseconds to sleep
Definition at line 201 of file Thread.cpp.
Referenced by WaitAndGetMessage(), and Omiscid::MsgSocket::WaitSyncLinkMsg().
{
#ifdef WIN32
    // Use SleepEx because accuracy of the wait time is better than with ::Sleep
    ::SleepEx(nb_ms, FALSE);
#else
    usleep(nb_ms*1000);
#endif
}
bool Thread::IsRunning () const
Return if the thread is running.
Returns:
true if the thread is running
Definition at line 211 of file Thread.cpp.
Referenced by StartThread(), StopThread(), and ~Thread().
{
    return ThreadIsRunning;
}
void Thread::SendMessage (int Code, void * Param1, void * Param2 = (void*)NULL)
Send message to a Thread.
Send a message to a thread
Definition at line 242 of file Thread.cpp.
{
    ThreadMessage MsgToSend( Code, Param1, Param2 );
    SmartLocker SL_MsgQueue(MsgQueue);
    MsgQueue.AddTail(MsgToSend);
}
void Thread::SendMessage (const ThreadMessage & MsgToSend)
Send message to a Thread.
Send a message to a thread
Definition at line 255 of file Thread.cpp.
{
    SmartLocker SL_MsgQueue(MsgQueue);
    MsgQueue.AddTail(MsgToSend);
}
unsigned int Thread::GetThreadId () [static]
return an Id for the calling Thread
Definition at line 229 of file Thread.cpp.
Referenced by Omiscid::ReentrantMutex::Lock(), and Omiscid::Mutex::Lock().
{
#ifdef WIN32
    return (unsigned int)GetCurrentThreadId();
#else
    return (unsigned int)pthread_self();
#endif
}
bool Thread::WaitAndGetMessage (ThreadMessage & MsgToGet, unsigned int DelayMax = (unsigned int)DEFAULT_MESSAGE_TIMEOUT) [protected]
Retrieve message for a thread with timeout.
Retrieve message for a thread
Definition at line 266 of file Thread.cpp.
References Omiscid::ElapsedTime::Get(), Omiscid::SmartLocker::Lock(), Sleep(), and Omiscid::SmartLocker::Unlock().
{
    bool Done;
    SmartLocker SL_MsgQueue(MsgQueue, false);
    if ( DelayMax == 0 )
    {
        // INFINITE wait
        Done = false;
        while( true ) // was for(;;) but new version of MS compiler do no like it
        {
            // Is there a message ?
            SL_MsgQueue.Lock();
            if ( MsgQueue.GetNumberOfElements() != 0 )
            {
                MsgToGet = MsgQueue.ExtractFirst();
                Done = true;
            }
            SL_MsgQueue.Unlock();
            if ( Done == true )
            {
                return true;
            }
            // Wait
            Sleep( 10 );
        }
        // never here
        return true;
    }
    else
    {
        ElapsedTime CountWaitedTime;
        Done = false;
        while( true ) // was for(;;) but new version of MS compiler do no like it
        {
            // Is there a message ?
            SL_MsgQueue.Lock();
            if ( MsgQueue.GetNumberOfElements() != 0 )
            {
                MsgToGet = MsgQueue.ExtractFirst();
                Done = true;
            }
            SL_MsgQueue.Unlock();
            if ( Done == true )
            {
                return true;
            }
            if ( Done == true || CountWaitedTime.Get() >= DelayMax )
            {
                return Done;
            }
            Sleep( 10 );
        }
        // never here
        return true;
    }
    return false;
}
bool Thread::GetMessage (ThreadMessage & MsgToSend) [protected]
Get a message for a thread.
Get message for a thread
Definition at line 336 of file Thread.cpp.
{
    SmartLocker SL_MsgQueue(MsgQueue);
    if ( MsgQueue.GetNumberOfElements() == 0 )
    {
        // No message
        return false;
    }
    // get first message
    MsgToSend = MsgQueue.ExtractFirst();
    return true;
}
virtual void FUNCTION_CALL_TYPE Omiscid::Thread::Run () [protected, pure virtual]
Method executed in a thread.
Overload this virtual function and provide your own thread implementation.
Implemented in Omiscid::MsgSocket, Omiscid::XMLTreeParser, and Omiscid::RegisterThread.
bool Thread::StopPending () const [protected]
Return if stop is required.
Returns:
true if the thread should stop
Definition at line 216 of file Thread.cpp.
Referenced by Omiscid::XMLTreeParser::Run(), and Omiscid::MsgSocket::Run().
{
    return StopWasAsked;
}
void Thread::WaitForStop () [protected]
Wait until if stop is required.
Definition at line 221 of file Thread.cpp.
References Omiscid::Event::Wait().
Referenced by Omiscid::RegisterThread::Run().
{
    StopWasAskedEvent.Wait(0);
}
The documentation for this class was generated from the following files:
System/System/Thread.h
System/Thread.cpp