OMiSCID(aka O3MiSCID): Omiscid::LockableObject Class Reference
Omiscid::LockableObject Class Reference
LockableObject are object that can be lock (Mutex, ReentrantMutex, MutexedSimpleList, ...).
#include <System/LockManagement.h>
Public Member Functions
LockableObject ()
Constructor.
virtual ~LockableObject ()
Constructor.
virtual bool Lock ()=0
Virtual function used to lock the object.
virtual bool Unlock ()=0
Virtual function used to unlock the object.
Detailed Description
LockableObject are object that can be lock (Mutex, ReentrantMutex, MutexedSimpleList, ...).
Author:
Dominique Vaufreydaz
Definition at line 20 of file LockManagement.h.
Constructor & Destructor Documentation
Omiscid::LockableObject::LockableObject () [inline]
Constructor.
Definition at line 26 of file LockManagement.h.
{};
virtual Omiscid::LockableObject::~LockableObject () [inline, virtual]
Constructor.
Definition at line 31 of file LockManagement.h.
{};
Member Function Documentation
virtual bool Omiscid::LockableObject::Lock () [pure virtual]
Virtual function used to lock the object.
Implemented in Omiscid::Mutex, Omiscid::MutexedSimpleRecycleList< TYPE >, Omiscid::ReentrantMutex, Omiscid::MutexedSimpleList< TYPE >, Omiscid::MutexedSimpleList< Omiscid::XMLMessage * >, Omiscid::MutexedSimpleList< Omiscid::ThreadMessage >, Omiscid::MutexedSimpleList< Omiscid::ServiceRepositoryListener * >, Omiscid::MutexedSimpleList< Omiscid::ClientConnection * >, Omiscid::MutexedSimpleList< Omiscid::ValueListener * >, Omiscid::MutexedSimpleList< Omiscid::VariableAttributeListener * >, Omiscid::MutexedSimpleList< Omiscid::MsgSocket * >, Omiscid::MutexedSimpleList< Omiscid::AnswerWaiter * >, Omiscid::MutexedSimpleList< Omiscid::UdpConnection * >, Omiscid::MutexedSimpleList< Omiscid::MsgSocketCallbackObject * >, and Omiscid::MutexedSimpleList< Omiscid::Message * >.
Referenced by Omiscid::SmartLocker::Lock().
virtual bool Omiscid::LockableObject::Unlock () [pure virtual]
Virtual function used to unlock the object.
Implemented in Omiscid::Mutex, Omiscid::MutexedSimpleRecycleList< TYPE >, Omiscid::ReentrantMutex, Omiscid::MutexedSimpleList< TYPE >, Omiscid::MutexedSimpleList< Omiscid::XMLMessage * >, Omiscid::MutexedSimpleList< Omiscid::ThreadMessage >, Omiscid::MutexedSimpleList< Omiscid::ServiceRepositoryListener * >, Omiscid::MutexedSimpleList< Omiscid::ClientConnection * >, Omiscid::MutexedSimpleList< Omiscid::ValueListener * >, Omiscid::MutexedSimpleList< Omiscid::VariableAttributeListener * >, Omiscid::MutexedSimpleList< Omiscid::MsgSocket * >, Omiscid::MutexedSimpleList< Omiscid::AnswerWaiter * >, Omiscid::MutexedSimpleList< Omiscid::UdpConnection * >, Omiscid::MutexedSimpleList< Omiscid::MsgSocketCallbackObject * >, and Omiscid::MutexedSimpleList< Omiscid::Message * >.
Referenced by Omiscid::SmartLocker::Unlock(), and Omiscid::SmartLocker::~SmartLocker().
The documentation for this class was generated from the following file:
System/System/LockManagement.h