OMiSCID(aka O3MiSCID): Omiscid::ElapsedTime Class Reference
Omiscid::ElapsedTime Class Reference
Enable to compute the elapse time between two calls in milliseconds.
#include <System/ElapsedTime.h>
Public Member Functions
ElapsedTime ()
Constructor.
virtual ~ElapsedTime ()
Virtual destructor.
void Reset ()
reset the start time
unsigned int Get (bool DoReset=false)
Get the elapsed time in ms since construction or last reset.
Detailed Description
Enable to compute the elapse time between two calls in milliseconds.
Author:
Dominique Vaufreydaz
Definition at line 21 of file ElapsedTime.h.
Constructor & Destructor Documentation
ElapsedTime::~ElapsedTime () [virtual]
Virtual destructor.
Destructor.
Definition at line 18 of file ElapsedTime.cpp.
{
}
Member Function Documentation
void ElapsedTime::Reset ()
reset the start time
reset start time
Definition at line 23 of file ElapsedTime.cpp.
Referenced by ElapsedTime().
{
    struct timeval CurrentTimeOfDay;
    // retrieve the current time
    gettimeofday(&CurrentTimeOfDay, NULL);
    // Compute the time in ms since epoque
    StartTime = CurrentTimeOfDay.tv_sec * 1000 + CurrentTimeOfDay.tv_usec/1000;
}
unsigned int ElapsedTime::Get (bool DoReset = false)
Get the elapsed time in ms since construction or last reset.
Parameters:
DoReset says if we need to reset the object with a new start time
Returns:
the Elapsed Time in ms since the
Definition at line 38 of file ElapsedTime.cpp.
Referenced by Omiscid::Thread::WaitAndGetMessage(), and Omiscid::MsgSocket::WaitSyncLinkMsg().
{
    struct timeval CurrentTimeOfDay;
    unsigned int   CurrentTime;
    unsigned int   CurrentElapsedTime;
    // retrieve the current time
    gettimeofday(&CurrentTimeOfDay, NULL);
    // Compute the time in ms since epoque
    CurrentTime = CurrentTimeOfDay.tv_sec * 1000 + CurrentTimeOfDay.tv_usec/1000;
    CurrentElapsedTime = CurrentTime - StartTime;
    if ( DoReset == true )
    {
        // Reset the Time and return elapsed time
        StartTime = CurrentTime;
    }
    return CurrentElapsedTime;
}
The documentation for this class was generated from the following files:
System/System/ElapsedTime.h
System/ElapsedTime.cpp